### ISSUE TITLE
FRM image in VTD table

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#123]
FRM image stored/retrieved from blob in VTD table.

**Comment by midenok** [comment]
### Create FRM
```
#0  open64 () at ../sysdeps/unix/syscall-template.S:84
#1  0x00005555565aa89e in my_create (FileName=0x7fffe5748900 "./test/d2.frm", CreateFlags=0, access_flags=514, MyFlags=0) at /home/midenok/src/mariadb/midenok/src/mysys/my_create.c:46
#2  0x0000555555dbc1f2 in inline_mysql_file_create (key=0, src_file=0x5555567c60e8 "/home/midenok/src/mariadb/midenok/src/sql/discover.cc", src_line=129, filename=0x7fffe5748900 "./test/d2.frm", create_flags=0, access_flags=514, myFlags=0) at /home/midenok/src/mariadb/midenok/src/include/mysql/psi/mysql_file.h:1007
#3  0x0000555555dbcbaa in writefrm (path=0x7fffe574ba10 "./test/d2", db=0x7fff8c011740 "test", table=0x7fff8c0110d8 "d2", tmp_table=false, frmdata=0x7fff8c098db0 "\376\001\n\f\035", len=519) at /home/midenok/src/mariadb/midenok/src/sql/discover.cc:128
#4  0x0000555555c5c5c4 in TABLE_SHARE::write_frm_image (this=0x7fffe5748fe0, frm=0x7fff8c098db0 "\376\001\n\f\035", len=519) at /home/midenok/src/mariadb/midenok/src/sql/table.cc:2727
#5  0x0000555555c56cc6 in TABLE_SHARE::init_from_binary_frm_image (this=0x7fffe5748fe0, thd=0x7fff8c000b00, write=true, frm_image=0x7fff8c098db0 "\376\001\n\f\035", frm_length=519) at /home/midenok/src/mariadb/midenok/src/sql/table.cc:1215
#6  0x0000555555dfcd64 in ha_create_table (thd=0x7fff8c000b00, path=0x7fffe574ba10 "./test/d2", db=0x7fff8c011740 "test", table_name=0x7fff8c0110d8 "d2", create_info=0x7fffe574bff0, frm=0x7fffe574ba00) at /home/midenok/src/mariadb/midenok/src/sql/handler.cc:4761
#7  0x0000555555c76d5d in rea_create_table (thd=0x7fff8c000b00, frm=0x7fffe574ba00, path=0x7fffe574ba10 "./test/d2", db=0x7fff8c011740 "test", table_name=0x7fff8c0110d8 "d2", create_info=0x7fffe574bff0, file=0x7fff8c011d48, no_ha_create_table=false) at /home/midenok/src/mariadb/midenok/src/sql/unireg.cc:500
#8  0x0000555555c211a1 in create_table_impl (thd=0x7fff8c000b00, orig_db=0x7fff8c011740 "test", orig_table_name=0x7fff8c0110d8 "d2", db=0x7fff8c011740 "test", table_name=0x7fff8c0110d8 "d2", path=0x7fffe574ba10 "./test/d2", options=..., create_info=0x7fffe574bff0, alter_info=0x7fffe574bf40, create_table_mode=0, is_trans=0x7fffe574bc6e, key_info=0x7fffe574b9f0, key_count=0x7fffe574b9e4, frm=0x7fffe574ba00) at /home/midenok/src/mariadb/midenok/src/sql/sql_table.cc:4833
#9  0x0000555555c217b0 in mysql_create_table_no_lock (thd=0x7fff8c000b00, db=0x7fff8c011740 "test", table_name=0x7fff8c0110d8 "d2", create_info=0x7fffe574bff0, alter_info=0x7fffe574bf40, is_trans=0x7fffe574bc6e, create_table_mode=0, table_list=0x7fff8c011110) at /home/midenok/src/mariadb/midenok/src/sql/sql_table.cc:4946
#10 0x0000555555c21afc in mysql_create_table (thd=0x7fff8c000b00, create_table=0x7fff8c011110, create_info=0x7fffe574bff0, alter_info=0x7fffe574bf40) at /home/midenok/src/mariadb/midenok/src/sql/sql_table.cc:5019
#11 0x0000555555b567f9 in mysql_execute_command (thd=0x7fff8c000b00) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:4084
#12 0x0000555555b60abc in mysql_parse (thd=0x7fff8c000b00, rawbuf=0x7fff8c010fd8 "create or replace table d2 (x int) engine innodb with system versioning", length=71, parser_state=0x7fffe574c6b0, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:7902
```
### Open FRM
```
#0  open64 () at ../sysdeps/unix/syscall-template.S:84
#1  0x00005555565b5379 in my_open (FileName=0x7fffe574ba20 "./test/d2.frm", Flags=0, MyFlags=0) at /home/midenok/src/mariadb/midenok/src/mysys/my_open.c:57
#2  0x0000555555c53603 in inline_mysql_file_open (key=0, src_file=0x5555566c0d08 "/home/midenok/src/mariadb/midenok/src/sql/table.cc", src_line=603, filename=0x7fffe574ba20 "./test/d2.frm", flags=0, myFlags=0) at /home/midenok/src/mariadb/midenok/src/include/mysql/psi/mysql_file.h:1053
#3  0x0000555555c5508a in open_table_def (thd=0x7fff8c000b00, share=0x7fff8c01c718, flags=11) at /home/midenok/src/mariadb/midenok/src/sql/table.cc:603
#4  0x0000555555d38017 in tdc_acquire_share (thd=0x7fff8c000b00, tl=0x7fffe574c6b0, flags=3, out_table=0x7fffe574bd48) at /home/midenok/src/mariadb/midenok/src/sql/table_cache.cc:825
#5  0x0000555555ad6bf7 in open_table (thd=0x7fff8c000b00, table_list=0x7fffe574c6b0, ot_ctx=0x7fffe574c350) at /home/midenok/src/mariadb/midenok/src/sql/sql_base.cc:1742
#6  0x0000555555ad9d03 in open_and_process_table (thd=0x7fff8c000b00, lex=0x7fff8c004618, tables=0x7fffe574c6b0, counter=0x7fffe574c41c, flags=1024, prelocking_strategy=0x7fffe574c420, has_prelocking_list=false, ot_ctx=0x7fffe574c350) at /home/midenok/src/mariadb/midenok/src/sql/sql_base.cc:3414
#7  0x0000555555adaefc in open_tables (thd=0x7fff8c000b00, options=..., start=0x7fffe574c400, counter=0x7fffe574c41c, flags=1024, prelocking_strategy=0x7fffe574c420) at /home/midenok/src/mariadb/midenok/src/sql/sql_base.cc:3932
#8  0x0000555555ad395a in open_tables (thd=0x7fff8c000b00, tables=0x7fffe574c400, counter=0x7fffe574c41c, flags=1024, prelocking_strategy=0x7fffe574c420) at /home/midenok/src/mariadb/midenok/src/sql/sql_base.h:236
#9  0x0000555555adc7de in open_normal_and_derived_tables (thd=0x7fff8c000b00, tables=0x7fffe574c6b0, flags=1024, dt_phases=34) at /home/midenok/src/mariadb/midenok/src/sql/sql_base.cc:4750
#10 0x0000555555be87f7 in mysqld_list_fields (thd=0x7fff8c000b00, table_list=0x7fffe574c6b0, wild=0x7fff8c010ff8 "") at /home/midenok/src/mariadb/midenok/src/sql/sql_show.cc:1428
#11 0x0000555555b5153c in dispatch_command (command=COM_FIELD_LIST, thd=0x7fff8c000b00, packet=0x7fff8c0087f4 "", packet_length=3, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:2008
```

**Comment by midenok** [comment]
Deprecated due to 2.0 DDL Survival.
