### ISSUE TITLE
Particular JOIN query fails on versioned table.

### ISSUE THREAD

**Issue by kevgs** [tempesta-tech/mariadb#145]
```sql
create table t1 (a int not null auto_increment primary key) with system versioning;
select * from (t1 as t2 left join t1 as t3 using (a)) natural left join t1;
drop table t1;
```

```
mysqltest: At line 2: query 'select * from (t1 as t2 left join t1 as t3 using (a)) natural left join t1' failed: 1052: Column 'sys_trx_start' in from clause is ambiguous
```

Found in `select.test` by using a forced versioning feature.

**Comment by kevgs** [comment]
```c++
#0  my_error (nr=1052, MyFlags=0) at /home/kevg/work/mariadb_10.2/mysys/my_error.c:113
#1  0x0000000000673509 in mark_common_columns (thd=0x7fffe0000b00, table_ref_1=0x7fffe0013a80, table_ref_2=0x7fffe0014188, using_fields=0x0, found_using_fields=0x7ffff09c468c)
    at /home/kevg/work/mariadb_10.2/sql/sql_base.cc:6351
#2  0x0000000000672b8f in store_top_level_join_columns (thd=0x7fffe0000b00, table_ref=0x7fffe00147c8, left_neighbor=0x0, right_neighbor=0x0) at /home/kevg/work/mariadb_10.2/sql/sql_base.cc:6731
#3  0x000000000066f273 in setup_natural_join_row_types (thd=0x7fffe0000b00, from_clause=0x7fffe0004ea8, context=0x7fffe0004d80) at /home/kevg/work/mariadb_10.2/sql/sql_base.cc:6854
#4  0x000000000066eff6 in setup_tables (thd=0x7fffe0000b00, context=0x7fffe0004d80, from_clause=0x7fffe0004ea8, tables=0x7fffe0012d68, leaves=List<TABLE_LIST> with 3 elements, select_insert=false, 
    full_table_list=false) at /home/kevg/work/mariadb_10.2/sql/sql_base.cc:7263
#5  0x000000000066f447 in setup_tables_and_check_access (thd=0x7fffe0000b00, context=0x7fffe0004d80, from_clause=0x7fffe0004ea8, tables=0x7fffe0012d68, leaves=List<TABLE_LIST> with 3 elements, 
    select_insert=false, want_access_first=1, want_access=1, full_table_list=false) at /home/kevg/work/mariadb_10.2/sql/sql_base.cc:7306
#6  0x00000000007385ab in JOIN::prepare (this=0x7fffe0014fb0, tables_init=0x7fffe0012d68, wild_num=1, conds_init=0x0, og_num=0, order_init=0x0, skip_order_by=false, group_init=0x0, having_init=0x0, 
    proc_param_init=0x0, select_lex_arg=0x7fffe0004d30, unit_arg=0x7fffe00045e0) at /home/kevg/work/mariadb_10.2/sql/sql_select.cc:1048
#7  0x0000000000734ff9 in mysql_select (thd=0x7fffe0000b00, tables=0x7fffe0012d68, wild_num=1, fields=List<Item> with 1 elements, conds=0x0, og_num=0, order=0x0, group=0x0, having=0x0, proc_param=0x0, 
    select_options=2147748608, result=0x7fffe0014f90, unit=0x7fffe00045e0, select_lex=0x7fffe0004d30) at /home/kevg/work/mariadb_10.2/sql/sql_select.cc:3891
#8  0x000000000073499c in handle_select (thd=0x7fffe0000b00, lex=0x7fffe0004518, result=0x7fffe0014f90, setup_tables_done_option=0) at /home/kevg/work/mariadb_10.2/sql/sql_select.cc:363
#9  0x00000000006f7f73 in execute_sqlcom_select (thd=0x7fffe0000b00, all_tables=0x7fffe0012d68) at /home/kevg/work/mariadb_10.2/sql/sql_parse.cc:6403
#10 0x00000000006ead50 in mysql_execute_command (thd=0x7fffe0000b00) at /home/kevg/work/mariadb_10.2/sql/sql_parse.cc:3426
#11 0x00000000006e6bea in mysql_parse (thd=0x7fffe0000b00, rawbuf=0x7fffe0012468 "select * from (t1 as t2 left join t1 as t3 using (a)) natural left join t1", length=74, parser_state=0x7ffff09ca168, 
    is_com_multi=false, is_next_command=false) at /home/kevg/work/mariadb_10.2/sql/sql_parse.cc:7846
```
