### ISSUE TITLE
JOIN USING with versioning tables problem

### ISSUE THREAD

**Issue by kevgs** [tempesta-tech/mariadb#147]
```sql
create table t1 (a int) with system versioning;
create table t2 (a int) with system versioning;
create view v1 as select * from t2 inner join t1 using (a);
```

```
mysqltest: At line 5: query 'create view v1 as select * from t2 inner join t1 using (a)' failed: 1052: Column 'sys_trx_start' in field list is ambiguous
```

Found in `main.select` using forced versioning feature.

**Comment by kevgs** [comment]
```c++
#0  my_error (nr=1052, MyFlags=0) at /home/kevg/work/mariadb_10.2/mysys/my_error.c:113
#1  0x000000000066b14e in find_field_in_natural_join (thd=0x7fffe0000b00, table_ref=0x7fffe0013a08, name=0x7fffe002c4cb "sys_trx_start", length=13, ref=0x7fffe0014408, register_tree_change=true, 
    actual_table=0x7ffff09c4650) at /home/kevg/work/mariadb_10.2/sql/sql_base.cc:5287
#2  0x000000000066a68d in find_field_in_table_ref (thd=0x7fffe0000b00, table_list=0x7fffe0013a08, name=0x7fffe002c4cb "sys_trx_start", length=13, item_name=0x7fffe002c4cb "sys_trx_start", db_name=0x0, 
    table_name=0x0, ref=0x7fffe0014408, check_privileges=true, allow_rowid=true, cached_field_index_ptr=0x7fffe00143cc, register_tree_change=true, actual_table=0x7ffff09c4650)
    at /home/kevg/work/mariadb_10.2/sql/sql_base.cc:5591
#3  0x000000000066becf in find_field_in_tables (thd=0x7fffe0000b00, item=0x7fffe0014308, first_table=0x7fffe0013a08, last_table=0x0, ref=0x7fffe0014408, report_error=IGNORE_EXCEPT_NON_UNIQUE, 
    check_privileges=true, register_tree_change=true) at /home/kevg/work/mariadb_10.2/sql/sql_base.cc:5847
#4  0x00000000009f5f31 in Item_field::fix_fields (this=0x7fffe0014308, thd=0x7fffe0000b00, reference=0x7fffe0014408) at /home/kevg/work/mariadb_10.2/sql/item.cc:5393
#5  0x000000000066e2ad in setup_fields (thd=0x7fffe0000b00, ref_pointer_array=..., fields=List<Item> with 3 elements, mark_used_columns=MARK_COLUMNS_READ, sum_func_list=0x7fffe0014888, allow_sum_func=true)
    at /home/kevg/work/mariadb_10.2/sql/sql_base.cc:7036
#6  0x0000000000738b24 in JOIN::prepare (this=0x7fffe0014578, tables_init=0x7fffe0012d00, wild_num=1, conds_init=0x0, og_num=0, order_init=0x0, skip_order_by=false, group_init=0x0, having_init=0x0, 
    proc_param_init=0x0, select_lex_arg=0x7fffe0004d30, unit_arg=0x7fffe00045e0) at /home/kevg/work/mariadb_10.2/sql/sql_select.cc:1130
#7  0x00000000007f97a2 in st_select_lex_unit::prepare (this=0x7fffe00045e0, thd_arg=0x7fffe0000b00, sel_result=0x0, additional_options=0) at /home/kevg/work/mariadb_10.2/sql/sql_union.cc:552
#8  0x000000000080adf3 in mysql_create_view (thd=0x7fffe0000b00, views=0x7fffe0012590, mode=VIEW_CREATE_NEW) at /home/kevg/work/mariadb_10.2/sql/sql_view.cc:552
#9  0x00000000006f50df in mysql_execute_command (thd=0x7fffe0000b00) at /home/kevg/work/mariadb_10.2/sql/sql_parse.cc:5995
#10 0x00000000006e6c2a in mysql_parse (thd=0x7fffe0000b00, rawbuf=0x7fffe0012468 "create view v1 as select * from t2 inner join t1 using (a)", length=58, parser_state=0x7ffff09ca168, is_com_multi=false, 
    is_next_command=false) at /home/kevg/work/mariadb_10.2/sql/sql_parse.cc:7849
```
