### ISSUE TITLE
CREATE AS SELECT * FROM VTMD fails

### ISSUE THREAD

**Issue by kevgs** [tempesta-tech/mariadb#206]
```sql
set versioning_ddl_survival=on;

create table t (a int) with system versioning engine innodb;
create table tmp as select * from t;

drop table tmp;
create table tmp as select * from t_vtmd;

query 'create table tmp as select * from t_vtmd' failed: 4071: `start` must be of type `TIMESTAMP(6)` for versioned table `tmp`
```

```c++
#0  my_message_sql (error=4071, str=0x7ffff0360470 "`start` must be of type `TIMESTAMP(6)` for versioned table `tmp`", MyFlags=0) at mysqld.cc:3589
#1  0x0000000001782ce3 in my_error (nr=4071, MyFlags=0) at my_error.c:125
#2  0x0000000000a7a249 in Vers_parse_info::check_generated_type (this=0x7ffff0365f88, table_name=0x7fff88012800 "tmp", alter_info=0x7ffff0365d98, integer_fields=false) at handler.cc:7018
#3  0x0000000000a79f0c in Vers_parse_info::check_and_fix_implicit (this=0x7ffff0365f88, thd=0x7fff88000b00, alter_info=0x7ffff0365d98, create_info=0x7ffff0365e40, table_name=0x7fff88012800 "tmp")
    at handler.cc:6811
#4  0x0000000000d8782c in create_table_from_items (thd=0x7fff88000b00, create_info=0x7ffff0365e40, create_table=0x7fff88012838, alter_info=0x7ffff0365d98, items=0x7fff88004f70, lock=0x7ffff0361cd8, 
    hooks=0x7ffff0361c80) at sql_insert.cc:4167
#5  0x0000000000d86ddb in select_create::prepare (this=0x7fff880137d8, values=List<Item> with 5 elements, u=0x7fff880046e0) at sql_insert.cc:4379
#6  0x0000000000e270d2 in JOIN::prepare (this=0x7fff880138d0, tables_init=0x7fff88012fb0, wild_num=1, conds_init=0x0, og_num=0, order_init=0x0, skip_order_by=false, group_init=0x0, having_init=0x0, 
    proc_param_init=0x0, select_lex_arg=0x7fff88004e40, unit_arg=0x7fff880046e0) at sql_select.cc:1370
#7  0x0000000000e21d19 in mysql_select (thd=0x7fff88000b00, tables=0x7fff88012fb0, wild_num=1, fields=List<Item> with 5 elements, conds=0x0, og_num=0, order=0x0, group=0x0, having=0x0, proc_param=0x0, 
    select_options=2416184064, result=0x7fff880137d8, unit=0x7fff880046e0, select_lex=0x7fff88004e40) at sql_select.cc:3993
#8  0x0000000000e21693 in handle_select (thd=0x7fff88000b00, lex=0x7fff88004618, result=0x7fff880137d8, setup_tables_done_option=0) at sql_select.cc:363
#9  0x0000000000dbd990 in mysql_execute_command (thd=0x7fff88000b00) at sql_parse.cc:4044
#10 0x0000000000db823a in mysql_parse (thd=0x7fff88000b00, rawbuf=0x7fff88012738 "create table tmp as select * from t_vtmd", length=40, parser_state=0x7ffff0367538, is_com_multi=false, is_next_command=false)
    at sql_parse.cc:7902
```

**Comment by kevgs** [comment]
```c++
(gdb) f
#3  0x0000000000a79f0c in Vers_parse_info::check_and_fix_implicit (this=0x7ffff0365f88, thd=0x7fff88000b00, alter_info=0x7ffff0365d98, create_info=0x7ffff0365e40, table_name=0x7fff88012800 "tmp")
    at handler.cc:6811
6811	         check_generated_type(table_name, alter_info, integer_fields);
(gdb) p create_info->db_type->db_type
$5 = DB_TYPE_MYISAM
```

**Comment by kevgs** [comment]
```c++
#0  Table_scope_and_contents_source_st::use_default_db_type (this=0x7ffff0365e40, thd=0x7fff88000b00) at handler.h:1838
#1  0x0000000000dbd293 in mysql_execute_command (thd=0x7fff88000b00) at sql_parse.cc:3877
#2  0x0000000000db823a in mysql_parse (thd=0x7fff88000b00, rawbuf=0x7fff88012738 "create table tmp as select * from t_vtmd", length=40, parser_state=0x7ffff0367538, is_com_multi=false, is_next_command=false)
    at sql_parse.cc:7902
#3  0x0000000000db3260 in dispatch_command (command=COM_QUERY, thd=0x7fff88000b00, packet=0x7fff88008af1 "create table tmp as select * from t_vtmd", packet_length=40, is_com_multi=false, is_next_command=false)
    at sql_parse.cc:1813
#4  0x0000000000db69db in do_command (thd=0x7fff88000b00) at sql_parse.cc:1376
#5  0x0000000000f84871 in do_handle_one_connection (connect=0x2b2eb60) at sql_connect.cc:1354
#6  0x0000000000f8464a in handle_one_connection (arg=0x2b2eb60) at sql_connect.cc:1260
#7  0x00000000016ff494 in pfs_spawn_thread (arg=0x2a78e60) at pfs.cc:1862
#8  0x00007ffff7bc06da in start_thread (arg=0x7ffff0369700) at pthread_create.c:456
#9  0x00007ffff6787d7f in clone () at clone.S:105
(gdb) p db_type->db_type
$4 = DB_TYPE_MYISAM
```
