### ISSUE TITLE
Historical records became alive on copy

### ISSUE THREAD

**Issue by kevgs** [tempesta-tech/mariadb#212]
```sql
create or replace table t(a int) engine innodb;
insert into t values(1);
alter table t with system versioning, algorithm=copy;
update t set a=2;
select * from t for system_time all;
a	sys_trx_start	sys_trx_end
2	1303	18446744073709551615
1	1288	1303
alter table t add column b int, algorithm=copy;
select * from t for system_time all;
a	sys_trx_start	sys_trx_end	b
2	1308	18446744073709551615	NULL
1	1308	18446744073709551615	NULL
```

**Comment by midenok** [comment]
Provide more clear and short title. 'Changes versioned fields' tells nothing like seems to be the bug.

**Comment by kevgs** [comment]
```c++
#0  row_insert_for_mysql (mysql_rec=0x7fff8802cf48 "\361\001", prebuilt=0x7fff88030f48, ins_mode=ROW_INS_VERSIONED) at row0mysql.cc:1416
#1  0x0000000001139ab7 in ha_innobase::write_row (this=0x7fff8802c748, record=0x7fff8802cf48 "\361\001") at ha_innodb.cc:8727
#2  0x0000000000a77978 in handler::ha_write_row (this=0x7fff8802c748, buf=0x7fff8802cf48 "\361\001") at handler.cc:6012
#3  0x0000000000edba62 in copy_data_between_tables (thd=0x7fff88000b00, from=0x7fff88027ec0, to=0x7fff8802bb30, create=List<Create_field> with 3 elements, ignore=false, order_num=0, order=0x0, 
    copied=0x7ffff03607b0, deleted=0x7ffff03607a8, keys_onoff=Alter_info::LEAVE_AS_IS, alter_ctx=0x7ffff0360b50) at sql_table.cc:10055
#4  0x0000000000ed3836 in mysql_alter_table (thd=0x7fff88000b00, new_db=0x7fff88012ea0 "test", new_name=0x0, create_info=0x7ffff0362298, table_list=0x7fff88012870, alter_info=0x7ffff03621f0, order_num=0, 
    order=0x0, ignore=false) at sql_table.cc:9474
#5  0x0000000000f8b1e6 in Sql_cmd_alter_table::execute (this=0x7fff88012eb0, thd=0x7fff88000b00) at sql_alter.cc:318
#6  0x0000000000dc719b in mysql_execute_command (thd=0x7fff88000b00) at sql_parse.cc:6224
#7  0x0000000000db876a in mysql_parse (thd=0x7fff88000b00, rawbuf=0x7fff88012758 "alter table t with system versioning, algorithm=copy", length=52, parser_state=0x7ffff0367538, is_com_multi=false, 
    is_next_command=false) at sql_parse.cc:7902
```
ins_mode=ROW_INS_VERSIONED
