### ISSUE TITLE
Revisit vers_conditions logic + parser fixes

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#237]
- [x] possibly remove `st_select_lex::vers_conditions`, use only `TABLE_LIST::vers_conditions`;
- [x] revisit derived vers_conditions propagation;
- [x] `sql_yacc.yy` XXX review fixes.

**Comment by midenok** [comment]
```c++
        // Propagate query conditions from nearest outer SELECT_LEX:
        while (outer_slex && (!outer_slex->vers_conditions || outer_slex->vers_conditions.from_inner))
          outer_slex= outer_slex->next_select_in_list();
```
`from_inner` means that we already got `vers_conditions` from inner query and don't need it back, so we skip it. Thus we find nearest `outer_slex` with vers_conditions that were set by user (not imported).

**Comment by midenok** [comment]
#### `main.derived` fails:
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:58
#1  0x00007ffff64b437a in __GI_abort () at abort.c:89
#2  0x00007ffff64aab47 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0x5555566c5880 "(st_select_lex*)join->select_lex == this", file=file@entry=0x5555566c5600 "/home/midenok/src/mariadb/midenok/src/sql/sql_union.cc", line=line@entry=1707, function=function@entry=0x5555566c5d00 <st_select_lex::cleanup()::__PRETTY_FUNCTION__> "bool st_select_lex::cleanup()") at assert.c:92
#3  0x00007ffff64aabf2 in __GI___assert_fail (assertion=0x5555566c5880 "(st_select_lex*)join->select_lex == this", file=0x5555566c5600 "/home/midenok/src/mariadb/midenok/src/sql/sql_union.cc", line=1707, function=0x5555566c5d00 <st_select_lex::cleanup()::__PRETTY_FUNCTION__> "bool st_select_lex::cleanup()") at assert.c:101
#4  0x0000555555c473ca in st_select_lex::cleanup (this=0x7fffe00d59b0) at /home/midenok/src/mariadb/midenok/src/sql/sql_union.cc:1707
#5  0x0000555555eca982 in subselect_single_select_engine::prepare (this=0x7fffe00bd690, thd=0x7fffe0000b00) at /home/midenok/src/mariadb/midenok/src/sql/item_subselect.cc:3605
#6  0x0000555555ebf1e4 in Item_subselect::fix_fields (this=0x7fffe00bec18, thd_param=0x7fffe0000b00, ref=0x7fffe00da420) at /home/midenok/src/mariadb/midenok/src/sql/item_subselect.cc:268
#7  0x0000555555ec9b37 in Item_in_subselect::fix_fields (this=0x7fffe00bec18, thd_arg=0x7fffe0000b00, ref=0x7fffe00da420) at /home/midenok/src/mariadb/midenok/src/sql/item_subselect.cc:3289
#8  0x0000555555ae8721 in setup_conds (thd=0x7fffe0000b00, tables=0x7fffe00bde88, leaves=..., conds=0x7fffe00da420) at /home/midenok/src/mariadb/midenok/src/sql/sql_base.cc:7909
#9  0x0000555555b96a44 in setup_without_group (thd=0x7fffe0000b00, ref_pointer_array=..., tables=0x7fffe00bde88, leaves=..., fields=..., all_fields=..., conds=0x7fffe00da420, order=0x0, group=0x0, win_specs=..., win_funcs=..., hidden_group_fields=0x7fffe00da2ff, reserved=0x7fffe00bc2bc) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:639
#10 0x0000555555b992dc in JOIN::prepare (this=0x7fffe00da020, tables_init=0x7fffe00bde88, wild_num=0, conds_init=0x7fffe00bf5d8, og_num=0, order_init=0x0, skip_order_by=false, group_init=0x0, having_init=0x0, proc_param_init=0x0, select_lex_arg=0x7fffe00bc020, unit_arg=0x7fffe00bb8c0) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:1167
#11 0x0000555555ba3a97 in mysql_select (thd=0x7fffe0000b00, tables=0x7fffe00bde88, wild_num=0, fields=..., conds=0x7fffe00bf5d8, og_num=0, order=0x0, group=0x0, having=0x0, proc_param=0x0, select_options=3489926912, result=0x7fffe00d9f78, unit=0x7fffe00bb8c0, select_lex=0x7fffe00bc020) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:4049
#12 0x0000555555b95fa8 in handle_select (thd=0x7fffe0000b00, lex=0x7fffe00bb7f8, result=0x7fffe00d9f78, setup_tables_done_option=1073741824) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:363
#13 0x0000555555b5b9f7 in mysql_execute_command (thd=0x7fffe0000b00) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:4644
#14 0x0000555555f7de14 in sp_instr_stmt::exec_core (this=0x7fffe00bd6d0, thd=0x7fffe0000b00, nextp=0x7ffff07563d4) at /home/midenok/src/mariadb/midenok/src/sql/sp_head.cc:3344
#15 0x0000555555f7d3a7 in sp_lex_keeper::reset_lex_and_exec_core (this=0x7fffe00bd718, thd=0x7fffe0000b00, nextp=0x7ffff07563d4, open_tables=false, instr=0x7fffe00bd6d0) at /home/midenok/src/mariadb/midenok/src/sql/sp_head.cc:3088
#16 0x0000555555f7daab in sp_instr_stmt::execute (this=0x7fffe00bd6d0, thd=0x7fffe0000b00, nextp=0x7ffff07563d4) at /home/midenok/src/mariadb/midenok/src/sql/sp_head.cc:3260
#17 0x0000555555f77ea7 in sp_head::execute (this=0x7fffe00d3db8, thd=0x7fffe0000b00, merge_da_on_success=true) at /home/midenok/src/mariadb/midenok/src/sql/sp_head.cc:1233
#18 0x0000555555f7a105 in sp_head::execute_procedure (this=0x7fffe00d3db8, thd=0x7fffe0000b00, args=0x7fffe0005428) at /home/midenok/src/mariadb/midenok/src/sql/sp_head.cc:2059
#19 0x0000555555b57348 in do_execute_sp (thd=0x7fffe0000b00, sp=0x7fffe00d3db8) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:2882
#20 0x0000555555b5ef71 in mysql_execute_command (thd=0x7fffe0000b00) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:5810
#21 0x0000555555b645c4 in mysql_parse (thd=0x7fffe0000b00, rawbuf=0x7fffe0012538 "call p1()", length=9, parser_state=0x7ffff0757660, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:7902
```
```
1707        DBUG_ASSERT((st_select_lex*)join->select_lex == this);
```
```
(gdb) p this
$1 = (st_select_lex * const) 0x7fffe00a44e0
(gdb) p join->select_lex
$2 = (SELECT_LEX *) 0xa5a5a5a5a5a5a5a5
```

**Comment by midenok** [comment]
```
(gdb) p this->join
$1 = (JOIN *) 0x7fffe00da868
```
```
#0  JOIN::JOIN (this=0x7fffe00da868, thd_arg=0x7fffe0000b00, fields_arg=..., select_options_arg=268435456, result_arg=0x7fffe00bd5e8) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.h:1406
#1  0x0000555555eca9d2 in subselect_single_select_engine::prepare (this=0x7fffe00bd610, thd=0x7fffe0000b00) at /home/midenok/src/mariadb/midenok/src/sql/item_subselect.cc:3608
#2  0x0000555555ebf1e4 in Item_subselect::fix_fields (this=0x7fffe00beb98, thd_param=0x7fffe0000b00, ref=0x7fffe00da718) at /home/midenok/src/mariadb/midenok/src/sql/item_subselect.cc:268
#3  0x0000555555ec9b37 in Item_in_subselect::fix_fields (this=0x7fffe00beb98, thd_arg=0x7fffe0000b00, ref=0x7fffe00da718) at /home/midenok/src/mariadb/midenok/src/sql/item_subselect.cc:3289
#4  0x0000555555ae8721 in setup_conds (thd=0x7fffe0000b00, tables=0x7fffe00bde08, leaves=..., conds=0x7fffe00da718) at /home/midenok/src/mariadb/midenok/src/sql/sql_base.cc:7909
#5  0x0000555555b96a44 in setup_without_group (thd=0x7fffe0000b00, ref_pointer_array=..., tables=0x7fffe00bde08, leaves=..., fields=..., all_fields=..., conds=0x7fffe00da718, order=0x0, group=0x0, win_specs=..., win_funcs=..., hidden_group_fields=0x7fffe00da5f7, reserved=0x7fffe00bc23c) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:639
#6  0x0000555555b992dc in JOIN::prepare (this=0x7fffe00da318, tables_init=0x7fffe00bde08, wild_num=1, conds_init=0x7fffe00beb98, og_num=0, order_init=0x0, skip_order_by=false, group_init=0x0, having_init=0x0, proc_param_init=0x0, select_lex_arg=0x7fffe00bbfa0, unit_arg=0x7fffe00bb840) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:1167
#7  0x0000555555ba3a97 in mysql_select (thd=0x7fffe0000b00, tables=0x7fffe00bde08, wild_num=1, fields=..., conds=0x7fffe00beb98, og_num=0, order=0x0, group=0x0, having=0x0, proc_param=0x0, select_options=3489926912, result=0x7fffe00da270, unit=0x7fffe00bb840, select_lex=0x7fffe00bbfa0) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:4049
#8  0x0000555555b95fa8 in handle_select (thd=0x7fffe0000b00, lex=0x7fffe00bb778, result=0x7fffe00da270, setup_tables_done_option=1073741824) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:363
#9  0x0000555555b5b9f7 in mysql_execute_command (thd=0x7fffe0000b00) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:4644
#10 0x0000555555f7de14 in sp_instr_stmt::exec_core (this=0x7fffe00bd650, thd=0x7fffe0000b00, nextp=0x7ffff07563d4) at /home/midenok/src/mariadb/midenok/src/sql/sp_head.cc:3344
#11 0x0000555555f7d3a7 in sp_lex_keeper::reset_lex_and_exec_core (this=0x7fffe00bd698, thd=0x7fffe0000b00, nextp=0x7ffff07563d4, open_tables=false, instr=0x7fffe00bd650) at /home/midenok/src/mariadb/midenok/src/sql/sp_head.cc:3088
#12 0x0000555555f7daab in sp_instr_stmt::execute (this=0x7fffe00bd650, thd=0x7fffe0000b00, nextp=0x7ffff07563d4) at /home/midenok/src/mariadb/midenok/src/sql/sp_head.cc:3260
#13 0x0000555555f77ea7 in sp_head::execute (this=0x7fffe00d40d8, thd=0x7fffe0000b00, merge_da_on_success=true) at /home/midenok/src/mariadb/midenok/src/sql/sp_head.cc:1233
#14 0x0000555555f7a105 in sp_head::execute_procedure (this=0x7fffe00d40d8, thd=0x7fffe0000b00, args=0x7fffe0005428) at /home/midenok/src/mariadb/midenok/src/sql/sp_head.cc:2059
#15 0x0000555555b57348 in do_execute_sp (thd=0x7fffe0000b00, sp=0x7fffe00d40d8) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:2882
#16 0x0000555555b5ef71 in mysql_execute_command (thd=0x7fffe0000b00) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:5810
#17 0x0000555555b645c4 in mysql_parse (thd=0x7fffe0000b00, rawbuf=0x7fffe0012538 "call p1()", length=9, parser_state=0x7ffff0757660, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:7902
```
