### ISSUE TITLE
Partitioning fixes

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#242]
Fix [review comments](https://github.com/MariaDB/server/commit/7e3093670f32dc156a615c3dda2244f53423cd57) related to partitioning.

Depends on #244 

- [x] comment 1
- [x] comment 2
```diff
--- a/sql/ha_partition.cc
+++ b/sql/ha_partition.cc
@@ -2029,6 +2029,7 @@ int ha_partition::copy_partitions(ulonglong * const copied,
         /* Copy record to new handler */
         (*copied)++;
         if (new_file->ha_external_lock(thd, F_UNLCK) || new_file->ha_external_lock(thd, F_WRLCK))
+        // XXX this looks very fishy. Why are you doing it?
           goto error;
         tmp_disable_binlog(thd); /* Do not replicate the low-level changes. */
         result= new_file->ha_write_row(m_rec0);
```
```diff
--- a/sql/ha_partition.cc
+++ b/sql/ha_partition.cc
@@ -2035,6 +2035,7 @@ int ha_partition::copy_partitions(ulonglong * const copied,
         result= new_file->ha_write_row(m_rec0);
         reenable_binlog(thd);
         if (new_file->ha_external_lock(thd, F_UNLCK) || new_file->ha_external_lock(thd, F_RDLCK) || result)
+        // XXX and here
           goto error;
       }
     }
```

- [x] comment 3
```diff
--- a/sql/ha_partition.h
+++ b/sql/ha_partition.h
@@ -1280,6 +1280,15 @@ class ha_partition :public handler
   virtual bool versioned() const
   {
     return m_innodb;
+    // XXX no, no, no. No engine-specific checks please (I didn't actually
+    // know partitioning does that wtf).
+    // do it like
+    //
+    //   return partition_ht()->flags & HTON_SUPPORTS_SYS_VERSIONING;
+    //
+    // and change the name from "versioned" to something that implies
+    // that the engine supports versioning internally. MyISAM tables can be
+    // versioned too, so "versioned" doesn't equal to "supports sys versioning"
   }
 
   virtual ha_rows part_recs_slow(void *_part_elem)
```

- [x] comment 4
```diff
--- a/sql/partition_element.h
+++ b/sql/partition_element.h
@@ -180,6 +189,10 @@ class partition_element :public Sql_alloc
   };
 
   elem_type type;
+  // XXX I don't think this is needed. 'max_value' flag means
+  // MAXVALUE for RANGE partitioning, DEFAULT for LIST partitioning.
+  // I don't see why it cannot mean AS_OF_NOW for SYSTEM_TIME partitioning.
+  // (in a sense AS_OF_NOW *is* max_value of the second timestamp column)
 
   partition_element()
   : part_max_rows(0), part_min_rows(0), range_value(0),
```

- [x] comment 5
- [x] comment 6
```diff
--- a/sql/partition_element.h
+++ b/sql/partition_element.h
@@ -215,8 +228,12 @@ class partition_element :public Sql_alloc
   part_column_list_val& get_col_val(uint idx)
   {
     DBUG_ASSERT(type != CONVENTIONAL);
+    // XXX I don't see why it should be type != CONVENTIONAL.
+    // The method is fairly generic
     DBUG_ASSERT(list_val_list.elements == 1);
     part_elem_value *ev= static_cast<part_elem_value*>(list_val_list.first_node()->info);
+    // XXX That's not how one uses List.
+    // Better: ev= list_val_list->head();
     DBUG_ASSERT(ev);
     DBUG_ASSERT(ev->col_val_array);
     return ev->col_val_array[idx];
```

- [x] comment 7
- [x] comment 8
```diff
--- a/sql/partition_info.cc
+++ b/sql/partition_info.cc
@@ -889,11 +889,15 @@ partition_info::vers_part_rotate(THD * thd)
 
 bool partition_info::vers_setup_1(THD * thd, uint32 added)
 {
+  // XXX generally, the more cryptic function name is, the longer and more
+  // detailed function comment must be. "vers_setup_1" is very cryptic :)
   DBUG_ASSERT(part_type == VERSIONING_PARTITION);
 
   if (!table->versioned())
   {
     my_error(ER_VERSIONING_REQUIRED, MYF(0), "`BY SYSTEM_TIME` partitioning");
+    // XXX backticks are only used to quote identifiers, don't use them
+    // like this.
     return true;
   }
 ```

- [x] comment 9
```diff
--- a/sql/partition_info.cc
+++ b/sql/partition_info.cc
@@ -910,6 +914,7 @@ bool partition_info::vers_setup_1(THD * thd, uint32 added)
     Field *sys_trx_end= table->vers_end_field();
     part_field_list.empty();
     part_field_list.push_back(const_cast<char *>(sys_trx_end->field_name), thd->mem_root);
+    // XXX what was the content of part_field_list before you repopulated it?
     DBUG_ASSERT(part_field_list.elements == num_columns);
     // needed in handle_list_of_fields()
     sys_trx_end->flags|= GET_FIXED_FIELDS_FLAG;
```

- [x] comment 10
```diff
--- a/sql/partition_info.cc
+++ b/sql/partition_info.cc
@@ -1361,6 +1366,12 @@ bool partition_info::check_engine_mix(handlerton *engine_type,
 */
 
 bool partition_info::check_range_constants(THD *thd, bool init)
+  // XXX what are you trying to do by introducing this 'init' argument?
+  // This function "allocates an array..." and "also check that the
+  // range constants are defined in increasing order".
+  // One could expect init=false to mean that the caller is only
+  // interestd in "check" part, not in "allocate" part. But in the only place
+  // where init=false, you ignore the return value. So, what's the point?
 {
   partition_element* part_def;
   bool first= TRUE;
```

**Comment by midenok** [comment]
```c++
      Field *sys_trx_end= table->vers_end_field();
      part_field_list.empty();
      part_field_list.push_back(const_cast<char *>(sys_trx_end->field_name), thd->mem_root);
      // XXX what was the content of part_field_list before you repopulated it?
```
### 1. `part_field_list` constructed
```c++
Thread 28 "mysqld" hit Hardware watchpoint 2: -location part_field_list.elements                                                                                            
                                                                                                                                                                            
Old value = 2779096485                                                                                                                                                      
New value = 0                                                                                                                                                               
0x0000555555a7c595 in base_list::empty (this=0x7fff9c0133f0) at /home/midenok/src/mariadb/midenok/src/sql/sql_list.h:180                                                    
180   inline void empty() { elements=0; first= &end_of_list; last=&first;}                                                                                                  
#0  0x0000555555a7c595 in base_list::empty (this=0x7fff9c0133f0) at /home/midenok/src/mariadb/midenok/src/sql/sql_list.h:180                                                
#1  0x0000555555a7c5d6 in base_list::base_list (this=0x7fff9c0133f0) at /home/midenok/src/mariadb/midenok/src/sql/sql_list.h:181                                            
#2  0x0000555555b52966 in List<char>::List (this=0x7fff9c0133f0) at /home/midenok/src/mariadb/midenok/src/sql/sql_list.h:519                                                
#3  0x0000555555c39cd0 in partition_info::partition_info (this=0x7fff9c0133b8) at /home/midenok/src/mariadb/midenok/src/sql/partition_info.h:320                            
#4  0x0000555555c8c99f in partition_info::get_clone (this=0x7fff9c012e38, thd=0x7fff9c000b00) at /home/midenok/src/mariadb/midenok/src/sql/partition_info.cc:47             
#5  0x0000555555b5dcdd in mysql_execute_command (thd=0x7fff9c000b00) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:3910                                         
#6  0x0000555555b6861a in mysql_parse (thd=0x7fff9c000b00, rawbuf=0x7fff9c012558 "create or replace table t1 (x int)\nwith system versioning\npartition by system_time (\npa
rtition p0 versioning,\npartition pn as of now)", length=133, parser_state=0x7ffff0872660, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/midenok/s
rc/sql/sql_parse.cc:7902
```
```c++
Thread 28 "mysqld" hit Hardware watchpoint 3: -location part_field_list.first                                                                                               
                                                                                                                                                                            
Old value = (list_node *) 0xa5a5a5a5a5a5a5a5                                                                                                                                
New value = (list_node *) 0x55555722f3a0 <end_of_list>                                                                                                                      
0x0000555555a7c5a3 in base_list::empty (this=0x7fff9c0133f0) at /home/midenok/src/mariadb/midenok/src/sql/sql_list.h:180                                                    
180   inline void empty() { elements=0; first= &end_of_list; last=&first;}                                                                                                  
#0  0x0000555555a7c5a3 in base_list::empty (this=0x7fff9c0133f0) at /home/midenok/src/mariadb/midenok/src/sql/sql_list.h:180                                                
#1  0x0000555555a7c5d6 in base_list::base_list (this=0x7fff9c0133f0) at /home/midenok/src/mariadb/midenok/src/sql/sql_list.h:181                                            
#2  0x0000555555b52966 in List<char>::List (this=0x7fff9c0133f0) at /home/midenok/src/mariadb/midenok/src/sql/sql_list.h:519                                                
#3  0x0000555555c39cd0 in partition_info::partition_info (this=0x7fff9c0133b8) at /home/midenok/src/mariadb/midenok/src/sql/partition_info.h:320                            
#4  0x0000555555c8c99f in partition_info::get_clone (this=0x7fff9c012e38, thd=0x7fff9c000b00) at /home/midenok/src/mariadb/midenok/src/sql/partition_info.cc:47             
#5  0x0000555555b5dcdd in mysql_execute_command (thd=0x7fff9c000b00) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:3910                                         
#6  0x0000555555b6861a in mysql_parse (thd=0x7fff9c000b00, rawbuf=0x7fff9c012558 "create or replace table t1 (x int)\nwith system versioning\npartition by system_time (\npa
rtition p0 versioning,\npartition pn as of now)", length=133, parser_state=0x7ffff0872660, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/midenok/s
rc/sql/sql_parse.cc:7902
```
#### Frame 3
```
(gdb) p part_field_list
$2 = {
  <base_list> = {
    <Sql_alloc> = {<No data fields>}, 
    members of base_list: 
    first = 0x55555722f3a0 <end_of_list>, 
    last = 0x7fff9c0133f0, 
    elements = 0
  }, <No data fields>}
(gdb) p &part_field_list
$1 = (List<char> *) 0x7fff9c0133f0
(gdb) p &part_field_list.last
$2 = (list_node ***) 0x7fff9c0133f8
```
### 2. `part_field_list.last` changed
```
Thread 28 "mysqld" hit Hardware watchpoint 3: -location part_field_list.last

Old value = (list_node **) 0x7fff9c0133f0
New value = (list_node **) 0x7fff9c012e70
__memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:459
459     ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S: No such file or directory.
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:459
#1  0x0000555555c8c9f6 in partition_info::get_clone (this=0x7fff9c012e38, thd=0x7fff9c000b00) at /home/midenok/src/mariadb/midenok/src/sql/partition_info.cc:53
#2  0x0000555555b5dcdd in mysql_execute_command (thd=0x7fff9c000b00) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:3910
#3  0x0000555555b6861a in mysql_parse (thd=0x7fff9c000b00, rawbuf=0x7fff9c012558 "create or replace table t1 (x int)\nwith system versioning\npartition by system_time (\npartition p0 versioning,\npartition pn as of now)", length=133, parser_state=0x7ffff0872660, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:7902
```
```
   0x7ffff65cda0c <__memmove_avx_unaligned_erms+668>:   vmovdqu YMMWORD PTR [rdi],ymm4
   0x7ffff65cda10 <__memmove_avx_unaligned_erms+672>:   vmovdqu YMMWORD PTR [rdi+0x20],ymm5
   0x7ffff65cda15 <__memmove_avx_unaligned_erms+677>:   vmovdqu YMMWORD PTR [rdi+0x40],ymm6
=> 0x7ffff65cda1a <__memmove_avx_unaligned_erms+682>:   vmovdqu YMMWORD PTR [rdi+0x60],ymm7
```
```
(gdb) p/x $rdi+0x40
$4 = 0x7fff9c0133f8
```
#### Frame 1:
```
(gdb) f 1
#1  0x0000555555c8c9f6 in partition_info::get_clone (this=0x7fff9c012e38, thd=0x7fff9c000b00) at /home/midenok/src/mariadb/midenok/src/sql/partition_info.cc:53
53        memcpy(clone, this, sizeof(partition_info));
(gdb) p clone
$8 = (partition_info *) 0x7fff9c0133b8
(gdb) p &clone->part_field_list
$10 = (List<char> *) 0x7fff9c0133f0
(gdb) p &clone->part_field_list.last
$11 = (list_node ***) 0x7fff9c0133f8
(gdb) p &this.part_field_list.last
$9 = (list_node ***) 0x7fff9c012e78
(gdb) p &this.part_field_list
$10 = (List<char> *) 0x7fff9c012e70
(gdb) p this
$12 = (partition_info * const) 0x7fff9c012e38
```
### 3. `part_field_list.empty()` called
#### Before
```
$2 = {
  <base_list> = {
    <Sql_alloc> = {<No data fields>}, 
    members of base_list: 
    first = 0x55555722f3a0 <end_of_list>, 
    last = 0x7fff9c012e70, 
    elements = 0
  }, <No data fields>}
```
#### After (`last` recovered)
```
$3 = {
  <base_list> = {
    <Sql_alloc> = {<No data fields>}, 
    members of base_list: 
    first = 0x55555722f3a0 <end_of_list>, 
    last = 0x7fff9c0133f0, 
    elements = 0
  }, <No data fields>}
```
### 4. elements increased
```c++
Thread 28 "mysqld" hit Hardware watchpoint 2: -location part_field_list.elements

Old value = 0
New value = 1
base_list::push_back (this=0x7fff9c0133f0, info=0x7fff9c061e79, mem_root=0x7fff9c005c98) at /home/midenok/src/mariadb/midenok/src/sql/sql_list.h:221
221           return 0;
#0  base_list::push_back (this=0x7fff9c0133f0, info=0x7fff9c061e79, mem_root=0x7fff9c005c98) at /home/midenok/src/mariadb/midenok/src/sql/sql_list.h:221
#1  0x0000555555c97655 in List<char>::push_back (this=0x7fff9c0133f0, a=0x7fff9c061e79 "sys_trx_end", mem_root=0x7fff9c005c98) at /home/midenok/src/mariadb/midenok/src/sql/sql_list.h:525
#2  0x0000555555c8f484 in partition_info::vers_setup_expression (this=0x7fff9c0133b8, thd=0x7fff9c000b00, alter_add=0) at /home/midenok/src/mariadb/midenok/src/sql/partition_info.cc:967
#3  0x0000555555fb5f6c in fix_partition_func (thd=0x7fff9c000b00, table=0x7ffff086f5a0, is_create_table_ind=true) at /home/midenok/src/mariadb/midenok/src/sql/sql_partition.cc:1692
#4  0x0000555555c66e7c in open_table_from_share (thd=0x7fff9c000b00, share=0x7ffff086ef40, alias=0x5555567dabbd "", db_stat=0, prgflag=1, ha_open_flags=0, outparam=0x7ffff086f5a0, is_create_table=true) at /home/midenok/src/mariadb/midenok/src/sql/table.cc:3306
#5  0x0000555555e09303 in ha_create_table (thd=0x7fff9c000b00, path=0x7ffff0871970 "./test/t1", db=0x7fff9c012d40 "test", table_name=0x7fff9c0126d8 "t1", create_info=0x7ffff0871f80, frm=0x7ffff0871960) at /home/midenok/src/mariadb/midenok/src/sql/handler.cc:4777
#6  0x0000555555c7fb8f in rea_create_table (thd=0x7fff9c000b00, frm=0x7ffff0871960, path=0x7ffff0871970 "./test/t1", db=0x7fff9c012d40 "test", table_name=0x7fff9c0126d8 "t1", create_info=0x7ffff0871f80, file=0x7fff9c013be0, no_ha_create_table=false) at /home/midenok/src/mariadb/midenok/src/sql/unireg.cc:510
#7  0x0000555555c2968e in create_table_impl (thd=0x7fff9c000b00, orig_db=0x7fff9c012d40 "test", orig_table_name=0x7fff9c0126d8 "t1", db=0x7fff9c012d40 "test", table_name=0x7fff9c0126d8 "t1", path=0x7ffff0871970 "./test/t1", options=..., create_info=0x7ffff0871f80, alter_info=0x7ffff0871ed0, create_table_mode=0, is_trans=0x7ffff0871bce, key_info=0x7ffff0871950, key_count=0x7ffff0871944, frm=0x7ffff0871960) at /home/midenok/src/mariadb/midenok/src/sql/sql_table.cc:4859
#8  0x0000555555c29c9d in mysql_create_table_no_lock (thd=0x7fff9c000b00, db=0x7fff9c012d40 "test", table_name=0x7fff9c0126d8 "t1", create_info=0x7ffff0871f80, alter_info=0x7ffff0871ed0, is_trans=0x7ffff0871bce, create_table_mode=0, table_list=0x7fff9c012710) at /home/midenok/src/mariadb/midenok/src/sql/sql_table.cc:4972
#9  0x0000555555c2a016 in mysql_create_table (thd=0x7fff9c000b00, create_table=0x7fff9c012710, create_info=0x7ffff0871f80, alter_info=0x7ffff0871ed0) at /home/midenok/src/mariadb/midenok/src/sql/sql_table.cc:5045
#10 0x0000555555b5e357 in mysql_execute_command (thd=0x7fff9c000b00) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:4084
#11 0x0000555555b6861a in mysql_parse (thd=0x7fff9c000b00, rawbuf=0x7fff9c012558 "create or replace table t1 (x int)\nwith system versioning\npartition by system_time (\npartition p0 versioning,\npartition pn as of now)", length=133, parser_state=0x7ffff0872660, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:7902
```

**Comment by midenok** [comment]
```
 bool partition_info::check_range_constants(THD *thd, bool init)
 +  // XXX what are you trying to do by introducing this 'init' argument?
 +  // This function "allocates an array..." and "also check that the
 +  // range constants are defined in increasing order".
 +  // One could expect init=false to mean that the caller is only
 +  // interestd in "check" part, not in "allocate" part. But in the only place
 +  // where init=false, you ignore the return value. So, what's the point?
  {
```
```
#0  partition_info::vers_update_range_constants (this=0x7fff9c06b748, thd=0x7fff9c000b00) at /home/midenok/src/mariadb/midenok/src/sql/partition_info.h:557
#1  0x0000555555f4e019 in prune_partitions (thd=0x7fff9c000b00, table=0x7fff9c07cd10, pprune_cond=0x7fff9c0ab828) at /home/midenok/src/mariadb/midenok/src/sql/opt_range.cc:3460
#2  0x0000555555b9fbb8 in JOIN::optimize_inner (this=0x7fff9c012778) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:1785
#3  0x0000555555b9e900 in JOIN::optimize (this=0x7fff9c012778) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:1466
#4  0x0000555555ba7ae7 in mysql_select (thd=0x7fff9c000b00, tables=0x7fff9c0aaec0, wild_num=0, fields=..., conds=0x7fff9c0ab828, og_num=0, order=0x0, group=0x0, having=0x0, proc_param=0x0, select_options=2416184064, result=0x7fff9c0ab508, unit=0x7fff9c0a94f8, select_lex=0x7fff9c0a9c58) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:4043
#5  0x0000555555b9a0fe in handle_select (thd=0x7fff9c000b00, lex=0x7fff9c0a9430, result=0x7fff9c0ab508, setup_tables_done_option=0) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:363
#6  0x0000555555b653d9 in execute_sqlcom_select (thd=0x7fff9c000b00, all_tables=0x7fff9c0aaec0) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:6455
#7  0x0000555555b5d0af in mysql_execute_command (thd=0x7fff9c000b00) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:3574
#8  0x0000555555b86388 in Prepared_statement::execute (this=0x7fff9c0a8fd0, expanded_query=0x7ffff0871c10, open_cursor=false) at /home/midenok/src/mariadb/midenok/src/sql/sql_prepare.cc:4641
#9  0x0000555555b84ab1 in Prepared_statement::execute_loop (this=0x7fff9c0a8fd0, expanded_query=0x7ffff0871c10, open_cursor=false, packet=0x0, packet_end=0x0) at /home/midenok/src/mariadb/midenok/src/sql/sql_prepare.cc:4075
#10 0x0000555555b827c2 in mysql_sql_stmt_execute (thd=0x7fff9c000b00) at /home/midenok/src/mariadb/midenok/src/sql/sql_prepare.cc:3183
#11 0x0000555555b5d0f4 in mysql_execute_command (thd=0x7fff9c000b00) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:3590
#12 0x0000555555b6871a in mysql_parse (thd=0x7fff9c000b00, rawbuf=0x7fff9c012558 "execute stmt", length=12, parser_state=0x7ffff0872660, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:7902
```
Related to #97
