### ISSUE TITLE
Disallow TRUNCATE on versioned tables

### ISSUE THREAD

**Issue by kevgs** [tempesta-tech/mariadb#261]
Standard disallows TRUNCATE on system versioned tables:

`14.10 <truncate table statement>`
```
Syntax Rules
...
3) T shall be a base table and shall not be a system-versioned table.
```
Currently `TRUNCATE` on system versioned tables removes both current and historical rows. For DDL Survival mode `TRUNCATE` is still required. Disallow `TRUNCATE` for non-survive modes.

**Comment by midenok** [comment]
Updated description.

**Comment by kevgs** [comment]
```c++
#0  dd_recreate_table (thd=0x7fff88000b00, db=0x7fff88012e48 "test", table_name=0x7fff880127e0 "t1", path=0x0) at datadict.cc:166
#1  0x00000000010ce7ac in Sql_cmd_truncate_table::truncate_table (this=0x7fff88012e50, thd=0x7fff88000b00, table_ref=0x7fff88012818) at sql_truncate.cc:431
#2  0x00000000010ceb76 in Sql_cmd_truncate_table::execute (this=0x7fff88012e50, thd=0x7fff88000b00) at sql_truncate.cc:533
#3  0x0000000000dc5c6b in mysql_execute_command (thd=0x7fff88000b00) at sql_parse.cc:6224
#4  0x0000000000db723a in mysql_parse (thd=0x7fff88000b00, rawbuf=0x7fff88012748 "truncate table t1", length=17, parser_state=0x7ffff0352538, is_com_multi=false, is_next_command=false) at sql_parse.cc:7902
#5  0x0000000000db2260 in dispatch_command (command=COM_QUERY, thd=0x7fff88000b00, packet=0x7fff88008b01 "truncate table t1", packet_length=17, is_com_multi=false, is_next_command=false) at sql_parse.cc:1813
#6  0x0000000000db59db in do_command (thd=0x7fff88000b00) at sql_parse.cc:1376
#7  0x0000000000f84811 in do_handle_one_connection (connect=0x2b31160) at sql_connect.cc:1354
#8  0x0000000000f845ea in handle_one_connection (arg=0x2b31160) at sql_connect.cc:1260
#9  0x00000000016ff084 in pfs_spawn_thread (arg=0x2b3b5e0) at pfs.cc:1862
#10 0x00007ffff7bc06da in start_thread (arg=0x7ffff0354700) at pthread_create.c:456
#11 0x00007ffff6787d7f in clone () at clone.S:105
```
```gdb
(gdb) p table_ref->table
$1 = (TABLE *) 0x0
```
In that case table is not opened at all. And we can't check whether it's versioned by `table_ref->table->versioned()`.
