### ISSUE TITLE
REOGRANIZE PARTITION for system_time partitions

### ISSUE THREAD

**Issue by kevgs** [tempesta-tech/mariadb#265]
# Reproduce
```sql
create or replace table t1 (x int)
  with system versioning
  engine myisam
  partition by system_time limit 1 (
    partition p0 versioning,
    partition pn as of now);

alter table t1 reorganize partition p0 into (partition p00 versioning);
```

## Result
```
Thread 33 "mysqld" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe56eb700 (LWP 12139)]
0x0000555555c97f90 in partition_info::get_column_item (this=0x7fff900cc118, item=0x0, field=0x7fff900ca7a8) at /home/midenok/src/mariadb/trunk/src/sql/partition_info.cc:2832
2832          item->collation.collation != field->charset())
(gdb) bt
#0  0x0000555555c97f90 in partition_info::get_column_item (this=0x7fff900cc118, item=0x0, field=0x7fff900ca7a8) at /home/midenok/src/mariadb/trunk/src/sql/partition_info.cc:2832
#1  0x0000555555c98180 in partition_info::fix_column_value_functions (this=0x7fff900cc118, thd=0x7fff90000b00, val=0x7fff900120d0, part_id=0) at /home/midenok/src/mariadb/trunk/src/sql/partition_info.cc:2892
#2  0x0000555555c9472c in partition_info::check_range_constants (this=0x7fff900cc118, thd=0x7fff90000b00, alloc=true) at /home/midenok/src/mariadb/trunk/src/sql/partition_info.cc:1487
#3  0x0000555555c9635e in partition_info::check_partition_info (this=0x7fff900cc118, thd=0x7fff90000b00, eng_type=0x0, file=0x7fff900c9e18, info=0x0, add_or_reorg_part=true) at /home/midenok/src/mariadb/trunk/src/sql/partition_info.cc:2121
#4  0x0000555555fc30f0 in prep_alter_part_table (thd=0x7fff90000b00, table=0x7fff900c9200, alter_info=0x7fffe56e9420, create_info=0x7fffe56e94d0, alter_ctx=0x7fffe56e83b0, partition_changed=0x7fffe56e7a8d, fast_alter_table=0x7fffe56e7a8e) at /home/midenok/src/mariadb/trunk/src/sql/sql_partition.cc:5730
#5  0x0000555555c382a7 in mysql_alter_table (thd=0x7fff90000b00, new_db=0x7fff90011850 "test", new_name=0x0, create_info=0x7fffe56e94d0, table_list=0x7fff90011220, alter_info=0x7fffe56e9420, order_num=0, order=0x0, ignore=false) at /home/midenok/src/mariadb/trunk/src/sql/sql_table.cc:9002
#6  0x0000555555cbb6e8 in Sql_cmd_alter_table::execute (this=0x7fff90011bf8, thd=0x7fff90000b00) at /home/midenok/src/mariadb/trunk/src/sql/sql_alter.cc:318
#7  0x0000555555b67ad7 in mysql_execute_command (thd=0x7fff90000b00) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:6224
#8  0x0000555555b6bdd8 in mysql_parse (thd=0x7fff90000b00, rawbuf=0x7fff900110e8 "alter table t1 reorganize partition p0 into (partition p00 versioning)", length=70, parser_state=0x7fffe56ea6b0, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:7902
```
```
(gdb) p item
$1 = (Item *) 0x0
```

## Expected
Warning or error or partition renaming ??? @midenok

**Comment by midenok** [comment]
I think it should work as documented for **reorganize**.

**Comment by midenok** [comment]
This doesn't reproduce now. Please close.
