### ISSUE TITLE
Delete from VIEW fails

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#291]
### Tests failed
`versioning.delete`

### Reproduce
```sql
create or replace table t1 (x int) with system versioning;
insert into t1 values (1);
create or replace view vt1 as select x from t1;
delete from vt1;
select x from vt1;
```
### Result
```
+------+
| x    |
+------+
|    1 |
+------+
```
### Expected
No records in `vt1`.

### Notes
Works ok for plain tables.
```sql
create or replace table p1 (x int);
insert into p1 values (1);
create or replace view vp1 as select x from p1;
delete from vp1;
select x from vp1;
```

**Comment by midenok** [comment]
```
#0  TABLE::delete_row (this=0x7fff8404e470) at /home/midenok/src/mariadb/review/src/sql/sql_delete.cc:243
#1  0x0000000000c964eb in mysql_delete (thd=0x7fff84000d50, table_list=0x7fff84013810, conds=0x0, order_list=0x7fff84005418, limit=18446744073709551615, options=0, result=0x0) at /home/midenok/src/mariadb/review/src/sql/sql_delete.cc:674
#2  0x0000000000742fe0 in mysql_execute_command (thd=0x7fff84000d50) at /home/midenok/src/mariadb/review/src/sql/sql_parse.cc:4891
#3  0x0000000000739e3f in mysql_parse (thd=0x7fff84000d50, rawbuf=0x7fff84013748 "delete from vp1", length=15, parser_state=0x7fffe502d650, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/review/src/sql/sql_parse.cc:7947
```
