### ISSUE TITLE
Partitioning LIMIT or INTERVAL syntax error

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#294]
### Reproduce 1
```sql
create or replace table t1 (x int)
with system versioning
partition by system_time limit 1 (
    partition p0 versioning,
    partition pn as of now);
```
### Result 1
```
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'SYSTEM_TIMELIMIT 1
(PARTITION `p0` VERSIONING ENGINE = InnoDB,
 PARTITION `pn` A' at line 1
```
### Reproduce 2
```sql
create or replace table t1 (x int)
with system versioning
partition by system_time interval 1 second (
    partition p0 versioning,
    partition pn as of now);
```
### Result 2
```
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'SYSTEM_TIMEINTERVAL 1 SECOND 
(PARTITION `p0` VERSIONING ENGINE = InnoDB,
 PARTI' at line 1
```
### Expected
No error
### Tests affected
```
versioning.partition
```

**Comment by midenok** [comment]
```c++
#0  THD::parse_error (this=0x7fff7c000d50, err_text=0x286e4af "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use", yytext=0x0) at /home/midenok/src/mariadb/review/src/sql/sql_class.h:4110
#1  0x0000000000997ee5 in MYSQLerror (thd=0x7fff7c000d50, s=0x286e4af "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use") at /home/midenok/src/mariadb/review/src/sql/sql_yacc.yy:150
#2  0x00000000009d36fa in MYSQLparse (thd=0x7fff7c000d50) at sql/sql_yacc.cc:46153
#3  0x000000000074eb0a in parse_sql (thd=0x7fff7c000d50, parser_state=0x7fffe4e0f678, creation_ctx=0x0, do_pfs_digest=false) at /home/midenok/src/mariadb/review/src/sql/sql_parse.cc:9969
#4  0x0000000000cb1b08 in mysql_unpack_partition (thd=0x7fff7c000d50, part_buf=0x7fff7c03b878 " PARTITION BY SYSTEM_TIMELIMIT 1\n(PARTITION `p0` VERSIONING ENGINE = InnoDB,\n PARTITION `pn` AS OF NOW ENGINE = InnoDB)", part_info_len=119, table=0x7fffe4e11b80, is_create_table_ind=true, default_db_type=0x28ab620, work_part_info_used=0x7fffe4e1116f) at /home/midenok/src/mariadb/review/src/sql/sql_partition.cc:4203
#5  0x0000000000881f07 in open_table_from_share (thd=0x7fff7c000d50, share=0x7fffe4e11328, alias=0x15ca12a "", db_stat=0, prgflag=1, ha_open_flags=0, outparam=0x7fffe4e11b80, is_create_table=true) at /home/midenok/src/mariadb/review/src/sql/table.cc:3328
#6  0x0000000000a8ab19 in ha_create_table (thd=0x7fff7c000d50, path=0x7fffe4e14b70 "./test/t1", db=0x7fff7c013f58 "test", table_name=0x7fff7c0138e8 "t1", create_info=0x7fffe4e17390, frm=0x7fffe4e14b60) at /home/midenok/src/mariadb/review/src/sql/handler.cc:4792
#7  0x00000000008a2c5b in rea_create_table (thd=0x7fff7c000d50, frm=0x7fffe4e14b60, path=0x7fffe4e14b70 "./test/t1", db=0x7fff7c013f58 "test", table_name=0x7fff7c0138e8 "t1", create_info=0x7fffe4e17390, file=0x7fff7c015648, no_ha_create_table=false) at /home/midenok/src/mariadb/review/src/sql/unireg.cc:508
#8  0x00000000008354c7 in create_table_impl (thd=0x7fff7c000d50, orig_db=0x7fff7c013f58 "test", orig_table_name=0x7fff7c0138e8 "t1", db=0x7fff7c013f58 "test", table_name=0x7fff7c0138e8 "t1", path=0x7fffe4e14b70 "./test/t1", options=..., create_info=0x7fffe4e17390, alter_info=0x7fffe4e172e8, create_table_mode=0, is_trans=0x7fffe4e15597, key_info=0x7fffe4e14d88, key_count=0x7fffe4e14d84, frm=0x7fffe4e14b60) at /home/midenok/src/mariadb/review/src/sql/sql_table.cc:4846
#9  0x0000000000834827 in mysql_create_table_no_lock (thd=0x7fff7c000d50, db=0x7fff7c013f58 "test", table_name=0x7fff7c0138e8 "t1", create_info=0x7fffe4e17390, alter_info=0x7fffe4e172e8, is_trans=0x7fffe4e15597, create_table_mode=0, table_list=0x7fff7c013920) at /home/midenok/src/mariadb/review/src/sql/sql_table.cc:4956
#10 0x0000000000835cd4 in mysql_create_table (thd=0x7fff7c000d50, create_table=0x7fff7c013920, create_info=0x7fffe4e17390, alter_info=0x7fffe4e172e8) at /home/midenok/src/mariadb/review/src/sql/sql_table.cc:5032
#11 0x0000000000740b70 in mysql_execute_command (thd=0x7fff7c000d50) at /home/midenok/src/mariadb/review/src/sql/sql_parse.cc:4248
#12 0x0000000000739e5f in mysql_parse (thd=0x7fff7c000d50, rawbuf=0x7fff7c013748 "create or replace table t1 (x int) with system versioning partition by system_time limit 1 (     partition p0 versioning,     partition pn as of now)", length=149, parser_state=0x7fffe4e18650, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/review/src/sql/sql_parse.cc:7947
```
Wrong argument: `part_buf=0x7fff7c03b878 " PARTITION BY SYSTEM_TIMELIMIT 1\n`
