### ISSUE TITLE
Assertion fails for instant_alter_column_possible()

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#317]
### Failing tests
```
versioning.alter \
versioning.rpl_stmt,innodb,innodb \
versioning.rpl_row,innodb,innodb \
versioning.rpl_mixed,innodb,innodb
```
#### Test: versioning.alter
```c++
#3  0x00007ffff600afc2 in __GI___assert_fail (assertion=0x1626b2b "(ha_alter_info->handler_flags & ~INNOBASE_INPLACE_IGNORE) == Alter_inplace_info::CHANGE_CREATE_OPTION", file=0x1624a90 "/home/midenok/src/mariadb/trunk/src/storage/innobase/handler/handler0alter.cc", line=477, function=0x1626b91 "bool create_option_need_rebuild(const Alter_inplace_info *, const TABLE *)") at assert.c:101
#4  0x0000000000d72765 in create_option_need_rebuild (ha_alter_info=0x7ffff037b860, table=0x7fff9808a410) at /home/midenok/src/mariadb/trunk/src/storage/innobase/handler/handler0alter.cc:476
#5  0x0000000000d6aec6 in instant_alter_column_possible (ha_alter_info=0x7ffff037b860, table=0x7fff9808a410) at /home/midenok/src/mariadb/trunk/src/storage/innobase/handler/handler0alter.cc:665
#6  0x0000000000d6a304 in ha_innobase::check_if_supported_inplace_alter (this=0x7fff9808b048, altered_table=0x7fff980d4520, ha_alter_info=0x7ffff037b860) at /home/midenok/src/mariadb/trunk/src/storage/innobase/handler/handler0alter.cc:1139
#7  0x0000000000842341 in mysql_alter_table (thd=0x7fff98000d50, new_db=0x7fff980155f0 "test", new_name=0x0, create_info=0x7ffff037d3a8, table_list=0x7fff98014fb8, alter_info=0x7ffff037d300, order_num=0, order=0x0, ignore=false) at /home/midenok/src/mariadb/trunk/src/sql/sql_table.cc:9381
#8  0x00000000008ec3b8 in Sql_cmd_alter_table::execute (this=0x7fff98015858, thd=0x7fff98000d50) at /home/midenok/src/mariadb/trunk/src/sql/sql_alter.cc:325
#9  0x000000000074d9aa in mysql_execute_command (thd=0x7fff98000d50) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:6248
#10 0x000000000073f75f in mysql_parse (thd=0x7fff98000d50, rawbuf=0x7fff98014d48 "alter table t\nadd column trx_start bigint(20) unsigned generated always as row start,\nadd column trx_end bigint(20) unsigned generated always as row end,\nadd period for system_time(trx_start, trx_end),\nwith system versioning", length=224, parser_state=0x7ffff03805f0, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:7959
```
#### Test: versioning.rpl_stmt,innodb,innodb
```c++
#3  0x00007ffff600afc2 in __GI___assert_fail (assertion=0x1626b2b "(ha_alter_info->handler_flags & ~INNOBASE_INPLACE_IGNORE) == Alter_inplace_info::CHANGE_CREATE_OPTION", file=0x1624a90 "/home/midenok/src/mariadb/trunk/src/storage/innobase/handler/handler0alter.cc", line=477, function=0x1626b91 "bool create_option_need_rebuild(const Alter_inplace_info *, const TABLE *)") at assert.c:101
#4  0x0000000000d72765 in create_option_need_rebuild (ha_alter_info=0x7ffff01d9860, table=0x7fff8402b730) at /home/midenok/src/mariadb/trunk/src/storage/innobase/handler/handler0alter.cc:476
#5  0x0000000000d6aec6 in instant_alter_column_possible (ha_alter_info=0x7ffff01d9860, table=0x7fff8402b730) at /home/midenok/src/mariadb/trunk/src/storage/innobase/handler/handler0alter.cc:665
#6  0x0000000000d6a304 in ha_innobase::check_if_supported_inplace_alter (this=0x7fff84021568, altered_table=0x7fff84032e60, ha_alter_info=0x7ffff01d9860) at /home/midenok/src/mariadb/trunk/src/storage/innobase/handler/handler0alter.cc:1139
#7  0x0000000000842341 in mysql_alter_table (thd=0x7fff84000d50, new_db=0x7fff840141a8 "test", new_name=0x0, create_info=0x7ffff01db3a8, table_list=0x7fff84013b70, alter_info=0x7ffff01db300, order_num=0, order=0x0, ignore=false) at /home/midenok/src/mariadb/trunk/src/sql/sql_table.cc:9381
#8  0x00000000008ec3b8 in Sql_cmd_alter_table::execute (this=0x7fff840141b0, thd=0x7fff84000d50) at /home/midenok/src/mariadb/trunk/src/sql/sql_alter.cc:325
#9  0x000000000074d9aa in mysql_execute_command (thd=0x7fff84000d50) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:6248
#10 0x000000000073f75f in mysql_parse (thd=0x7fff84000d50, rawbuf=0x7fff84013a78 "alter table t1 with system versioning", length=37, parser_state=0x7ffff01de5f0, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:7959
```

**Comment by midenok** [comment]
Squashed into 497c6add88edae9c7ec6d6d840c0ed65adc016be
