### ISSUE TITLE
show create as of udf() assertion (3d)

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#319]
### Reproduce
```sql
delimiter ~~
create or replace function moment()
returns timestamp(6)
not deterministic
begin
  declare t timestamp(6);
  declare i int;
  set i= sleep(0.001);
  set t= now(6);
  set i= sleep(0.001);
  return t;
end~~
delimiter ;
set versioning_alter_history= survive;
create or replace table t (x int) with system versioning;
alter table t add column y int;
select moment();
show create table t for system_time as of timestamp moment();
```
### Result
```
(gdb) f 4
#4  0x0000000000a9c421 in handler::ha_external_lock (this=0x7fff7c04b578, thd=0x7fff7c000d50, lock_type=2) at /home/midenok/src/mariadb/review/src/sql/handler.cc:5953
5953      DBUG_ASSERT(inited == NONE || table->open_by_handler);
(gdb) p inited
$1 = handler::RND
(gdb) p table->open_by_handler
$2 = false
```
```c++
#4  0x0000000000a9c421 in handler::ha_external_lock (this=0x7fff7c04b578, thd=0x7fff7c000d50, lock_type=2) at /home/midenok/src/mariadb/review/src/sql/handler.cc:5953
#5  0x0000000000bf77d9 in unlock_external (thd=0x7fff7c000d50, table=0x7fff7c017650, count=1) at /home/midenok/src/mariadb/review/src/sql/lock.cc:723
#6  0x0000000000bf7950 in mysql_unlock_tables (thd=0x7fff7c000d50, sql_lock=0x7fff7c017638, free_lock=false) at /home/midenok/src/mariadb/review/src/sql/lock.cc:432
#7  0x0000000000bf7a9b in mysql_unlock_tables (thd=0x7fff7c000d50, sql_lock=0x7fff7c017638) at /home/midenok/src/mariadb/review/src/sql/lock.cc:417
#8  0x000000000069fac0 in close_thread_tables (thd=0x7fff7c000d50) at /home/midenok/src/mariadb/review/src/sql/sql_base.cc:840
#9  0x0000000000c7bb2e in sp_lex_keeper::reset_lex_and_exec_core (this=0x7fff7c052048, thd=0x7fff7c000d50, nextp=0x7fffe5247e28, open_tables=true, instr=0x7fff7c052000) at /home/midenok/src/mariadb/review/src/sql/sp_head.cc:3128
#10 0x0000000000c7d26a in sp_instr_set::execute (this=0x7fff7c052000, thd=0x7fff7c000d50, nextp=0x7fffe5247e28) at /home/midenok/src/mariadb/review/src/sql/sp_head.cc:3411
#11 0x0000000000c73844 in sp_head::execute (this=0x7fff7c050da8, thd=0x7fff7c000d50, merge_da_on_success=true) at /home/midenok/src/mariadb/review/src/sql/sp_head.cc:1200
#12 0x0000000000c7565c in sp_head::execute_function (this=0x7fff7c050da8, thd=0x7fff7c000d50, argp=0x0, argcount=0, return_value_fld=0x7fff7c017c58) at /home/midenok/src/mariadb/review/src/sql/sp_head.cc:1808
#13 0x0000000000b4073d in Item_func_sp::execute_impl (this=0x7fff7c015cc8, thd=0x7fff7c000d50) at /home/midenok/src/mariadb/review/src/sql/item_func.cc:6484
#14 0x0000000000b4043a in Item_func_sp::execute (this=0x7fff7c015cc8) at /home/midenok/src/mariadb/review/src/sql/item_func.cc:6417
#15 0x0000000000b4a624 in Item_func_sp::get_date (this=0x7fff7c015cc8, ltime=0x7fffe52487d0, fuzzydate=33554433) at /home/midenok/src/mariadb/review/src/sql/item_func.h:2817
#16 0x0000000000aa60f2 in Item::get_date_with_conversion (this=0x7fff7c015cc8, ltime=0x7fffe52487d0, fuzzydate=33554433) at /home/midenok/src/mariadb/review/src/sql/item.cc:143
#17 0x0000000000637635 in Item::val_datetime_packed (this=0x7fff7c015cc8) at /home/midenok/src/mariadb/review/src/sql/item.h:1418
#18 0x0000000000ad9235 in Arg_comparator::compare_datetime (this=0x7fff7c017a88) at /home/midenok/src/mariadb/review/src/sql/item_cmpfunc.cc:798
#19 0x0000000000af0ca2 in Arg_comparator::compare (this=0x7fff7c017a88) at /home/midenok/src/mariadb/review/src/sql/item_cmpfunc.h:102
#20 0x0000000000adcb15 in Item_func_gt::val_int (this=0x7fff7c0179c8) at /home/midenok/src/mariadb/review/src/sql/item_cmpfunc.cc:1789
#21 0x0000000000971588 in Type_handler_int_result::Item_val_bool (this=0x200bf28 <type_handler_long>, item=0x7fff7c0179c8) at /home/midenok/src/mariadb/review/src/sql/sql_type.cc:3199
#22 0x0000000000637075 in Item::val_bool (this=0x7fff7c0179c8) at /home/midenok/src/mariadb/review/src/sql/item.h:1125
#23 0x0000000000ae8d6a in Item_cond_and::val_int (this=0x7fff7c017b28) at /home/midenok/src/mariadb/review/src/sql/item_cmpfunc.cc:5001
#24 0x0000000000872f7c in SQL_SELECT::skip_record (this=0x7fff7c017d30, thd=0x7fff7c000d50) at /home/midenok/src/mariadb/review/src/sql/opt_range.h:1643
#25 0x0000000000a2ff7d in VTMD_table::find_archive_name (this=0x7fffe5249040, thd=0x7fff7c000d50, out=...) at /home/midenok/src/mariadb/review/src/sql/vtmd.cc:555
#26 0x0000000000a30b59 in VTMD_table::setup_select (this=0x7fffe5249040, thd=0x7fff7c000d50) at /home/midenok/src/mariadb/review/src/sql/vtmd.cc:673
#27 0x00000000007f811b in mysqld_show_create (thd=0x7fff7c000d50, table_list=0x7fff7c016ff8) at /home/midenok/src/mariadb/review/src/sql/sql_show.cc:1303
#28 0x0000000000747199 in mysql_execute_command (thd=0x7fff7c000d50) at /home/midenok/src/mariadb/review/src/sql/sql_parse.cc:4510
#29 0x000000000073f78f in mysql_parse (thd=0x7fff7c000d50, rawbuf=0x7fff7c0159a8 "show create table t for system_time as of timestamp moment()", length=60, parser_state=0x7fffe524d650, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/review/src/sql/sql_parse.cc:7959
```
### Fix test
After fix revert back `vtmd_show.test` from
```sql
  set @tm2= moment();
  show create table t for system_time as of timestamp @tm2;
```
to
```sql
  show create table t for system_time as of timestamp moment();
```

**Comment by kevgs** [comment]
```sql
set versioning_alter_history= survive;
create or replace table t (x int) with system versioning;
select * from t for system_time as of timestamp moment();
```
`moment()` is first used in `AS OF`.
```c++
bool
Item_func_sp::fix_fields(THD *thd, Item **ref)
{
  bool res;
  DBUG_ENTER("Item_func_sp::fix_fields");
  DBUG_ASSERT(fixed == 0);
  sp_head *sp= sp_handler_function.sp_find_routine(thd, m_name, true);
```
```
(gdb) p sp
$1 = (sp_head *) 0x0
(gdb) p *m_name
$2 = {
  <Sql_alloc> = {<No data fields>},
  <Database_qualified_name> = {
    m_db = LEX_CSTRING 0x7fff8c015190 "test" length 4,
    m_name = LEX_CSTRING 0x7fff8c015188 "moment" length 6
  },
  members of sp_name:
  m_explicit_name = false
}
```

**Comment by krizhanovsky** [comment]
Fixed for `archive/2017-11-23` branch in https://github.com/FooBarrior/mariadb/pull/1 by @FooBarrior:
```diff
diff --git a/sql/sql_parse.cc b/sql/sql_parse.cc
index 590fe245d7d..7cb4ea9fa78 100644
--- a/sql/sql_parse.cc
+++ b/sql/sql_parse.cc
@@ -6406,23 +6406,44 @@ static bool execute_sqlcom_select(THD *thd, TABLE_LIST *all_tables)
   if (check_dependencies_in_with_clauses(lex->with_clauses_list))
     return 1;
 
+  size_t vers_table_count= 0;
+
   if (thd->variables.vers_alter_history == VERS_ALTER_HISTORY_SURVIVE)
   {
+    for (TABLE_LIST *table= all_tables; table; table= table->next_local)
+    {
+      if (table->vers_conditions)
+        vers_table_count++;
+    }
+  }
+
+  VTMD_exists *vtmd_array= (VTMD_exists*)thd->calloc(sizeof (VTMD_exists) * vers_table_count);
+
+  if (thd->variables.vers_alter_history == VERS_ALTER_HISTORY_SURVIVE)
+  {
+    size_t i = 0;
     for (TABLE_LIST *table= all_tables; table; table= table->next_local)
     {
       if (table->vers_conditions)
       {
-        VTMD_exists vtmd(*table);
-        if (vtmd.check_exists(thd))
-          return 1;
-        if (vtmd.exists && vtmd.setup_select(thd))
+        VTMD_exists *vtmd= new (vtmd_array + i) VTMD_exists(*table);
+        if (vtmd->check_exists(thd))
           return 1;
+        vtmd->add_to_prelocking_list(thd);
+        i++;
       }
     }
   }
 
   if (!(res= open_and_lock_tables(thd, all_tables, TRUE, 0)))
   {
+    for (size_t i= 0; i < vers_table_count; i++)
+    {
+      VTMD_exists &vtmd= vtmd_array[i];
+      if (vtmd.exists && vtmd.setup_select(thd))
+        return 1;
+    }
+
     if (lex->describe)
     {
       /*
diff --git a/sql/sql_show.cc b/sql/sql_show.cc
index e6123da93fb..baefe19167e 100644
--- a/sql/sql_show.cc
+++ b/sql/sql_show.cc
@@ -1179,6 +1179,7 @@ mysqld_show_create_get_fields(THD *thd, TABLE_LIST *table_list,
   /* We want to preserve the tree for views. */
   thd->lex->context_analysis_only|= CONTEXT_ANALYSIS_ONLY_VIEW;
 
+  if (!table_list->table) /* table could be preopened by vtmd */
   {
     /*
       Use open_tables() directly rather than
@@ -1299,7 +1300,12 @@ mysqld_show_create(THD *thd, TABLE_LIST *table_list)
   if (versioned)
   {
     DBUG_ASSERT(table_list->vers_conditions == FOR_SYSTEM_TIME_AS_OF);
-    VTMD_table vtmd(*table_list);
+    VTMD_exists &vtmd = *new (thd->alloc(sizeof(VTMD_exists))) VTMD_exists(*table_list);
+    if (vtmd.check_exists(thd))
+      goto exit;
+    vtmd.add_to_prelocking_list(thd);
+    if (open_and_lock_tables(thd, table_list, TRUE, 0))
+      goto exit;
     if (vtmd.setup_select(thd))
       goto exit;
   }
diff --git a/sql/vtmd.cc b/sql/vtmd.cc
index ad03ea02156..ff68dfa4593 100644
--- a/sql/vtmd.cc
+++ b/sql/vtmd.cc
@@ -86,6 +86,22 @@ VTMD_table::find_record(ulonglong sys_trx_end, bool &found)
 }
 
 
+void
+VTMD_table::add_to_prelocking_list(THD *thd)
+{
+  vtmd.init_one_table_for_prelocking(
+    DB_WITH_LEN(about),
+    XSTRING_WITH_LEN(vtmd_name),
+    vtmd_name,
+    TL_READ,
+    true,
+    thd->lex->query_tables->belong_to_view,
+    thd->lex->query_tables->trg_event_map,
+    &thd->lex->query_tables_last);
+
+  vtmd.prelocking_placeholder = TABLE_LIST::USER;
+}
+
 bool
 VTMD_table::open(THD *thd, Local_da &local_da, bool *created)
 {
@@ -525,8 +541,9 @@ VTMD_table::find_archive_name(THD *thd, String &out)
   SELECT_LEX &select_lex= thd->lex->select_lex;
 
   Local_da local_da(thd, ER_VERS_VTMD_ERROR);
-  if (open(thd, local_da))
-    return true;
+
+  // tables should be already locked before running this method
+   DBUG_ASSERT(thd->lock);
 
   Name_resolution_context &ctx= thd->lex->select_lex.context;
   TABLE_LIST *table_list= ctx.table_list;
@@ -535,6 +552,7 @@ VTMD_table::find_archive_name(THD *thd, String &out)
   ctx.table_list= &vtmd;
   ctx.first_name_resolution_table= &vtmd;
   vtmd.table->map= 1;
+  vtmd.table->use_all_columns();
 
   vtmd.vers_conditions= about.vers_conditions;
   if ((error= vers_setup_select(thd, &vtmd, &conds, &select_lex)) ||
@@ -570,7 +588,6 @@ VTMD_table::find_archive_name(THD *thd, String &out)
   ctx.table_list= table_list;
   ctx.first_name_resolution_table= first_name_resolution_table;
   vtmd.table->map= map;
-  close_log_table(thd, &open_tables_backup);
   DBUG_ASSERT(!error || local_da.is_error());
   return error;
 }
diff --git a/sql/vtmd.h b/sql/vtmd.h
index 6c0a4be6bd7..a98f44a615c 100644
--- a/sql/vtmd.h
+++ b/sql/vtmd.h
@@ -55,9 +55,6 @@ class VTMD_table
   TABLE_LIST &about;
   SString_t vtmd_name;
 
-private:
-  VTMD_table(const VTMD_table&); // prohibit copying references
-
 public:
   enum {
     FLD_START= 0,
@@ -81,7 +78,8 @@ class VTMD_table
 
   bool create(THD *thd);
   bool find_record(ulonglong sys_trx_end, bool &found);
-  bool open(THD *thd, Local_da &local_da, bool *created= NULL);
+  void add_to_prelocking_list(THD *thd);
+  bool open(THD *thd, Local_da &local_da, bool *created);
   bool update(THD *thd, const char* archive_name= NULL);
   bool setup_select(THD *thd);

```
