### ISSUE TITLE
Hidden fields are not fully hidden

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#361]
Related to [MDEV-10177](https://jira.mariadb.org/browse/MDEV-10177), #49

### Reproduce
```sql
create or replace table t (x int primary key) engine innodb with system versioning;
show create table t;
describe t;
```
### Result
```
+-------+---------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                        |
+-------+---------------------------------------------------------------------------------------------------------------------+
| t     | CREATE TABLE `t` (
  `x` int(11) NOT NULL,
  PRIMARY KEY (`x`,`sys_trx_end`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 |
+-------+---------------------------------------------------------------------------------------------------------------------+
+---------------+---------------------+------+-----+---------+-------+
| Field         | Type                | Null | Key | Default | Extra |
+---------------+---------------------+------+-----+---------+-------+
| x             | int(11)             | NO   | PRI | NULL    |       |
| sys_trx_start | bigint(20) unsigned | YES  |     | NULL    |       |
| sys_trx_end   | bigint(20) unsigned | NO   | PRI | NULL    |       |
+---------------+---------------------+------+-----+---------+-------+
```
### Expected
No system fields displayed

### Tests affected
```
mtrf --mysqld="--versioning-force=1" --mysqld="--versioning-hide=full" --mysqld="--versioning-alter-history=keep"
```
* main.enforce_storage_engine_opt

**Comment by midenok** [comment]
### DESCRIBE command
```c++
#0  make_select (head=0x7fff7c08af98, const_tables=0, read_tables=0, conds=0x0, filesort=0x0, allow_null_cond=true, error=0x7fff7c0190e8) at /home/midenok/src/mariadb/review/src/sql/opt_range.cc:1172
#1  0x00000000007948cb in JOIN::optimize_stage2 (this=0x7fff7c018d00) at /home/midenok/src/mariadb/review/src/sql/sql_select.cc:2007
#2  0x00000000007989eb in JOIN::optimize_inner (this=0x7fff7c018d00) at /home/midenok/src/mariadb/review/src/sql/sql_select.cc:1916
#3  0x000000000079410c in JOIN::optimize (this=0x7fff7c018d00) at /home/midenok/src/mariadb/review/src/sql/sql_select.cc:1488
#4  0x000000000078cb0f in mysql_select (thd=0x7fff7c000d50, tables=0x7fff7c016c00, wild_num=0, fields=..., conds=0x0, og_num=0, order=0x0, group=0x0, having=0x0, proc_param=0x0, select_options=2684619520, result=0x7fff7c018ce0, unit=0x7fff7c004ac0, select_lex=0x7fff7c005220) at /home/midenok/src/mariadb/review/src/sql/sql_select.cc:4172
#5  0x000000000078c453 in handle_select (thd=0x7fff7c000d50, lex=0x7fff7c0049f8, result=0x7fff7c018ce0, setup_tables_done_option=0) at /home/midenok/src/mariadb/review/src/sql/sql_select.cc:368
#6  0x000000000074d76f in execute_sqlcom_select (thd=0x7fff7c000d50, all_tables=0x7fff7c016c00) at /home/midenok/src/mariadb/review/src/sql/sql_parse.cc:6503
#7  0x00000000007425e8 in mysql_execute_command (thd=0x7fff7c000d50) at /home/midenok/src/mariadb/review/src/sql/sql_parse.cc:3746
#8  0x000000000073d20f in mysql_parse (thd=0x7fff7c000d50, rawbuf=0x7fff7c0159a8 "describe t", length=10, parser_state=0x7fffe524d650, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/review/src/sql/sql_parse.cc:7959
```
