### ISSUE TITLE
Fully unversioned fields

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#375]
As per request from @vuvova, there is no much difference between unversioned fields and JOIN with unversioned table.

Warning about use of unversioned field in historical queries stays untouched.

[from chat:](https://tempesta-tech.slack.com/archives/C80AX4708/p1512635216000172)

> [11:26] midenok: That will lead to errors as user not always remembers what fields are optimized and how they work. They will use value from future in results from past. This is total mess. At least query should return warning. At most error.
If column was added is different story. There was no any value in past. For optimized fields there was some value.

> [11:31] serg: if a column was added, it's different, I agree that NULL is appropriate
but not if the column was declared WITHOUT VERSIONING
then, I think, it should return a current value
like like in the case, say
SELECT * FROM (select * FROM versioned_table JOIN unversioned_table) FOR SYSTEM_TIME AS OF xxx

**Comment by midenok** [comment]
### `vers_setup_conds()` called first time
```c++
#0  st_select_lex::vers_setup_conds (this=0x7fff9812bdd0, thd=0x7fff98000d50, tables=0x7fff98128268, where_expr=0x7fff98137b90) at /home/midenok/src/mariadb/trunk/src/sql/sql_select.cc:735
#1  0x0000000000790b3c in JOIN::prepare (this=0x7fff98137788, tables_init=0x7fff98128268, wild_num=0, conds_init=0x0, og_num=0, order_init=0x0, skip_order_by=false, group_init=0x0, having_init=0x0, proc_param_init=0x0, select_lex_arg=0x7fff9812bdd0, unit_arg=0x7fff9812b670) at /home/midenok/src/mariadb/trunk/src/sql/sql_select.cc:1102
#2  0x000000000078d0d9 in mysql_select (thd=0x7fff98000d50, tables=0x7fff98128268, wild_num=0, fields=..., conds=0x0, og_num=0, order=0x0, group=0x0, having=0x0, proc_param=0x0, select_options=2147749632, result=0x7fff981233a8, unit=0x7fff9812b670, select_lex=0x7fff9812bdd0) at /home/midenok/src/mariadb/trunk/src/sql/sql_select.cc:4167
#3  0x000000000078ca53 in handle_select (thd=0x7fff98000d50, lex=0x7fff9812b5a8, result=0x7fff981233a8, setup_tables_done_option=0) at /home/midenok/src/mariadb/trunk/src/sql/sql_select.cc:368
#4  0x000000000074dd6f in execute_sqlcom_select (thd=0x7fff98000d50, all_tables=0x7fff98128268) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:6503
#5  0x0000000000742be8 in mysql_execute_command (thd=0x7fff98000d50) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:3746
#6  0x0000000000c7e365 in sp_instr_stmt::exec_core (this=0x7fff98125220, thd=0x7fff98000d50, nextp=0x7ffff037c7d8) at /home/midenok/src/mariadb/trunk/src/sql/sp_head.cc:3394
#7  0x0000000000c7cbca in sp_lex_keeper::reset_lex_and_exec_core (this=0x7fff98125270, thd=0x7fff98000d50, nextp=0x7ffff037c7d8, open_tables=false, instr=0x7fff98125220) at /home/midenok/src/mariadb/trunk/src/sql/sp_head.cc:3110
#8  0x0000000000c7d5bd in sp_instr_stmt::execute (this=0x7fff98125220, thd=0x7fff98000d50, nextp=0x7ffff037c7d8) at /home/midenok/src/mariadb/trunk/src/sql/sp_head.cc:3297
#9  0x0000000000c74a44 in sp_head::execute (this=0x7fff9811b2e8, thd=0x7fff98000d50, merge_da_on_success=true) at /home/midenok/src/mariadb/trunk/src/sql/sp_head.cc:1200
#10 0x0000000000c77a30 in sp_head::execute_procedure (this=0x7fff9811b2e8, thd=0x7fff98000d50, args=0x7fff98005858) at /home/midenok/src/mariadb/trunk/src/sql/sp_head.cc:2077
#11 0x00000000007405e2 in do_execute_sp (thd=0x7fff98000d50, sp=0x7fff9811b2e8) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:2924
#12 0x000000000073ffe1 in Sql_cmd_call::execute (this=0x7fff98014e58, thd=0x7fff98000d50) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:3166
#13 0x000000000074ba5a in mysql_execute_command (thd=0x7fff98000d50) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:6248
#14 0x000000000073d80f in mysql_parse (thd=0x7fff98000d50, rawbuf=0x7fff98014d48 "call test_02('timestamp(6)', 'myisam', 'sys_end')", length=49, parser_state=0x7ffff03805f0, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:7959
```
### `vers_setup_conds()` called second time
```c++
#0  st_select_lex::vers_setup_conds (this=0x7fff9812bdd0, thd=0x7fff98000d50, tables=0x7fff98128268, where_expr=0x7fff98137ba8) at /home/midenok/src/mariadb/trunk/src/sql/sql_select.cc:735
#1  0x0000000000790b3c in JOIN::prepare (this=0x7fff981377a0, tables_init=0x7fff98128268, wild_num=0, conds_init=0x7fff981351b0, og_num=0, order_init=0x0, skip_order_by=false, group_init=0x0, having_init=0x0, proc_param_init=0x0, select_lex_arg=0x7fff9812bdd0, unit_arg=0x7fff9812b670) at /home/midenok/src/mariadb/trunk/src/sql/sql_select.cc:1102
#2  0x000000000078d0d9 in mysql_select (thd=0x7fff98000d50, tables=0x7fff98128268, wild_num=0, fields=..., conds=0x7fff981351b0, og_num=0, order=0x0, group=0x0, having=0x0, proc_param=0x0, select_options=2147749632, result=0x7fff981233a8, unit=0x7fff9812b670, select_lex=0x7fff9812bdd0) at /home/midenok/src/mariadb/trunk/src/sql/sql_select.cc:4167
#3  0x000000000078ca53 in handle_select (thd=0x7fff98000d50, lex=0x7fff9812b5a8, result=0x7fff981233a8, setup_tables_done_option=0) at /home/midenok/src/mariadb/trunk/src/sql/sql_select.cc:368
#4  0x000000000074dd6f in execute_sqlcom_select (thd=0x7fff98000d50, all_tables=0x7fff98128268) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:6503
#5  0x0000000000742be8 in mysql_execute_command (thd=0x7fff98000d50) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:3746
#6  0x0000000000c7e365 in sp_instr_stmt::exec_core (this=0x7fff98125220, thd=0x7fff98000d50, nextp=0x7ffff037c7d8) at /home/midenok/src/mariadb/trunk/src/sql/sp_head.cc:3394
#7  0x0000000000c7cbca in sp_lex_keeper::reset_lex_and_exec_core (this=0x7fff98125270, thd=0x7fff98000d50, nextp=0x7ffff037c7d8, open_tables=false, instr=0x7fff98125220) at /home/midenok/src/mariadb/trunk/src/sql/sp_head.cc:3110
#8  0x0000000000c7d5bd in sp_instr_stmt::execute (this=0x7fff98125220, thd=0x7fff98000d50, nextp=0x7ffff037c7d8) at /home/midenok/src/mariadb/trunk/src/sql/sp_head.cc:3297
#9  0x0000000000c74a44 in sp_head::execute (this=0x7fff9811b2e8, thd=0x7fff98000d50, merge_da_on_success=true) at /home/midenok/src/mariadb/trunk/src/sql/sp_head.cc:1200
#10 0x0000000000c77a30 in sp_head::execute_procedure (this=0x7fff9811b2e8, thd=0x7fff98000d50, args=0x7fff98005858) at /home/midenok/src/mariadb/trunk/src/sql/sp_head.cc:2077
#11 0x00000000007405e2 in do_execute_sp (thd=0x7fff98000d50, sp=0x7fff9811b2e8) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:2924
#12 0x000000000073ffe1 in Sql_cmd_call::execute (this=0x7fff98014e80, thd=0x7fff98000d50) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:3166
#13 0x000000000074ba5a in mysql_execute_command (thd=0x7fff98000d50) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:6248
#14 0x000000000073d80f in mysql_parse (thd=0x7fff98000d50, rawbuf=0x7fff98014d48 "call test_02('bigint unsigned', 'innodb', 'vtq_commit_ts(sys_end)')", length=67, parser_state=0x7ffff03805f0, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:7959
```

Same SP called second time.
