### ISSUE TITLE
MDEV-14645: AS OF TIMESTAMP is misused as TRX_ID

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#396]
https://jira.mariadb.org/browse/MDEV-14645

### Reproduce
```sql
create or replace table t1 (i int) with system versioning engine innodb;
insert into t1 values (1);
delete from t1;
select sys_trx_start from t1 for system_time all into @trx_start;
select * from t1 for system_time as of timestamp @trx_start;
```
### Result
```
+------+
| i    |
+------+
|    1 |
+------+
```
### Expected
@trx_start is interpreted not as TRX_ID but as integer timestamp.

**Comment by midenok** [comment]
### Integer used as datetime
```c++
#0  push_warning (thd=0x7fff78000d50, level=Sql_state_errno_level::WARN_LEVEL_WARN, code=1292, msg=0x7fffe5268660 "Incorrect datetime value: '1513249266.691968'") at /home/midenok/src/mariadb/trunk/src/sql/sql_error.cc:703
#1  0x00000000008a2089 in make_truncated_value_warning (thd=0x7fff78000d50, level=Sql_state_errno_level::WARN_LEVEL_WARN, sval=0x7fffe5268960, time_type=MYSQL_TIMESTAMP_ERROR, field_name=0x0) at /home/midenok/src/mariadb/trunk/src/sql/sql_time.cc:893
#2  0x00000000008a296e in number_to_time_with_warn (neg=false, nr=1513249266, sec_part=691968, ltime=0x7fffe5268e48, fuzzydate=33554433, str=0x7fffe5268960, field_name=0x0) at /home/midenok/src/mariadb/trunk/src/sql/sql_time.cc:386
#3  0x00000000008a2a31 in decimal_to_datetime_with_warn (value=0x7fffe5268bf8, ltime=0x7fffe5268e48, fuzzydate=33554433, field_name=0x0) at /home/midenok/src/mariadb/trunk/src/sql/sql_time.cc:422
#4  0x0000000000b31306 in Item_func_hybrid_field_type::get_date_from_decimal_op (this=0x7fff78013be8, ltime=0x7fffe5268e48, fuzzydate=33554433) at /home/midenok/src/mariadb/trunk/src/sql/item_func.cc:836
#5  0x0000000000975f69 in Type_handler_decimal_result::Item_func_hybrid_field_type_get_date (this=0x2032de0 <type_handler_newdecimal>, item=0x7fff78013be8, ltime=0x7fffe5268e48, fuzzydate=33554433) at /home/midenok/src/mariadb/trunk/src/sql/sql_type.cc:3371
#6  0x00000000007383da in Item_func_hybrid_field_type::get_date (this=0x7fff78013be8, res=0x7fffe5268e48, fuzzy_date=33554433) at /home/midenok/src/mariadb/trunk/src/sql/item_func.h:572
#7  0x0000000000aac972 in Item::get_date_with_conversion (this=0x7fff78013be8, ltime=0x7fffe5268e48, fuzzydate=33554433) at /home/midenok/src/mariadb/trunk/src/sql/item.cc:149
#8  0x0000000000bd2ff6 in Item_func::get_arg0_date (this=0x7fff78014b60, ltime=0x7fffe5268e48, fuzzy_date=33554433) at /home/midenok/src/mariadb/trunk/src/sql/item_func.h:166
#9  0x0000000000bcefbc in Item_datetime_typecast::get_date (this=0x7fff78014b60, ltime=0x7fffe5268e48, fuzzy_date=33554433) at /home/midenok/src/mariadb/trunk/src/sql/item_timefunc.cc:2643
#10 0x00000000006380f5 in Item::get_date_result (this=0x7fff78014b60, ltime=0x7fffe5268e48, fuzzydate=33554433) at /home/midenok/src/mariadb/trunk/src/sql/item.h:1440
#11 0x0000000000aac818 in Item::val_datetime_packed_result (this=0x7fff78014b60) at /home/midenok/src/mariadb/trunk/src/sql/item.cc:121
#12 0x0000000000acf732 in Item_cache_temporal::cache_value (this=0x7fff78017018) at /home/midenok/src/mariadb/trunk/src/sql/item.cc:9982
#13 0x0000000000acf21e in Item_cache_temporal::val_datetime_packed (this=0x7fff78017018) at /home/midenok/src/mariadb/trunk/src/sql/item.cc:9906
#14 0x0000000000ae1765 in Arg_comparator::compare_datetime (this=0x7fff78014e40) at /home/midenok/src/mariadb/trunk/src/sql/item_cmpfunc.cc:798
#15 0x0000000000af91f2 in Arg_comparator::compare (this=0x7fff78014e40) at /home/midenok/src/mariadb/trunk/src/sql/item_cmpfunc.h:102
#16 0x0000000000ae5045 in Item_func_gt::val_int (this=0x7fff78014d80) at /home/midenok/src/mariadb/trunk/src/sql/item_cmpfunc.cc:1789
#17 0x0000000000975a78 in Type_handler_int_result::Item_val_bool (this=0x2032d98 <type_handler_long>, item=0x7fff78014d80) at /home/midenok/src/mariadb/trunk/src/sql/sql_type.cc:3199
#18 0x0000000000637a65 in Item::val_bool (this=0x7fff78014d80) at /home/midenok/src/mariadb/trunk/src/sql/item.h:1122
#19 0x0000000000af129a in Item_cond_and::val_int (this=0x7fff78017298) at /home/midenok/src/mariadb/trunk/src/sql/item_cmpfunc.cc:5001
#20 0x00000000007d3b83 in evaluate_join_record (join=0x7fff780143e8, join_tab=0x7fff780166c8, error=0) at /home/midenok/src/mariadb/trunk/src/sql/sql_select.cc:19562
#21 0x00000000007d3341 in sub_select (join=0x7fff780143e8, join_tab=0x7fff780166c8, end_of_records=false) at /home/midenok/src/mariadb/trunk/src/sql/sql_select.cc:19467
#22 0x00000000007bb718 in do_select (join=0x7fff780143e8, procedure=0x0) at /home/midenok/src/mariadb/trunk/src/sql/sql_select.cc:19007
#23 0x00000000007ba4f9 in JOIN::exec_inner (this=0x7fff780143e8) at /home/midenok/src/mariadb/trunk/src/sql/sql_select.cc:4045
#24 0x00000000007b942e in JOIN::exec (this=0x7fff780143e8) at /home/midenok/src/mariadb/trunk/src/sql/sql_select.cc:3828
#25 0x00000000007910fc in mysql_select (thd=0x7fff78000d50, tables=0x7fff78013cc0, wild_num=1, fields=..., conds=0x0, og_num=0, order=0x0, group=0x0, having=0x0, proc_param=0x0, select_options=2147748608, result=0x7fff780143c8, unit=0x7fff78004ac0, select_lex=0x7fff78005220) at /home/midenok/src/mariadb/trunk/src/sql/sql_select.cc:4240
```
