### ISSUE TITLE
MDEV-14650 Assertion `0' failed in TABLE::vers_update_fields

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#402]
### Reproduce
```sql
create table or replace t1 (i int) engine=innodb with system versioning partition by hash(i);
alter table t1 engine=myisam;
```
### Result
Command succeeds
### Expected
Error
```
ERROR 4119 (HY000): Not allowed for versioned `test`.`t1`. Change to/from native versioning engine is prohibited.
```

**Comment by midenok** [comment]
### Engine change is prohibited
```c++
#0  my_error (nr=4119, MyFlags=0) at /home/midenok/src/mariadb/trunk/src/mysys/my_error.c:113
#1  0x0000000000843ef6 in mysql_alter_table (thd=0x7fff80000d50, new_db=0x7fff80013f98 "test", new_name=0x0, create_info=0x7fffe508e408, table_list=0x7fff80013960, alter_info=0x7fffe508e360, order_num=0, order=0x0, ignore=false) at /home/midenok/src/mariadb/trunk/src/sql/sql_table.cc:8864
#2  0x00000000008f0408 in Sql_cmd_alter_table::execute (this=0x7fff80013fa8, thd=0x7fff80000d50) at /home/midenok/src/mariadb/trunk/src/sql/sql_alter.cc:325
#3  0x000000000074ff75 in mysql_execute_command (thd=0x7fff80000d50) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:6258
#4  0x0000000000741cdf in mysql_parse (thd=0x7fff80000d50, rawbuf=0x7fff80013878 "alter table t1 engine=myisam", length=28, parser_state=0x7fffe5091650, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:7988
```
