### ISSUE TITLE
NATURAL JOIN of versioned VIEW fails

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#405]
### Reproduce
```sql
create or replace table t1 (a int) with system versioning;
create or replace table t2 (b int);
create or replace view v1 as select a, sys_trx_start, sys_trx_end from t1 where a > round(rand()*1000);
select * from v1 natural join t2;
```
### Result
```c++
#0  0x00000000006b51ab in mark_common_columns (thd=0x7fff78000d50, table_ref_1=0x7fff78013a80, table_ref_2=0x7fff78014108, using_fields=0x0, found_using_fields=0x7fffe5268cec) at /home/midenok/src/mariadb/trunk/src/sql/sql_base.cc:6425
#1  0x00000000006b4af7 in store_top_level_join_columns (thd=0x7fff78000d50, table_ref=0x7fff78014758, left_neighbor=0x0, right_neighbor=0x0) at /home/midenok/src/mariadb/trunk/src/sql/sql_base.cc:6857
#2  0x00000000006b0e1d in setup_natural_join_row_types (thd=0x7fff78000d50, from_clause=0x7fff780053c8, context=0x7fff78005278) at /home/midenok/src/mariadb/trunk/src/sql/sql_base.cc:6980
#3  0x00000000006b0b87 in setup_tables (thd=0x7fff78000d50, context=0x7fff78005278, from_clause=0x7fff780053c8, tables=0x7fff78013a80, leaves=..., select_insert=false, full_table_list=false) at /home/midenok/src/mariadb/trunk/src/sql/sql_base.cc:7396
#4  0x00000000006b1027 in setup_tables_and_check_access (thd=0x7fff78000d50, context=0x7fff78005278, from_clause=0x7fff780053c8, tables=0x7fff78013a80, leaves=..., select_insert=false, want_access_first=1, want_access=1, full_table_list=false) at /home/midenok/src/mariadb/trunk/src/sql/sql_base.cc:7439
#5  0x0000000000794eae in JOIN::prepare (this=0x7fff780184f0, tables_init=0x7fff78013a80, wild_num=1, conds_init=0x0, og_num=0, order_init=0x0, skip_order_by=false, group_init=0x0, having_init=0x0, proc_param_init=0x0, select_lex_arg=0x7fff78005230, unit_arg=0x7fff78004ad0) at /home/midenok/src/mariadb/trunk/src/sql/sql_select.cc:1138
#6  0x0000000000791079 in mysql_select (thd=0x7fff78000d50, tables=0x7fff78013a80, wild_num=1, fields=..., conds=0x0, og_num=0, order=0x0, group=0x0, having=0x0, proc_param=0x0, select_options=2147748608, result=0x7fff780184d0, unit=0x7fff78004ad0, select_lex=0x7fff78005230) at /home/midenok/src/mariadb/trunk/src/sql/sql_select.cc:4229
#7  0x00000000007909f3 in handle_select (thd=0x7fff78000d50, lex=0x7fff78004a08, result=0x7fff780184d0, setup_tables_done_option=0) at /home/midenok/src/mariadb/trunk/src/sql/sql_select.cc:368
#8  0x000000000075228f in execute_sqlcom_select (thd=0x7fff78000d50, all_tables=0x7fff78013a80) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:6532
#9  0x00000000007470f6 in mysql_execute_command (thd=0x7fff78000d50) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:3749
#10 0x0000000000741cdf in mysql_parse (thd=0x7fff78000d50, rawbuf=0x7fff78013878 "select * from v1 natural join t2", length=32, parser_state=0x7fffe526d650, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:7988
```
```
(gdb) f 0
#0  0x00000000006b51ab in mark_common_columns (thd=0x7fff78000d50, table_ref_1=0x7fff78013a80, table_ref_2=0x7fff78014108, using_fields=0x0, found_using_fields=0x7fffe5268cec) at /home/midenok/src/mariadb/trunk/src/sql/sql_base.cc:6425
6425          Item *item= nj_col_1->view_field->item;
(gdb) p nj_col_1->view_field
$7 = (Field_translator *) 0x0
```

**Comment by midenok** [comment]
Related to #161 (e8ae9f1ae9e361c41148f32f9efbae49ccadff19).

#161 is deprecated by #383.
