### ISSUE TITLE
MDEV-14633 Assertion on TRT read

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#406]
### Reproduce
```sql
create or replace table t1 (pk int primary key, i int, t time, key (i))
engine=innodb with system versioning;
insert into t1 values (1,10,'15:01:53'),(2,20,'00:00:00');
delete from t1;
select * from t1 where t = '00:00:00' and i > 0 and sys_trx_end <> '2012-12-12 00:00:00';
```
### Result
```c++
#3  0x00007ffff600afc2 in __GI___assert_fail (assertion=0x16654e6 "trx->lock.n_active_thrs == 1", file=0x16652b0 "/home/midenok/src/mariadb/trunk/src/storage/innobase/que/que0que.cc", line=865, function=0x1665540 "void que_thr_stop_for_mysql_no_error(que_thr_t *, trx_t *)") at assert.c:101
#4  0x0000000000e85917 in que_thr_stop_for_mysql_no_error (thr=0x33603d0, trx=0x7fffef913508) at /home/midenok/src/mariadb/trunk/src/storage/innobase/que/que0que.cc:865
#5  0x0000000000f38f49 in row_search_mvcc (buf=0x335d638 "\377\004\r", mode=PAGE_CUR_G, prebuilt=0x335f878, match_mode=0, direction=0) at /home/midenok/src/mariadb/trunk/src/storage/innobase/row/row0sel.cc:5740
#6  0x0000000000d48514 in ha_innobase::index_read (this=0x335ce28, buf=0x335d638 "\377\004\r", key_ptr=0x0, key_len=0, find_flag=HA_READ_AFTER_KEY) at /home/midenok/src/mariadb/trunk/src/storage/innobase/handler/ha_innodb.cc:9687
#7  0x0000000000d491cb in ha_innobase::index_first (this=0x335ce28, buf=0x335d638 "\377\004\r") at /home/midenok/src/mariadb/trunk/src/storage/innobase/handler/ha_innodb.cc:10126
#8  0x0000000000d49513 in ha_innobase::rnd_next (this=0x335ce28, buf=0x335d638 "\377\004\r") at /home/midenok/src/mariadb/trunk/src/storage/innobase/handler/ha_innodb.cc:10222
#9  0x0000000000a96765 in handler::ha_rnd_next (this=0x335ce28, buf=0x335d638 "\377\004\r") at /home/midenok/src/mariadb/trunk/src/sql/handler.cc:2626
#10 0x0000000000c759f4 in rr_sequential (info=0x7fffe5266698) at /home/midenok/src/mariadb/trunk/src/sql/records.cc:485
#11 0x000000000069b3cb in READ_RECORD::read_record (this=0x7fffe5266698) at /home/midenok/src/mariadb/trunk/src/sql/records.h:73
#12 0x000000000089d2f5 in TR_table::query (this=0x7fffe52667e8, trx_id=14601) at /home/midenok/src/mariadb/trunk/src/sql/table.cc:8663
#13 0x0000000000a4e124 in Field_vers_trx_id::get_date (this=0x7fff8004a4a0, ltime=0x7fffe5266f90, fuzzydate=33554433, trx_id=14601) at /home/midenok/src/mariadb/trunk/src/sql/field.cc:2016
#14 0x0000000000a7d4bf in Field_vers_trx_id::get_date (this=0x7fff8004a4a0, ltime=0x7fffe5266f90, fuzzydate=33554433) at /home/midenok/src/mariadb/trunk/src/sql/field.h:2204
#15 0x0000000000ab8adc in Item_field::get_date (this=0x7fff800148a8, ltime=0x7fffe5266f90, fuzzydate=33554433) at /home/midenok/src/mariadb/trunk/src/sql/item.cc:3390
#16 0x0000000000aacce2 in Item::get_date_with_conversion (this=0x7fff800148a8, ltime=0x7fffe5266f90, fuzzydate=33554433) at /home/midenok/src/mariadb/trunk/src/sql/item.cc:149
#17 0x0000000000638125 in Item::val_datetime_packed (this=0x7fff800148a8) at /home/midenok/src/mariadb/trunk/src/sql/item.h:1415
#18 0x0000000000ae1b36 in Arg_comparator::compare_datetime (this=0x7fff80014b28) at /home/midenok/src/mariadb/trunk/src/sql/item_cmpfunc.cc:795
#19 0x0000000000af95f2 in Arg_comparator::compare (this=0x7fff80014b28) at /home/midenok/src/mariadb/trunk/src/sql/item_cmpfunc.h:102
#20 0x0000000000ae52e5 in Item_func_ne::val_int (this=0x7fff80014a68) at /home/midenok/src/mariadb/trunk/src/sql/item_cmpfunc.cc:1773
#21 0x0000000000975de8 in Type_handler_int_result::Item_val_bool (this=0x2033d98 <type_handler_long>, item=0x7fff80014a68) at /home/midenok/src/mariadb/trunk/src/sql/sql_type.cc:3199
#22 0x0000000000637b75 in Item::val_bool (this=0x7fff80014a68) at /home/midenok/src/mariadb/trunk/src/sql/item.h:1122
#23 0x0000000000af169a in Item_cond_and::val_int (this=0x7fff80018748) at /home/midenok/src/mariadb/trunk/src/sql/item_cmpfunc.cc:5001
#24 0x0000000000aa0537 in handler_index_cond_check (h_arg=0x7fff80043ae8) at /home/midenok/src/mariadb/trunk/src/sql/handler.cc:5598
#25 0x0000000000d5c025 in innobase_index_cond (file=0x7fff80043ae8) at /home/midenok/src/mariadb/trunk/src/storage/innobase/handler/ha_innodb.cc:21475
#26 0x0000000000f3a550 in row_search_idx_cond_check (mysql_rec=0x7fff80034798 "\375\001", prebuilt=0x7fff8004ac58, rec=0x7fffe7e740aa "\200", offsets=0x7fffe52682a0) at /home/midenok/src/mariadb/trunk/src/storage/innobase/row/row0sel.cc:4010
#27 0x0000000000f377f5 in row_search_mvcc (buf=0x7fff80034798 "\375\001", mode=PAGE_CUR_G, prebuilt=0x7fff8004ac58, match_mode=0, direction=0) at /home/midenok/src/mariadb/trunk/src/storage/innobase/row/row0sel.cc:5230
#28 0x0000000000d48514 in ha_innobase::index_read (this=0x7fff80043ae8, buf=0x7fff80034798 "\375\001", key_ptr=0x7fff800501d8 "", key_len=5, find_flag=HA_READ_AFTER_KEY) at /home/midenok/src/mariadb/trunk/src/storage/innobase/handler/ha_innodb.cc:9687
#29 0x0000000000aa88eb in handler::index_read_map (this=0x7fff80043ae8, buf=0x7fff80034798 "\375\001", key=0x7fff800501d8 "", keypart_map=1, find_flag=HA_READ_AFTER_KEY) at /home/midenok/src/mariadb/trunk/src/sql/handler.h:3399
#30 0x0000000000a96f81 in handler::ha_index_read_map (this=0x7fff80043ae8, buf=0x7fff80034798 "\375\001", key=0x7fff800501d8 "", keypart_map=1, find_flag=HA_READ_AFTER_KEY) at /home/midenok/src/mariadb/trunk/src/sql/handler.cc:2676
#31 0x0000000000aa0008 in handler::read_range_first (this=0x7fff80043ae8, start_key=0x7fff80043bd0, end_key=0x0, eq_range_arg=false, sorted=true) at /home/midenok/src/mariadb/trunk/src/sql/handler.cc:5453
#32 0x0000000000939687 in handler::multi_range_read_next (this=0x7fff80043ae8, range_info=0x7fffe52690c8) at /home/midenok/src/mariadb/trunk/src/sql/multi_range_read.cc:286
#33 0x0000000000939879 in Mrr_simple_index_reader::get_next (this=0x7fff80044070, range_info=0x7fffe52690c8) at /home/midenok/src/mariadb/trunk/src/sql/multi_range_read.cc:323
#34 0x000000000093cb50 in DsMrr_impl::dsmrr_next (this=0x7fff80043f30, range_info=0x7fffe52690c8) at /home/midenok/src/mariadb/trunk/src/sql/multi_range_read.cc:1399
#35 0x0000000000d5be3f in ha_innobase::multi_range_read_next (this=0x7fff80043ae8, range_info=0x7fffe52690c8) at /home/midenok/src/mariadb/trunk/src/storage/innobase/handler/ha_innodb.cc:21414
#36 0x0000000000c5ca70 in QUICK_RANGE_SELECT::get_next (this=0x7fff80026fd0) at /home/midenok/src/mariadb/trunk/src/sql/opt_range.cc:11444
#37 0x0000000000c75810 in rr_quick (info=0x7fff80017908) at /home/midenok/src/mariadb/trunk/src/sql/records.cc:366
#38 0x000000000069b3cb in READ_RECORD::read_record (this=0x7fff80017908) at /home/midenok/src/mariadb/trunk/src/sql/records.h:73
#39 0x00000000007b777c in join_init_read_record (tab=0x7fff80017840) at /home/midenok/src/mariadb/trunk/src/sql/sql_select.cc:20401
#40 0x00000000007d325a in sub_select (join=0x7fff80014cb0, join_tab=0x7fff80017840, end_of_records=false) at /home/midenok/src/mariadb/trunk/src/sql/sql_select.cc:19475
#41 0x00000000007bb698 in do_select (join=0x7fff80014cb0, procedure=0x0) at /home/midenok/src/mariadb/trunk/src/sql/sql_select.cc:19018
#42 0x00000000007ba479 in JOIN::exec_inner (this=0x7fff80014cb0) at /home/midenok/src/mariadb/trunk/src/sql/sql_select.cc:4056
#43 0x00000000007b93ae in JOIN::exec (this=0x7fff80014cb0) at /home/midenok/src/mariadb/trunk/src/sql/sql_select.cc:3839
#44 0x000000000079105c in mysql_select (thd=0x7fff80000d50, tables=0x7fff80013af0, wild_num=1, fields=..., conds=0x7fff80014768, og_num=0, order=0x0, group=0x0, having=0x0, proc_param=0x0, select_options=2147748608, result=0x7fff80014c90, unit=0x7fff80004ad0, select_lex=0x7fff80005230) at /home/midenok/src/mariadb/trunk/src/sql/sql_select.cc:4251
#45 0x00000000007908b3 in handle_select (thd=0x7fff80000d50, lex=0x7fff80004a08, result=0x7fff80014c90, setup_tables_done_option=0) at /home/midenok/src/mariadb/trunk/src/sql/sql_select.cc:368
#46 0x000000000075214f in execute_sqlcom_select (thd=0x7fff80000d50, all_tables=0x7fff80013af0) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:6532
#47 0x0000000000746fb6 in mysql_execute_command (thd=0x7fff80000d50) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:3749
#48 0x0000000000741b9f in mysql_parse (thd=0x7fff80000d50, rawbuf=0x7fff80013878 "select * from t1 where t = '00:00:00' and i > 0 and sys_trx_end <> '2012-12-12 00:00:00'", length=88, parser_state=0x7fffe526d650, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:7988
```
```
(gdb) f 4
#4  0x0000000000e85917 in que_thr_stop_for_mysql_no_error (thr=0x33603d0, trx=0x7fffef913508) at /home/midenok/src/mariadb/trunk/src/storage/innobase/que/que0que.cc:865
865             ut_ad(trx->lock.n_active_thrs == 1);
(gdb) p trx->lock.n_active_thrs
$1 = 2
```

**Comment by midenok** [comment]
### 1. `n_active_thrs` increased from 0 to 1
```c++
#0  que_thr_move_to_run_state_for_mysql (thr=0x7fff8002ce30, trx=0x7fffef913508) at /home/midenok/src/mariadb/trunk/src/storage/innobase/que/que0que.cc:848
#1  0x0000000000f34ccf in row_search_mvcc (buf=0x7fff80026dc8 "\377", mode=PAGE_CUR_G, prebuilt=0x7fff8002c658, match_mode=0, direction=0) at /home/midenok/src/mariadb/trunk/src/storage/innobase/row/row0sel.cc:4494
#2  0x0000000000d48514 in ha_innobase::index_read (this=0x7fff8002aec8, buf=0x7fff80026dc8 "\377", key_ptr=0x7fff80037a48 "", key_len=5, find_flag=HA_READ_AFTER_KEY) at /home/midenok/src/mariadb/trunk/src/storage/innobase/handler/ha_innodb.cc:9687
#3  0x0000000000aa88eb in handler::index_read_map (this=0x7fff8002aec8, buf=0x7fff80026dc8 "\377", key=0x7fff80037a48 "", keypart_map=1, find_flag=HA_READ_AFTER_KEY) at /home/midenok/src/mariadb/trunk/src/sql/handler.h:3399
#4  0x0000000000a96f81 in handler::ha_index_read_map (this=0x7fff8002aec8, buf=0x7fff80026dc8 "\377", key=0x7fff80037a48 "", keypart_map=1, find_flag=HA_READ_AFTER_KEY) at /home/midenok/src/mariadb/trunk/src/sql/handler.cc:2676
#5  0x0000000000aa0008 in handler::read_range_first (this=0x7fff8002aec8, start_key=0x7fff8002afb0, end_key=0x0, eq_range_arg=false, sorted=true) at /home/midenok/src/mariadb/trunk/src/sql/handler.cc:5453
#6  0x0000000000939687 in handler::multi_range_read_next (this=0x7fff8002aec8, range_info=0x7fffe52690c8) at /home/midenok/src/mariadb/trunk/src/sql/multi_range_read.cc:286
#7  0x0000000000939879 in Mrr_simple_index_reader::get_next (this=0x7fff8002b450, range_info=0x7fffe52690c8) at /home/midenok/src/mariadb/trunk/src/sql/multi_range_read.cc:323
#8  0x000000000093cb50 in DsMrr_impl::dsmrr_next (this=0x7fff8002b310, range_info=0x7fffe52690c8) at /home/midenok/src/mariadb/trunk/src/sql/multi_range_read.cc:1399
#9  0x0000000000d5be3f in ha_innobase::multi_range_read_next (this=0x7fff8002aec8, range_info=0x7fffe52690c8) at /home/midenok/src/mariadb/trunk/src/storage/innobase/handler/ha_innodb.cc:21414
#10 0x0000000000c5ca70 in QUICK_RANGE_SELECT::get_next (this=0x7fff800377c0) at /home/midenok/src/mariadb/trunk/src/sql/opt_range.cc:11444
#11 0x0000000000c75810 in rr_quick (info=0x7fff80017908) at /home/midenok/src/mariadb/trunk/src/sql/records.cc:366
#12 0x000000000069b3cb in READ_RECORD::read_record (this=0x7fff80017908) at /home/midenok/src/mariadb/trunk/src/sql/records.h:73
#13 0x00000000007b777c in join_init_read_record (tab=0x7fff80017840) at /home/midenok/src/mariadb/trunk/src/sql/sql_select.cc:20401
#14 0x00000000007d325a in sub_select (join=0x7fff80014cb0, join_tab=0x7fff80017840, end_of_records=false) at /home/midenok/src/mariadb/trunk/src/sql/sql_select.cc:19475
#15 0x00000000007bb698 in do_select (join=0x7fff80014cb0, procedure=0x0) at /home/midenok/src/mariadb/trunk/src/sql/sql_select.cc:19018
#16 0x00000000007ba479 in JOIN::exec_inner (this=0x7fff80014cb0) at /home/midenok/src/mariadb/trunk/src/sql/sql_select.cc:4056
#17 0x00000000007b93ae in JOIN::exec (this=0x7fff80014cb0) at /home/midenok/src/mariadb/trunk/src/sql/sql_select.cc:3839
#18 0x000000000079105c in mysql_select (thd=0x7fff80000d50, tables=0x7fff80013af0, wild_num=1, fields=..., conds=0x7fff80014768, og_num=0, order=0x0, group=0x0, having=0x0, proc_param=0x0, select_options=2147748608, result=0x7fff80014c90, unit=0x7fff80004ad0, select_lex=0x7fff80005230) at /home/midenok/src/mariadb/trunk/src/sql/sql_select.cc:4251
#19 0x00000000007908b3 in handle_select (thd=0x7fff80000d50, lex=0x7fff80004a08, result=0x7fff80014c90, setup_tables_done_option=0) at /home/midenok/src/mariadb/trunk/src/sql/sql_select.cc:368
#20 0x000000000075214f in execute_sqlcom_select (thd=0x7fff80000d50, all_tables=0x7fff80013af0) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:6532
#21 0x0000000000746fb6 in mysql_execute_command (thd=0x7fff80000d50) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:3749
#22 0x0000000000741b9f in mysql_parse (thd=0x7fff80000d50, rawbuf=0x7fff80013878 "select * from t1 where t = '00:00:00' and i > 0 and sys_trx_end <> '2012-12-12 00:00:00'", length=88, parser_state=0x7fffe526d650, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:7988
```
### 2. trx started
```c++
#0  trx_start_low (trx=0x7fffef913508, read_write=false) at /home/midenok/src/mariadb/trunk/src/storage/innobase/trx/trx0trx.cc:1196
#1  0x0000000000ff4c50 in trx_start_if_not_started_low (trx=0x7fffef913508, read_write=false) at /home/midenok/src/mariadb/trunk/src/storage/innobase/trx/trx0trx.cc:2947
#2  0x0000000000f34ede in row_search_mvcc (buf=0x7fff80026dc8 "\377", mode=PAGE_CUR_G, prebuilt=0x7fff8002c658, match_mode=0, direction=0) at /home/midenok/src/mariadb/trunk/src/storage/innobase/row/row0sel.cc:4521
```
### 3. TRT query called
```c++
#0  row_search_mvcc (buf=0x33411f8 "\377", mode=PAGE_CUR_G, prebuilt=0x3343238, match_mode=0, direction=0) at /home/midenok/src/mariadb/trunk/src/storage/innobase/row/row0sel.cc:4138
#1  0x0000000000d48514 in ha_innobase::index_read (this=0x33409e8, buf=0x33411f8 "\377", key_ptr=0x0, key_len=0, find_flag=HA_READ_AFTER_KEY) at /home/midenok/src/mariadb/trunk/src/storage/innobase/handler/ha_innodb.cc:9687
#2  0x0000000000d491cb in ha_innobase::index_first (this=0x33409e8, buf=0x33411f8 "\377") at /home/midenok/src/mariadb/trunk/src/storage/innobase/handler/ha_innodb.cc:10126
#3  0x0000000000d49513 in ha_innobase::rnd_next (this=0x33409e8, buf=0x33411f8 "\377") at /home/midenok/src/mariadb/trunk/src/storage/innobase/handler/ha_innodb.cc:10222
#4  0x0000000000a96765 in handler::ha_rnd_next (this=0x33409e8, buf=0x33411f8 "\377") at /home/midenok/src/mariadb/trunk/src/sql/handler.cc:2626
#5  0x0000000000c759f4 in rr_sequential (info=0x7fffe5266698) at /home/midenok/src/mariadb/trunk/src/sql/records.cc:485
#6  0x000000000069b3cb in READ_RECORD::read_record (this=0x7fffe5266698) at /home/midenok/src/mariadb/trunk/src/sql/records.h:73
#7  0x000000000089d2f5 in TR_table::query (this=0x7fffe52667e8, trx_id=14601) at /home/midenok/src/mariadb/trunk/src/sql/table.cc:8663
#8  0x0000000000a4e124 in Field_vers_trx_id::get_date (this=0x7fff8002b7e0, ltime=0x7fffe5266f90, fuzzydate=33554433, trx_id=14601) at /home/midenok/src/mariadb/trunk/src/sql/field.cc:2016
#9  0x0000000000a7d4bf in Field_vers_trx_id::get_date (this=0x7fff8002b7e0, ltime=0x7fffe5266f90, fuzzydate=33554433) at /home/midenok/src/mariadb/trunk/src/sql/field.h:2204
#10 0x0000000000ab8adc in Item_field::get_date (this=0x7fff800148a8, ltime=0x7fffe5266f90, fuzzydate=33554433) at /home/midenok/src/mariadb/trunk/src/sql/item.cc:3390
#11 0x0000000000aacce2 in Item::get_date_with_conversion (this=0x7fff800148a8, ltime=0x7fffe5266f90, fuzzydate=33554433) at /home/midenok/src/mariadb/trunk/src/sql/item.cc:149
#12 0x0000000000638125 in Item::val_datetime_packed (this=0x7fff800148a8) at /home/midenok/src/mariadb/trunk/src/sql/item.h:1415
#13 0x0000000000ae1b36 in Arg_comparator::compare_datetime (this=0x7fff80014b28) at /home/midenok/src/mariadb/trunk/src/sql/item_cmpfunc.cc:795
#14 0x0000000000af95f2 in Arg_comparator::compare (this=0x7fff80014b28) at /home/midenok/src/mariadb/trunk/src/sql/item_cmpfunc.h:102
#15 0x0000000000ae52e5 in Item_func_ne::val_int (this=0x7fff80014a68) at /home/midenok/src/mariadb/trunk/src/sql/item_cmpfunc.cc:1773
#16 0x0000000000975de8 in Type_handler_int_result::Item_val_bool (this=0x2033d98 <type_handler_long>, item=0x7fff80014a68) at /home/midenok/src/mariadb/trunk/src/sql/sql_type.cc:3199
#17 0x0000000000637b75 in Item::val_bool (this=0x7fff80014a68) at /home/midenok/src/mariadb/trunk/src/sql/item.h:1122
#18 0x0000000000af169a in Item_cond_and::val_int (this=0x7fff80018748) at /home/midenok/src/mariadb/trunk/src/sql/item_cmpfunc.cc:5001
#19 0x0000000000aa0537 in handler_index_cond_check (h_arg=0x7fff8002aec8) at /home/midenok/src/mariadb/trunk/src/sql/handler.cc:5598
#20 0x0000000000d5c025 in innobase_index_cond (file=0x7fff8002aec8) at /home/midenok/src/mariadb/trunk/src/storage/innobase/handler/ha_innodb.cc:21475
#21 0x0000000000f3a550 in row_search_idx_cond_check (mysql_rec=0x7fff80026dc8 "\375\001", prebuilt=0x7fff8002c658, rec=0x7fffe7e540aa "\200", offsets=0x7fffe52682a0) at /home/midenok/src/mariadb/trunk/src/storage/innobase/row/row0sel.cc:4010
#22 0x0000000000f377f5 in row_search_mvcc (buf=0x7fff80026dc8 "\375\001", mode=PAGE_CUR_G, prebuilt=0x7fff8002c658, match_mode=0, direction=0) at /home/midenok/src/mariadb/trunk/src/storage/innobase/row/row0sel.cc:5230
```
### Cause
`row_search_mvcc()` is called from `row_search_mvcc()`.

**Comment by midenok** [comment]
### Fix
```diff
--- a/storage/innobase/row/row0sel.cc
+++ b/storage/innobase/row/row0sel.cc
@@ -5736,7 +5736,14 @@ row_search_mvcc(
 
 normal_return:
        /*-------------------------------------------------------------*/
-       que_thr_stop_for_mysql_no_error(thr, trx);
+       {
+               /* handler_index_cond_check() may pull TR_table search
+                  which initates another row_search_mvcc(). */
+               ulint n_active_thrs= trx->lock.n_active_thrs;
+               trx->lock.n_active_thrs= 1;
+               que_thr_stop_for_mysql_no_error(thr, trx);
+               trx->lock.n_active_thrs= n_active_thrs - 1;
+       }
 
        mtr_commit(&mtr);
```
