### ISSUE TITLE
Merge VERS_HIDDEN_FLAG and field_visibility

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#409]
Both `field_visibility` and `VERS_HIDDEN_FLAG` exist now independently.

`VERS_HIDDEN_FLAG` should be replaced with `SYSTEM_INVISIBLE` (or `COMPLETELY_INVISIBLE`?).

**Comment by midenok** [comment]
## cte.test
### breaks.gdb
```
logging
shell rm ~/bad.log

break item_cmpfunc.cc:800
  commands
    eval "shell echo '\n0x%x (%s)' >> ~/bad.log", ((Item_field *)(*a))->field, ((Item_field *)(*a))->field->field_name.str
    eval "shell unpack-datetime %lu >> ~/bad.log", val1
    eval "shell unpack-datetime %lu >> ~/bad.log", val2
    c
  end
c
```
### Field constructed
```c++
#0  Field::Field (this=0x7fff800ad5d8, ptr_arg=0x0, length_arg=26, null_ptr_arg=0x0, null_bit_arg=0 '\000', unireg_check_arg=Field::NONE, field_name_arg=0x7fff800a3ec0) at /home/midenok/src/mariadb/review/src/sql/field.cc:1615
#1  0x0000000000986905 in Field_temporal::Field_temporal (this=0x7fff800ad5d8, ptr_arg=0x0, len_arg=26, null_ptr_arg=0x0, null_bit_arg=0 '\000', unireg_check_arg=Field::NONE, field_name_arg=0x7fff800a3ec0) at /home/midenok/src/mariadb/review/src/sql/field.h:2393
#2  0x0000000000a5cead in Field_timestamp::Field_timestamp (this=0x7fff800ad5d8, ptr_arg=0x0, len_arg=26, null_ptr_arg=0x0, null_bit_arg=0 '\000', unireg_check_arg=Field::NONE, field_name_arg=0x7fff800a3ec0, share=0x7fff800ac450) at /home/midenok/src/mariadb/review/src/sql/field.cc:4913
#3  0x00000000008cb59a in Field_timestamp_with_dec::Field_timestamp_with_dec (this=0x7fff800ad5d8, ptr_arg=0x0, null_ptr_arg=0x0, null_bit_arg=0 '\000', unireg_check_arg=Field::NONE, field_name_arg=0x7fff800a3ec0, share=0x7fff800ac450, dec_arg=6) at /home/midenok/src/mariadb/review/src/sql/field.h:2564
#4  0x000000000098676e in Field_timestamp_hires::Field_timestamp_hires (this=0x7fff800ad5d8, ptr_arg=0x0, null_ptr_arg=0x0, null_bit_arg=0 '\000', unireg_check_arg=Field::NONE, field_name_arg=0x7fff800a3ec0, share=0x7fff800ac450, dec_arg=6) at /home/midenok/src/mariadb/review/src/sql/field.h:2602
#5  0x0000000000970385 in new_Field_timestamp (root=0x7fff800ac370, ptr=0x0, null_ptr=0x0, null_bit=0 '\000', unireg_check=Field::NONE, field_name=0x7fff800a3ec0, share=0x7fff800ac450, dec=6) at /home/midenok/src/mariadb/review/src/sql/field.h:3104
#6  0x00000000009741fc in Type_handler_timestamp2::make_table_field (this=0x2034ed8 <type_handler_timestamp2>, name=0x7fff800a3ec0, addr=..., attr=..., table=0x7fff800ab8a8) at /home/midenok/src/mariadb/review/src/sql/sql_type.cc:2221
#7  0x00000000009731e8 in Type_handler::make_and_init_table_field (this=0x2034ed8 <type_handler_timestamp2>, name=0x7fff800a3ec0, addr=..., attr=..., table=0x7fff800ab8a8) at /home/midenok/src/mariadb/review/src/sql/sql_type.cc:1999
#8  0x0000000000adae9d in Item_type_holder::create_tmp_field (this=0x7fff800a3e70, group=false, table=0x7fff800ab8a8) at /home/midenok/src/mariadb/review/src/sql/item.h:6297
#9  0x00000000007cf966 in create_tmp_field (thd=0x7fff80000d50, table=0x7fff800ab8a8, item=0x7fff800a3e70, type=Item::TYPE_HOLDER, copy_func=0x7fffe52681f0, from_field=0x7fff800acb68, default_field=0x7fff800acb18, group=false, modify_item=false, table_cant_handle_bit_fields=false, make_copy_field=false) at /home/midenok/src/mariadb/review/src/sql/sql_select.cc:17066
#10 0x00000000007b0ca0 in create_tmp_table (thd=0x7fff80000d50, param=0x7fff8001ab18, fields=..., group=0x0, distinct=false, save_sum_fields=true, select_options=2416188160, rows_limit=18446744073709551615, table_alias=0x7fff80018b10 "a", do_not_open=true, keep_row_order=false) at /home/midenok/src/mariadb/review/src/sql/sql_select.cc:17574
#11 0x0000000000868adc in select_union_recursive::create_result_table (this=0x7fff8001aae0, thd_arg=0x7fff80000d50, column_types=0x7fff80016880, is_union_distinct=true, options=2416188160, alias=0x7fff80018b10 "a", bit_fields_as_long=false, create_table=true, keep_row_order=false, hidden=0) at /home/midenok/src/mariadb/review/src/sql/sql_union.cc:430
#12 0x0000000000864eba in st_select_lex_unit::prepare (this=0x7fff800161b8, thd_arg=0x7fff80000d50, sel_result=0x7fff8001a9f8, additional_options=0) at /home/midenok/src/mariadb/review/src/sql/sql_union.cc:1010
#13 0x00000000006fa035 in mysql_derived_prepare (thd=0x7fff80000d50, lex=0x7fff80004a18, derived=0x7fff80018b28) at /home/midenok/src/mariadb/review/src/sql/sql_derived.cc:865
#14 0x00000000006fc8c7 in mysql_handle_single_derived (lex=0x7fff80004a18, derived=0x7fff80018b28, phases=2) at /home/midenok/src/mariadb/review/src/sql/sql_derived.cc:197
#15 0x000000000089c5af in TABLE_LIST::handle_derived (this=0x7fff80018b28, lex=0x7fff80004a18, phases=2) at /home/midenok/src/mariadb/review/src/sql/table.cc:8083
#16 0x0000000000723293 in st_select_lex::handle_derived (this=0x7fff80017760, lex=0x7fff80004a18, phases=2) at /home/midenok/src/mariadb/review/src/sql/sql_lex.cc:4038
#17 0x000000000089c536 in TABLE_LIST::handle_derived (this=0x7fff80019908, lex=0x7fff80004a18, phases=2) at /home/midenok/src/mariadb/review/src/sql/table.cc:8080
#18 0x0000000000723293 in st_select_lex::handle_derived (this=0x7fff80005240, lex=0x7fff80004a18, phases=2) at /home/midenok/src/mariadb/review/src/sql/sql_lex.cc:4038
#19 0x0000000000794e12 in JOIN::prepare (this=0x7fff8001a040, tables_init=0x7fff80019908, wild_num=1, conds_init=0x0, og_num=0, order_init=0x0, skip_order_by=false, group_init=0x0, having_init=0x0, proc_param_init=0x0, select_lex_arg=0x7fff80005240, unit_arg=0x7fff80004ae0) at /home/midenok/src/mariadb/review/src/sql/sql_select.cc:1155
#20 0x0000000000790ec9 in mysql_select (thd=0x7fff80000d50, tables=0x7fff80019908, wild_num=1, fields=..., conds=0x0, og_num=0, order=0x0, group=0x0, having=0x0, proc_param=0x0, select_options=2147748608, result=0x7fff8001a020, unit=0x7fff80004ae0, select_lex=0x7fff80005240) at /home/midenok/src/mariadb/review/src/sql/sql_select.cc:4258
#21 0x0000000000790843 in handle_select (thd=0x7fff80000d50, lex=0x7fff80004a18, result=0x7fff8001a020, setup_tables_done_option=0) at /home/midenok/src/mariadb/review/src/sql/sql_select.cc:368
#22 0x00000000007520df in execute_sqlcom_select (thd=0x7fff80000d50, all_tables=0x7fff80019908) at /home/midenok/src/mariadb/review/src/sql/sql_parse.cc:6532
#23 0x0000000000746f46 in mysql_execute_command (thd=0x7fff80000d50) at /home/midenok/src/mariadb/review/src/sql/sql_parse.cc:3749
#24 0x0000000000741b2f in mysql_parse (thd=0x7fff80000d50, rawbuf=0x7fff80015a48 "with recursive ancestors as (   select e.emp_id, e.name, e.mgr, e.salary   from emp as e   where name = 'bill'   union   select e.emp_id, e.name, e.mgr, e.salary   from emp as e,        ancestors as a   where e.mgr = a.emp_id ) select * from ancestors for system_time as of timestamp @ts_1", length=289, parser_state=0x7fffe526d650, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/review/src/sql/sql_parse.cc:7988
```
### Field gets value
```c++
#4  0x000000000089c0df in TABLE::insert_all_rows_into_tmp_table (this=0x7fff800a80e8, thd=0x7fff80000d50, tmp_table=0x7fff800aa248, tmp_table_param=0x7fff8001ab18, with_cleanup=true) at /home/midenok/src/mariadb/review/src/sql/table.cc:7997
#5  0x000000000086b318 in st_select_lex_unit::exec_recursive (this=0x7fff800161b8) at /home/midenok/src/mariadb/review/src/sql/sql_union.cc:1700
#6  0x00000000006fcab5 in TABLE_LIST::fill_recursive (this=0x7fff80019908, thd=0x7fff80000d50) at /home/midenok/src/mariadb/review/src/sql/sql_derived.cc:1127
#7  0x00000000006fbde1 in mysql_derived_fill (thd=0x7fff80000d50, lex=0x7fff80004a18, derived=0x7fff80019908) at /home/midenok/src/mariadb/review/src/sql/sql_derived.cc:1207
#8  0x00000000006fc8c7 in mysql_handle_single_derived (lex=0x7fff80004a18, derived=0x7fff80019908, phases=96) at /home/midenok/src/mariadb/review/src/sql/sql_derived.cc:197
#9  0x00000000007c8dc0 in st_join_table::preread_init (this=0x7fff800b89b8) at /home/midenok/src/mariadb/review/src/sql/sql_select.cc:12729
#10 0x00000000007d3357 in sub_select (join=0x7fff8001a040, join_tab=0x7fff800b89b8, end_of_records=false) at /home/midenok/src/mariadb/review/src/sql/sql_select.cc:19491
#11 0x00000000007bb918 in do_select (join=0x7fff8001a040, procedure=0x0) at /home/midenok/src/mariadb/review/src/sql/sql_select.cc:19063
#12 0x00000000007ba6f9 in JOIN::exec_inner (this=0x7fff8001a040) at /home/midenok/src/mariadb/review/src/sql/sql_select.cc:4085
#13 0x00000000007b962e in JOIN::exec (this=0x7fff8001a040) at /home/midenok/src/mariadb/review/src/sql/sql_select.cc:3868
#14 0x0000000000790fec in mysql_select (thd=0x7fff80000d50, tables=0x7fff80019908, wild_num=1, fields=..., conds=0x0, og_num=0, order=0x0, group=0x0, having=0x0, proc_param=0x0, select_options=2147748608, result=0x7fff8001a020, unit=0x7fff80004ae0, select_lex=0x7fff80005240) at /home/midenok/src/mariadb/review/src/sql/sql_select.cc:4280
#15 0x0000000000790843 in handle_select (thd=0x7fff80000d50, lex=0x7fff80004a18, result=0x7fff8001a020, setup_tables_done_option=0) at /home/midenok/src/mariadb/review/src/sql/sql_select.cc:368
#16 0x00000000007520df in execute_sqlcom_select (thd=0x7fff80000d50, all_tables=0x7fff80019908) at /home/midenok/src/mariadb/review/src/sql/sql_parse.cc:6532
#17 0x0000000000746f46 in mysql_execute_command (thd=0x7fff80000d50) at /home/midenok/src/mariadb/review/src/sql/sql_parse.cc:3749
#18 0x0000000000741b2f in mysql_parse (thd=0x7fff80000d50, rawbuf=0x7fff80015a48 "with recursive ancestors as (   select e.emp_id, e.name, e.mgr, e.salary   from emp as e   where name = 'bill'   union   select e.emp_id, e.name, e.mgr, e.salary   from emp as e,        ancestors as a   where e.mgr = a.emp_id ) select * from ancestors for system_time as of timestamp @ts_1", length=289, parser_state=0x7fffe526d650, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/review/src/sql/sql_parse.cc:7988
```
### Fix
```diff
--- a/sql/sql_base.cc
+++ b/sql/sql_base.cc
@@ -8313,8 +8313,7 @@ fill_record(THD *thd, TABLE *table, Field **ptr, List<Item> &values,
       goto err;
     }
 
-    if (field->invisible &&
-      !(vers_sys_field && thd->lex->sql_command == SQLCOM_CREATE_TABLE))
+    if (field->invisible && !vers_sys_field)
     {
       continue;
```

**Comment by midenok** [comment]
```
break Field::Field
  commands
    bt
    c
  end
disable $bpnum
break sql_select.cc:17598
  condition $bpnum 0 == strcmp(new_field->field_name.str, "sys_trx_end")
  commands
    p new_field
    p new_field->field_name.str
    watch -l new_field->ptr
    set $b = $bpnum
    commands
        bc $b
        watch -l *ptr
        c
    end
    bd $a
    c
  end
set $a = $bpnum
ign 2
break item_cmpfunc.cc:800
  commands
    p ((Item_field *)(*a))->field
  end
disable $bpnum
```

**Comment by midenok** [comment]
### Fix
```diff
--- a/sql/sql_base.cc
+++ b/sql/sql_base.cc
@@ -8313,8 +8313,7 @@ fill_record(THD *thd, TABLE *table, Field **ptr, List<Item> &values,
       goto err;
     }
 
-    if (field->invisible &&
-      !(vers_sys_field && thd->lex->sql_command == SQLCOM_CREATE_TABLE))
+    if (field->invisible && !vers_sys_field)
     {
       continue;
```

**Comment by midenok** [comment]
```
break Field::Field
  commands
    bt
    c
  end
disable $bpnum
break sql_select.cc:17598
  condition $bpnum 0 == strcmp(new_field->field_name.str, "sys_trx_end")
  commands
    p new_field
    p new_field->field_name.str
    watch -l new_field->ptr
    set $b = $bpnum
    commands
        bc $b
        watch -l *ptr
        c
    end
    bd $a
    c
  end
set $a = $bpnum
ign 2
break item_cmpfunc.cc:800
  commands
    p ((Item_field *)(*a))->field
  end
disable $bpnum
```
