### ISSUE TITLE
IB: TRX_ID based operations inside transaction generate history

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#472]
### Reproduce
```sql
create or replace table t1 (
  x int,
  sys_start bigint unsigned as row start invisible,
  sys_end bigint unsigned as row end invisible,
  period for system_time (row_start, row_end)
) engine innodb with system versioning;
begin;
insert into t1 values (1);
delete from t1;
commit;
```
### Result
History record is generated with `row_start` == `row_end`.
### Expected
No record is generated.

**Comment by midenok** [comment]
### Columns marked for read on DELETE
```c++
#0  bitmap_set_bit (map=0x7fff7c02c9b0, bit=2) at /home/midenok/src/mariadb/trunk/src/include/my_bitmap.h:117
#1  0x00000000008cdae8 in TABLE::mark_columns_needed_for_delete (this=0x7fff7c02c880) at /home/midenok/src/mariadb/trunk/src/sql/table.cc:6424
#2  0x0000000000cf1f88 in mysql_delete (thd=0x7fff7c000d50, table_list=0x7fff7c0139a0, conds=0x0, order_list=0x7fff7c0054d8, limit=18446744073709551615, options=0, result=0x0) at /home/midenok/src/mariadb/trunk/src/sql/sql_delete.cc:667
#3  0x00000000007806a8 in mysql_execute_command (thd=0x7fff7c000d50) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:4899
#4  0x0000000000777463 in mysql_parse (thd=0x7fff7c000d50, rawbuf=0x7fff7c0138d8 "delete from t1", length=14, parser_state=0x7fffe52ae640, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:7980
```
```c++
6419      /*
6420         For System Versioning we have to write and read Sys_end.
6421      */
6422      if (s->versioned)
6423      {
6424        bitmap_set_bit(read_set, s->vers_end_field()->field_index);
6425        bitmap_set_bit(write_set, s->vers_end_field()->field_index);
6426      }
```
