### ISSUE TITLE
Implement show create table for versioned tables

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#5]
<a href="https://github.com/hagrid-the-developer"><img src="https://avatars.githubusercontent.com/u/2307024?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [hagrid-the-developer](https://github.com/hagrid-the-developer)**
_Monday Sep 05, 2016 at 08:42 GMT_
_Originally opened as https://github.com/natsys/mariadb/issues/4_

---

Show create table doesn't work for system versioned tables:

```
> CREATE TABLE t1(id INT UNSIGNED AUTO INCREMENT, x INT UNSIGNED, y INT UNSIGNED, Sys_start TIMESTAMP(6) GENERATED ALWAYS AS ROW START, Sys_end TIMESTAMP(6) GENERATED ALWAYS AS ROW END, PERIOD FOR SYSTEM_TIME (Sys_start, Sys_end)) WITH SYSTEM VERSIONING;
> SHOW CREATE TABLE t1;

+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| t1    | CREATE TABLE `t1` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `x` int(10) unsigned DEFAULT NULL,
  `y` int(10) unsigned DEFAULT NULL,
  `Sys_start` timestamp(6) NOT NULL DEFAULT '0000-00-00 00:00:00.000000',
  `Sys_end` timestamp(6) NOT NULL DEFAULT '0000-00-00 00:00:00.000000',
  PRIMARY KEY (`id`,`Sys_end`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 |
```

Please note: Additional column in PRIMARY KEY is ok, it is necessary to preserve uniqueness of the key.

**Comment by midenok** [comment]
```
#0  append_identifier (thd=0x7ff10dc16070, packet=0x7ff1376b96e0, name=0x7ff10dc97565 "t1", length=0x2) at /home/midenok/src/mariadb/hagrid/src/sql/sql_show.cc:1466
#1  0x0000000000720196 in show_create_table (thd=0x7ff10dc16070, table_list=0x7ff10dc5e160, packet=0x7ff1376b96e0, create_info_arg=0x0, with_db_name=WITHOUT_DB_NAME) at /home/midenok/src/mariadb/hagrid/src/sql/sql_show.cc:1838
#2  0x000000000071e011 in mysqld_show_create_get_fields (thd=0x7ff10dc16070, table_list=0x7ff10dc5e160, field_list=0x7ff1376b96c0, buffer=0x7ff1376b96e0) at /home/midenok/src/mariadb/hagrid/src/sql/sql_show.cc:1154
#3  0x000000000071e44e in mysqld_show_create (thd=0x7ff10dc16070, table_list=0x7ff10dc5e160) at /home/midenok/src/mariadb/hagrid/src/sql/sql_show.cc:1227
#4  0x00000000006931fd in mysql_execute_command (thd=0x7ff10dc16070) at /home/midenok/src/mariadb/hagrid/src/sql/sql_parse.cc:4094
#5  0x000000000069f205 in mysql_parse (thd=0x7ff10dc16070, rawbuf=0x7ff10dc5e088 "show create table t1", length=0x14, parser_state=0x7ff1376baf70, is_com_multi=0x0, is_next_command=0x0) at /home/midenok/src/mariadb/hagrid/src/sql/sql_parse.cc:7789
```
