### ISSUE TITLE
saved_where does not provide idempotency on INNER JOIN inside SP

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#52]
``` sql
delimiter ~~
create or replace procedure creat(
  sys_type varchar(255),
  engine varchar(255),
  fields varchar(255))
begin
  set @str0= concat('(
    x int,
    y int,
    sys_start ', sys_type, ' generated always as row start,
    sys_end ', sys_type, ' generated always as row end,
    period for system_time (sys_start, sys_end))
  with system versioning
  engine ', engine);
  set @str= concat('create or replace table t1', @str0);
  prepare stmt from @str; execute stmt; drop prepare stmt;
  set @str= concat('create or replace table t2', @str0);
  prepare stmt from @str; execute stmt; drop prepare stmt;

  insert into t1 values (1, 1), (1, 2), (1, 3), (4, 4), (5, 5);
  insert into t2 values (1, 2), (2, 1), (3, 1);
end~~

create or replace procedure test()
begin
  select t1.x as IJ1_x1, t1.y as y1, t2.x as x2, t2.y as y2 from t1 inner join t2 on t1.x = t2.x where t1.y > 1 and t2.y = 2;
end~~

create or replace procedure test2() modifies sql data
begin
  select t1.x as x1, t1.y as y1, t2.x as x2, t2.y as y2 from t1, t2 where t1.y > 1 and t2.y = 2;
end~~
delimiter ;
```

```
MariaDB [test]> call test;
+--------+------+------+------+
| IJ1_x1 | y1   | x2   | y2   |
+--------+------+------+------+
|      1 |    2 |    1 |    2 |
|      1 |    3 |    1 |    2 |
+--------+------+------+------+
2 rows in set (0.01 sec)

Query OK, 0 rows affected (0.01 sec)

MariaDB [test]> call test;
+--------+------+------+------+
| IJ1_x1 | y1   | x2   | y2   |
+--------+------+------+------+
|      1 |    2 |    1 |    2 |
|      1 |    3 |    1 |    2 |
+--------+------+------+------+
2 rows in set (0.00 sec)

Query OK, 0 rows affected (0.00 sec)

MariaDB [test]> call test;
+--------+------+------+------+
| IJ1_x1 | y1   | x2   | y2   |
+--------+------+------+------+
|      1 |    1 |    1 |    2 |
|      1 |    2 |    1 |    2 |
|      1 |    3 |    1 |    2 |
+--------+------+------+------+
3 rows in set (0.00 sec)

Query OK, 0 rows affected (0.00 sec)

MariaDB [test]> call test2;
+------+------+------+------+
| x1   | y1   | x2   | y2   |
+------+------+------+------+
|    1 |    2 |    1 |    2 |
|    1 |    3 |    1 |    2 |
|    4 |    4 |    1 |    2 |
|    5 |    5 |    1 |    2 |
+------+------+------+------+
4 rows in set (0.00 sec)

Query OK, 0 rows affected (0.00 sec)

MariaDB [test]> call test2;
+------+------+------+------+
| x1   | y1   | x2   | y2   |
+------+------+------+------+
|    1 |    2 |    1 |    2 |
|    1 |    3 |    1 |    2 |
|    4 |    4 |    1 |    2 |
|    5 |    5 |    1 |    2 |
+------+------+------+------+
4 rows in set (0.00 sec)

Query OK, 0 rows affected (0.00 sec)

MariaDB [test]> call test2;
+------+------+------+------+
| x1   | y1   | x2   | y2   |
+------+------+------+------+
|    1 |    1 |    1 |    2 |
|    1 |    1 |    2 |    1 |
|    1 |    1 |    3 |    1 |
|    1 |    2 |    1 |    2 |
|    1 |    2 |    2 |    1 |
|    1 |    2 |    3 |    1 |
|    1 |    3 |    1 |    2 |
|    1 |    3 |    2 |    1 |
|    1 |    3 |    3 |    1 |
|    4 |    4 |    1 |    2 |
|    4 |    4 |    2 |    1 |
|    4 |    4 |    3 |    1 |
|    5 |    5 |    1 |    2 |
|    5 |    5 |    2 |    1 |
|    5 |    5 |    3 |    1 |
+------+------+------+------+
15 rows in set (0.00 sec)

Query OK, 0 rows affected (0.00 sec)
```

Recovery of `saved_where` have no effect on third execution of SP. Though it works good when there is no INNER JOIN.

**Comment by midenok** [comment]
### 1. `saved_where` set (STMT_INITIALIZED_FOR_SP)

```
#0  setup_for_system_time (thd=0x7fffcfc16070, tables=0x7fffcfc6a4d8, where_expr=0x7fffcfd6a648, select_lex=0x7fffcfc93880) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:718
#1  0x00000000006d051c in JOIN::prepare (this=0x7fffcfd6a250, tables_init=0x7fffcfc6a4d8, wild_num=0x0, conds_init=0x7fffcfc94d68, og_num=0x0, order_init=0x0, skip_order_by=0x0, group_init=0x0, having_init=0x0, proc_param_init=0x0, select_lex_arg=0x7fffcfc93880, unit_arg=0x7fffcfc93150) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:916
#2  0x00000000006da143 in mysql_select (thd=0x7fffcfc16070, tables=0x7fffcfc6a4d8, wild_num=0x0, fields=..., conds=0x7fffcfc94d68, og_num=0x0, order=0x0, group=0x0, having=0x0, proc_param=0x0, select_options=0x80040f00, result=0x7fffcfd6a230, unit=0x7fffcfc93150, select_lex=0x7fffcfc93880) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:3686
#3  0x00000000006ce848 in handle_select (thd=0x7fffcfc16070, lex=0x7fffcfc93088, result=0x7fffcfd6a230, setup_tables_done_option=0x0) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:378
#4  0x000000000069c432 in execute_sqlcom_select (thd=0x7fffcfc16070, all_tables=0x7fffcfc6a4d8) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:6317
#5  0x0000000000691e22 in mysql_execute_command (thd=0x7fffcfc16070) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:3351
#6  0x0000000000a417cc in sp_instr_stmt::exec_core (this=0x7fffcfc6aff8, thd=0x7fffcfc16070, nextp=0x7ffff7f7bb14) at /home/midenok/src/mariadb/midenok/src/sql/sp_head.cc:3218
#7  0x0000000000a40ebb in sp_lex_keeper::reset_lex_and_exec_core (this=0x7fffcfc6b040, thd=0x7fffcfc16070, nextp=0x7ffff7f7bb14, open_tables=0x0, instr=0x7fffcfc6aff8) at /home/midenok/src/mariadb/midenok/src/sql/sp_head.cc:2984
#8  0x0000000000a414b2 in sp_instr_stmt::execute (this=0x7fffcfc6aff8, thd=0x7fffcfc16070, nextp=0x7ffff7f7bb14) at /home/midenok/src/mariadb/midenok/src/sql/sp_head.cc:3134
#9  0x0000000000a3cb85 in sp_head::execute (this=0x7fffcfc69088, thd=0x7fffcfc16070, merge_da_on_success=0x1) at /home/midenok/src/mariadb/midenok/src/sql/sp_head.cc:1323
#10 0x0000000000a3ea38 in sp_head::execute_procedure (this=0x7fffcfc69088, thd=0x7fffcfc16070, args=0x7fffcfc1a7b8) at /home/midenok/src/mariadb/midenok/src/sql/sp_head.cc:2110
#11 0x000000000069054f in do_execute_sp (thd=0x7fffcfc16070, sp=0x7fffcfc69088) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:2792
#12 0x0000000000699a8a in mysql_execute_command (thd=0x7fffcfc16070) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:5671
#13 0x000000000069fcc5 in mysql_parse (thd=0x7fffcfc16070, rawbuf=0x7fffcfc5e088 "call test2", length=0xa, parser_state=0x7ffff7f7cf90, is_com_multi=0x0, is_next_command=0x0) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:7729
```

#### Result correct.

11 items

### 2. `saved_where` restored (STMT_EXECUTED)

```
#0  setup_for_system_time (thd=0x7fffcfc16070, tables=0x7fffcfc6a4d8, where_expr=0x7fffcfd917c0, select_lex=0x7fffcfc93880) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:709
#1  0x00000000006d051c in JOIN::prepare (this=0x7fffcfd913c8, tables_init=0x7fffcfc6a4d8, wild_num=0x0, conds_init=0x7fffcfd91148, og_num=0x0, order_init=0x0, skip_order_by=0x0, group_init=0x0, having_init=0x0, proc_param_init=0x0, select_lex_arg=0x7fffcfc93880, unit_arg=0x7fffcfc93150) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:916
#2  0x00000000006da143 in mysql_select (thd=0x7fffcfc16070, tables=0x7fffcfc6a4d8, wild_num=0x0, fields=..., conds=0x7fffcfd91148, og_num=0x0, order=0x0, group=0x0, having=0x0, proc_param=0x0, select_options=0x80040f00, result=0x7fffcfd913a8, unit=0x7fffcfc93150, select_lex=0x7fffcfc93880) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:3686
#3  0x00000000006ce848 in handle_select (thd=0x7fffcfc16070, lex=0x7fffcfc93088, result=0x7fffcfd913a8, setup_tables_done_option=0x0) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:378
#4  0x000000000069c432 in execute_sqlcom_select (thd=0x7fffcfc16070, all_tables=0x7fffcfc6a4d8) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:6317
#5  0x0000000000691e22 in mysql_execute_command (thd=0x7fffcfc16070) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:3351
#6  0x0000000000a417cc in sp_instr_stmt::exec_core (this=0x7fffcfc6aff8, thd=0x7fffcfc16070, nextp=0x7ffff7f7bb14) at /home/midenok/src/mariadb/midenok/src/sql/sp_head.cc:3218
#7  0x0000000000a40ebb in sp_lex_keeper::reset_lex_and_exec_core (this=0x7fffcfc6b040, thd=0x7fffcfc16070, nextp=0x7ffff7f7bb14, open_tables=0x0, instr=0x7fffcfc6aff8) at /home/midenok/src/mariadb/midenok/src/sql/sp_head.cc:2984
#8  0x0000000000a414b2 in sp_instr_stmt::execute (this=0x7fffcfc6aff8, thd=0x7fffcfc16070, nextp=0x7ffff7f7bb14) at /home/midenok/src/mariadb/midenok/src/sql/sp_head.cc:3134
#9  0x0000000000a3cb85 in sp_head::execute (this=0x7fffcfc69088, thd=0x7fffcfc16070, merge_da_on_success=0x1) at /home/midenok/src/mariadb/midenok/src/sql/sp_head.cc:1323
#10 0x0000000000a3ea38 in sp_head::execute_procedure (this=0x7fffcfc69088, thd=0x7fffcfc16070, args=0x7fffcfc1a7b8) at /home/midenok/src/mariadb/midenok/src/sql/sp_head.cc:2110
#11 0x000000000069054f in do_execute_sp (thd=0x7fffcfc16070, sp=0x7fffcfc69088) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:2792
#12 0x0000000000699a8a in mysql_execute_command (thd=0x7fffcfc16070) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:5671
#13 0x000000000069fcc5 in mysql_parse (thd=0x7fffcfc16070, rawbuf=0x7fffcfc5e088 "call test2", length=0xa, parser_state=0x7ffff7f7cf90, is_com_multi=0x0, is_next_command=0x0) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:7729
```

#### Result correct.

11 items

### 3. `saved_where` restored 2nd time (STMT_EXECUTED)

```
#0  setup_for_system_time (thd=0x7fffcfc16070, tables=0x7fffcfc6a4d8, where_expr=0x7fffcfd947c0, select_lex=0x7fffcfc93880) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:709
#1  0x00000000006d051c in JOIN::prepare (this=0x7fffcfd943c8, tables_init=0x7fffcfc6a4d8, wild_num=0x0, conds_init=0x7fffcfd94148, og_num=0x0, order_init=0x0, skip_order_by=0x0, group_init=0x0, having_init=0x0, proc_param_init=0x0, select_lex_arg=0x7fffcfc93880, unit_arg=0x7fffcfc93150) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:916
#2  0x00000000006da143 in mysql_select (thd=0x7fffcfc16070, tables=0x7fffcfc6a4d8, wild_num=0x0, fields=..., conds=0x7fffcfd94148, og_num=0x0, order=0x0, group=0x0, having=0x0, proc_param=0x0, select_options=0x80040f00, result=0x7fffcfd943a8, unit=0x7fffcfc93150, select_lex=0x7fffcfc93880) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:3686
#3  0x00000000006ce848 in handle_select (thd=0x7fffcfc16070, lex=0x7fffcfc93088, result=0x7fffcfd943a8, setup_tables_done_option=0x0) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:378
#4  0x000000000069c432 in execute_sqlcom_select (thd=0x7fffcfc16070, all_tables=0x7fffcfc6a4d8) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:6317
#5  0x0000000000691e22 in mysql_execute_command (thd=0x7fffcfc16070) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:3351
#6  0x0000000000a417cc in sp_instr_stmt::exec_core (this=0x7fffcfc6aff8, thd=0x7fffcfc16070, nextp=0x7ffff7f7bb14) at /home/midenok/src/mariadb/midenok/src/sql/sp_head.cc:3218
#7  0x0000000000a40ebb in sp_lex_keeper::reset_lex_and_exec_core (this=0x7fffcfc6b040, thd=0x7fffcfc16070, nextp=0x7ffff7f7bb14, open_tables=0x0, instr=0x7fffcfc6aff8) at /home/midenok/src/mariadb/midenok/src/sql/sp_head.cc:2984
#8  0x0000000000a414b2 in sp_instr_stmt::execute (this=0x7fffcfc6aff8, thd=0x7fffcfc16070, nextp=0x7ffff7f7bb14) at /home/midenok/src/mariadb/midenok/src/sql/sp_head.cc:3134
#9  0x0000000000a3cb85 in sp_head::execute (this=0x7fffcfc69088, thd=0x7fffcfc16070, merge_da_on_success=0x1) at /home/midenok/src/mariadb/midenok/src/sql/sp_head.cc:1323
#10 0x0000000000a3ea38 in sp_head::execute_procedure (this=0x7fffcfc69088, thd=0x7fffcfc16070, args=0x7fffcfc1a7b8) at /home/midenok/src/mariadb/midenok/src/sql/sp_head.cc:2110
#11 0x000000000069054f in do_execute_sp (thd=0x7fffcfc16070, sp=0x7fffcfc69088) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:2792
#12 0x0000000000699a8a in mysql_execute_command (thd=0x7fffcfc16070) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:5671
#13 0x000000000069fcc5 in mysql_parse (thd=0x7fffcfc16070, rawbuf=0x7fffcfc5e088 "call test2", length=0xa, parser_state=0x7ffff7f7cf90, is_com_multi=0x0, is_next_command=0x0) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:7729
```

#### Result incorrect!

11 items
