### ISSUE TITLE
MDEV-15990 REPLACE on a precise-versioned table returns duplicate key error (ER_DUP_ENTRY)

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#520]
### Reproduce
```sql
create or replace table t1 (pk int primary key,  i int, 
  s bigint unsigned as row start,
  e bigint unsigned as row end, period for system_time(s,e))
  engine=InnoDB with system versioning;
replace into t1 (pk,i) values (1,10),(1,100),(1,1000);
```
### Result
```
ERROR 1062 (23000): Duplicate entry '1-18446744073709551615' for key 'PRIMARY'
```
### Expected
No error.

**Comment by midenok** [comment]
### Error thrown
```c++
#0  Diagnostics_area::set_error_status (this=0x7fff800062a8, sql_errno=1062, message=0x7fffe4ecbc00 "Duplicate entry '1-18446744073709551615' for key 'PRIMARY'", sqlstate=0x14dc8c5 "23000", ucid=..., error_condition=0x0) at /home/midenok/src/mariadb/trunk/src/sql/sql_error.cc:438
#1  0x0000000000737261 in THD::raise_condition (this=0x7fff80000d50, sql_errno=1062, sqlstate=0x14dc8c5 "23000", level=Sql_state_errno_level::WARN_LEVEL_ERROR, ucid=..., msg=0x7fffe4ecbc00 "Duplicate entry '1-18446744073709551615' for key 'PRIMARY'") at /home/midenok/src/mariadb/trunk/src/sql/sql_class.cc:1149
#2  0x000000000065d8cd in THD::raise_condition (this=0x7fff80000d50, sql_errno=1062, sqlstate=0x0, level=Sql_state_errno_level::WARN_LEVEL_ERROR, msg=0x7fffe4ecbc00 "Duplicate entry '1-18446744073709551615' for key 'PRIMARY'") at /home/midenok/src/mariadb/trunk/src/sql/sql_class.h:4331
#3  0x0000000000649f10 in my_message_sql (error=1062, str=0x7fffe4ecbc00 "Duplicate entry '1-18446744073709551615' for key 'PRIMARY'", MyFlags=0) at /home/midenok/src/mariadb/trunk/src/sql/mysqld.cc:3680
#4  0x0000000001439b59 in my_printf_error (error=1062, format=0x28d7a45 "Duplicate entry '%-.64s' for key '%-.192s'", MyFlags=0) at /home/midenok/src/mariadb/trunk/src/mysys/my_error.c:154
#5  0x0000000000b136bb in print_keydup_error (table=0x7fff80070190, key=0x7fff800716e8, msg=0x28d7a45 "Duplicate entry '%-.64s' for key '%-.192s'", errflag=0) at /home/midenok/src/mariadb/trunk/src/sql/handler.cc:3523
#6  0x0000000000b1373e in print_keydup_error (table=0x7fff80070190, key=0x7fff800716e8, errflag=0) at /home/midenok/src/mariadb/trunk/src/sql/handler.cc:3537
#7  0x0000000000b13a11 in handler::print_error (this=0x7fff80070dd8, error=121, errflag=0) at /home/midenok/src/mariadb/trunk/src/sql/handler.cc:3614
#8  0x000000000076e97e in write_record (thd=0x7fff80000d50, table=0x7fff80070190, info=0x7fffe4ece458) at /home/midenok/src/mariadb/trunk/src/sql/sql_insert.cc:2052
#9  0x000000000076acd8 in mysql_insert (thd=0x7fff80000d50, table_list=0x7fff80013bd0, fields=..., values_list=..., update_fields=..., update_values=..., duplic=DUP_REPLACE, ignore=false) at /home/midenok/src/mariadb/trunk/src/sql/sql_insert.cc:1063
#10 0x00000000007baa73 in mysql_execute_command (thd=0x7fff80000d50) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:4720
#11 0x00000000007b23df in mysql_parse (thd=0x7fff80000d50, rawbuf=0x7fff80013ab8 "replace into t1 (pk,i) values (1,10),(1,100),(1,1000)", length=53, parser_state=0x7fffe4ed1650, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:8077
```
