### ISSUE TITLE
MDEV-17038 ALTER TABLE CHANGE COLUMN c1 c1 bigint NOT NULL - generates error if table uses SYSTEM VERSIONING

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#540]
### Reproduce
```sql
create or replace table t1 (a int, key(a)) with system versioning;
create or replace table t2 (b int, foreign key(b) references t1(a)) with system versioning;
alter table t2 modify column b int not null;
```
### Result
```c++
#0  my_error (nr=1832, MyFlags=0) at /home/midenok/src/mariadb/trunk/src/mysys/my_error.c:113
#1  0x00000000008bf113 in fk_prepare_copy_alter_table (thd=0x7fff78000ce8, table=0x7fff7809e778, alter_info=0x7fffe4ece2a8, alter_ctx=0x7fffe4ecd068) at /home/midenok/src/mariadb/trunk/src/sql/sql_table.cc:8806
#2  0x00000000008b791c in mysql_alter_table (thd=0x7fff78000ce8, new_db=0x7fff78005358, new_name=0x7fff78005710, create_info=0x7fffe4ece360, table_list=0x7fff78012d58, alter_info=0x7fffe4ece2a8, order_num=0, order=0x0, ignore=false) at /home/midenok/src/mariadb/trunk/src/sql/sql_table.cc:9720
#3  0x000000000095f0f7 in Sql_cmd_alter_table::execute (this=0x7fff780134c0, thd=0x7fff78000ce8) at /home/midenok/src/mariadb/trunk/src/sql/sql_alter.cc:489
#4  0x00000000007c0661 in mysql_execute_command (thd=0x7fff78000ce8) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:6280
#5  0x00000000007b21df in mysql_parse (thd=0x7fff78000ce8, rawbuf=0x7fff78012c50 "alter table t2 modify column b int not null", length=43, parser_state=0x7fffe4ed1650, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:8077
```
### Expected
No error.

**Comment by midenok** [comment]
### Bad: error state detected
```c++
#0  fk_check_column_changes (thd=0x7fff78000ce8, alter_info=0x7fffe4ece2a8, fk_columns=..., bad_column_name=0x7fffe4ecb740) at /home/midenok/src/mariadb/trunk/src/sql/sql_table.cc:8610
#1  0x00000000008bf089 in fk_prepare_copy_alter_table (thd=0x7fff78000ce8, table=0x7fff7809e778, alter_info=0x7fffe4ece2a8, alter_ctx=0x7fffe4ecd068) at /home/midenok/src/mariadb/trunk/src/sql/sql_table.cc:8796
#2  0x00000000008b791c in mysql_alter_table (thd=0x7fff78000ce8, new_db=0x7fff78005358, new_name=0x7fff78005710, create_info=0x7fffe4ece360, table_list=0x7fff78012d58, alter_info=0x7fffe4ece2a8, order_num=0, order=0x0, ignore=false) at /home/midenok/src/mariadb/trunk/src/sql/sql_table.cc:9720
#3  0x000000000095f0f7 in Sql_cmd_alter_table::execute (this=0x7fff780134c0, thd=0x7fff78000ce8) at /home/midenok/src/mariadb/trunk/src/sql/sql_alter.cc:489
#4  0x00000000007c0661 in mysql_execute_command (thd=0x7fff78000ce8) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:6280
#5  0x00000000007b21df in mysql_parse (thd=0x7fff78000ce8, rawbuf=0x7fff78012c50 "alter table t2 modify column b int not null", length=43, parser_state=0x7fffe4ed1650, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:8077
```
```c++
8597          if ((old_field->is_equal(new_field) == IS_EQUAL_NO) ||
8598              ((new_field->flags & NOT_NULL_FLAG) &&
8599               !(old_field->flags & NOT_NULL_FLAG)))
8600          {
8601            if (!(thd->variables.option_bits & OPTION_NO_FOREIGN_KEY_CHECKS))
8602            {
8603              /*
8604                Column in a FK has changed significantly. Unless
8605                foreign_key_checks are off we prohibit this since this
8606                means values in this column might be changed by ALTER
8607                and thus referential integrity might be broken,
8608              */
8609              *bad_column_name= column->str;
8610              return FK_COLUMN_DATA_CHANGE;
8611            }
8612          }
8613        }
```

**Comment by midenok** [comment]
Depends on **IB: inplace for VERS_TIMESTAMP versioning #414**
