### ISSUE TITLE
MDEV-17613 MIN/MAX Optimization (Select tables optimized away) does not work

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#565]
### Reproduce
```sql
create or replace table t1 (
    id bigint(10) not null auto_increment,
    user_id bigint(10),
    risk_assess_apply_id bigint(10),
    risk_assess_flow_id bigint(10),
    risk_assess_flow_node_id bigint(10),
    apply_type tinyint(1),
    state tinyint(1),
    create_time datetime,
    update_time datetime,
    name varchar(30),
    ext_id varchar(50),
    risk_assess_flow_name varchar(45),
    risk_assess_flow_code varchar(45),
    channel_code varchar(30),
    risk_user_id bigint(10),
    ext_user_id varchar(50),
    risk_assess_flow_state_id bigint(10),
    callback_credititem text,
    his_credititem text,
    ext_sub_credititem text,
    decision_sub_credititem text,
    total_sub_credititem text,
    calc_credititem_condition varchar(400),
    decision_credititem_conditon varchar(300),
    decision_process_id varchar(30),
    decision_result_save_condition varchar(300),
    result_save_condition varchar(300),
    is_normal int(10),
    normal_time datetime,
    is_suspend int(10),
    suspend_time datetime,
    is_continue int(10),
    continue_time datetime,
    is_decision_stop int(10),
    decision_stop_time datetime,
    is_exception int(10),
    exception_time datetime,
    decision_result_id bigint(10),
    ts timestamp(6) generated always as row start,
    te timestamp(6) generated always as row end,
    primary key (id,te),
    key idx_rafns_uid (user_id),
    key idx_rafns_risk_assess_apply_id (risk_assess_apply_id),
    key idx_rafns_risk_assess_flow_node_id (risk_assess_flow_node_id),
    key idx_rafns_create_time (create_time),
    key idx_rafns_rui (risk_user_id),
    key idx_rafns_rafsi (risk_assess_flow_state_id),
    key idx_rafns_rafni (risk_assess_flow_node_id),
    key idx_rafns_eui (ext_user_id),
    period for system_time (ts, te)
) auto_increment=42164142 row_format=compact
with system versioning
partition by system_time interval 1 month (
    partition p0 history,
    partition p1 history,
    partition p2 history,
    partition p3 history,
    partition p4 history,
    partition p5 history,
    partition p6 history,
    partition pcur current);
explain extended select max(id) from t1;
```
### Result
```
+------+-------------+-------+-------+---------------+---------+---------+------+------+----------+--------------------------+
| id   | select_type | table | type  | possible_keys | key     | key_len | ref  | rows | filtered | Extra                    |
+------+-------------+-------+-------+---------------+---------+---------+------+------+----------+--------------------------+
|    1 | SIMPLE      | t1    | index | NULL          | PRIMARY | 15      | NULL |    2 |   100.00 | Using where; Using index |
+------+-------------+-------+-------+---------------+---------+---------+------+------+----------+--------------------------+
```
### Expected
```
+------+-------------+-------+------+---------------+------+---------+------+------+----------+------------------------------+
| id   | select_type | table | type | possible_keys | key  | key_len | ref  | rows | filtered | Extra                        |
+------+-------------+-------+------+---------------+------+---------+------+------+----------+------------------------------+
|    1 | SIMPLE      | NULL  | NULL | NULL          | NULL | NULL    | NULL | NULL |     NULL | Select tables optimized away |
+------+-------------+-------+------+---------------+------+---------+------+------+----------+------------------------------+
```

**Comment by midenok** [comment]
### Fix
Instead of adding WHERE ROW_END = MAX condition it should add current partition selection. Apparently this works only for partitioned by SYSTEM_TIME tables. So the query
```sql
select * from t1;
```
transforms into
```sql
select * from t1 partition (c);
```
## Info
```c++
struct TABLE_LIST
{
...
  /* List to carry partition names from PARTITION (...) clause in statement */
  List<String> *partition_names;
```
### Partitions pruned by names
```c++
#0  0x0000000000926b19 in partition_info::set_partition_bitmaps (this=0x7fff7c036860, partition_names=0x1) at /home/midenok/src/mariadb/trunk/src/sql/partition_info.cc:305
#1  0x00000000013d8d84 in ha_partition::change_partitions_to_open (this=0x7fff7c08c090, partition_names=0x1) at /home/midenok/src/mariadb/trunk/src/sql/ha_partition.cc:8448
#2  0x00000000006faf71 in set_partitions_as_used (tl=0x7fff7c0156d8, t=0x7fff7c08b4c8) at /home/midenok/src/mariadb/trunk/src/sql/sql_base.cc:1499
#3  0x00000000006faa70 in open_table (thd=0x7fff7c000cf8, table_list=0x7fff7c0156d8, ot_ctx=0x7ffff41eac68) at /home/midenok/src/mariadb/trunk/src/sql/sql_base.cc:1962
#4  0x00000000006fec2b in open_and_process_table (thd=0x7fff7c000cf8, lex=0x7fff7c004ae0, tables=0x7fff7c0156d8, counter=0x7ffff41ead6c, flags=0, prelocking_strategy=0x7ffff41eade0, has_prelocking_list=false, ot_ctx=0x7ffff41eac68) at /home/midenok/src/mariadb/trunk/src/sql/sql_base.cc:3598
#5  0x00000000006fd8cd in open_tables (thd=0x7fff7c000cf8, options=..., start=0x7ffff41ead80, counter=0x7ffff41ead6c, flags=0, prelocking_strategy=0x7ffff41eade0) at /home/midenok/src/mariadb/trunk/src/sql/sql_base.cc:4121
#6  0x0000000000701f15 in open_and_lock_tables (thd=0x7fff7c000cf8, options=..., tables=0x7fff7c0156d8, derived=true, flags=0, prelocking_strategy=0x7ffff41eade0) at /home/midenok/src/mariadb/trunk/src/sql/sql_base.cc:4997
#7  0x00000000006b192c in open_and_lock_tables (thd=0x7fff7c000cf8, tables=0x7fff7c0156d8, derived=true, flags=0) at /home/midenok/src/mariadb/trunk/src/sql/sql_base.h:502
#8  0x00000000007b9281 in execute_sqlcom_select (thd=0x7fff7c000cf8, all_tables=0x7fff7c0156d8) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:6471
#9  0x00000000007aebf7 in mysql_execute_command (thd=0x7fff7c000cf8) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:3772
#10 0x00000000007a96f0 in mysql_parse (thd=0x7fff7c000cf8, rawbuf=0x7fff7c015060 "select * from t1 partition (pn)", length=31, parser_state=0x7ffff41ee640, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:8087
```
```c++
304       if (partition_names &&
305           partition_names->elements)
306       {
...
312         if (prune_partition_bitmaps(partition_names))
313           DBUG_RETURN(TRUE);
314       }
```
