### ISSUE TITLE
Foreign keys are disabled for versioned tables

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#58]
1. Enable foreign keys for versioned tables;
2. Investigate and describe required implementation;
3. Implement in code.

**Comment by kevgs** [comment]
When trying to remove a row from a parent table a lookup in a child table is performed to find out where a row to remove is referenced. And if it's referenced only by historical row delete should succeeded. Right now it doesn't work. Relevant code is here [here](https://github.com/natsys/mariadb_10.2/blob/natsys/trunk/storage/innobase/row/row0ins.cc#L1724) We need to insert code to ignore all history fields here.

**Comment by midenok** [comment]
### Simple deletion

```
#0  btr_cur_del_mark_set_clust_rec (flags=0x0, block=0x7f9ec98df880, rec=0x7f9eca34007e "", index=0x7f9ebb845108, offsets=0x7f9ef6b94780, thr=0x7f9eb588cf60, entry=0x7f9eb590e988, mtr=0x7f9ef6b94aa0) at /home/midenok/src/mariadb/midenok/src/storage/innobase/btr/btr0cur.cc:4931
#1  0x0000000000e42be7 in row_upd_del_mark_clust_rec (flags=0x0, node=0x7f9eb588cbf8, index=0x7f9ebb845108, offsets=0x7f9ef6b94780, thr=0x7f9eb588cf60, referenced=0x0, foreign=0x0, mtr=0x7f9ef6b94aa0) at /home/midenok/src/mariadb/midenok/src/storage/innobase/row/row0upd.cc:2992
#2  0x0000000000e43650 in row_upd_clust_step (node=0x7f9eb588cbf8, thr=0x7f9eb588cf60) at /home/midenok/src/mariadb/midenok/src/storage/innobase/row/row0upd.cc:3180
#3  0x0000000000e43bab in row_upd (node=0x7f9eb588cbf8, thr=0x7f9eb588cf60) at /home/midenok/src/mariadb/midenok/src/storage/innobase/row/row0upd.cc:3299
#4  0x0000000000e440bb in row_upd_step (thr=0x7f9eb588cf60) at /home/midenok/src/mariadb/midenok/src/storage/innobase/row/row0upd.cc:3445
#5  0x0000000000ddef6e in row_update_for_mysql_using_upd_graph (mysql_rec=0x7f9eb581da88 "\361\001", prebuilt=0x7f9eb588c088) at /home/midenok/src/mariadb/midenok/src/storage/innobase/row/row0mysql.cc:2653
#6  0x0000000000ddfb15 in row_update_for_mysql (mysql_rec=0x7f9eb581da88 "\361\001", prebuilt=0x7f9eb588c088) at /home/midenok/src/mariadb/midenok/src/storage/innobase/row/row0mysql.cc:2869
#7  0x0000000000c8579a in ha_innobase::delete_row (this=0x7f9eb58aa088, record=0x7f9eb581da88 "\361\001") at /home/midenok/src/mariadb/midenok/src/storage/innobase/handler/ha_innodb.cc:10066
#8  0x0000000000950945 in handler::ha_delete_row (this=0x7f9eb58aa088, buf=0x7f9eb581da88 "\361\001") at /home/midenok/src/mariadb/midenok/src/sql/handler.cc:5983
#9  0x0000000000adba14 in TABLE::delete_row (this=0x7f9eb58ca870) at /home/midenok/src/mariadb/midenok/src/sql/sql_delete.cc:220
#10 0x0000000000ad8f6d in mysql_delete (thd=0x7f9eb5816070, table_list=0x7f9eb5860180, conds=0x7f9eb5860930, order_list=0x7f9eb581a4c8, limit=0xffffffffffffffff, options=0x0, result=0x0) at /home/midenok/src/mariadb/midenok/src/sql/sql_delete.cc:608
#11 0x00000000006cd7d1 in mysql_execute_command (thd=0x7f9eb5816070) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:4518
#12 0x00000000006d851f in mysql_parse (thd=0x7f9eb5816070, rawbuf=0x7f9eb5860088 "delete from parent where id = 100011", length=0x24, parser_state=0x7f9ef6b96f80, is_com_multi=0x0, is_next_command=0x0) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:7794
```

### Deletion with cascaded

#### 1.

```
#0  btr_cur_del_mark_set_clust_rec (flags=0x0, block=0x7f9ec98df880, rec=0x7f9eca34007e "", index=0x7f9ebb845108, offsets=0x7f9ef6b94780, thr=0x7f9eb588cf60, entry=0x7f9eb590f888, mtr=0x7f9ef6b94aa0) at /home/midenok/src/mariadb/midenok/src/storage/innobase/btr/btr0cur.cc:4931
#1  0x0000000000e42be7 in row_upd_del_mark_clust_rec (flags=0x0, node=0x7f9eb588cbf8, index=0x7f9ebb845108, offsets=0x7f9ef6b94780, thr=0x7f9eb588cf60, referenced=0x0, foreign=0x0, mtr=0x7f9ef6b94aa0) at /home/midenok/src/mariadb/midenok/src/storage/innobase/row/row0upd.cc:2992
#2  0x0000000000e43650 in row_upd_clust_step (node=0x7f9eb588cbf8, thr=0x7f9eb588cf60) at /home/midenok/src/mariadb/midenok/src/storage/innobase/row/row0upd.cc:3180
#3  0x0000000000e43bab in row_upd (node=0x7f9eb588cbf8, thr=0x7f9eb588cf60) at /home/midenok/src/mariadb/midenok/src/storage/innobase/row/row0upd.cc:3299
#4  0x0000000000e440bb in row_upd_step (thr=0x7f9eb588cf60) at /home/midenok/src/mariadb/midenok/src/storage/innobase/row/row0upd.cc:3445
#5  0x0000000000ddef6e in row_update_for_mysql_using_upd_graph (mysql_rec=0x7f9eb581da88 "\361\001", prebuilt=0x7f9eb588c088) at /home/midenok/src/mariadb/midenok/src/storage/innobase/row/row0mysql.cc:2653
#6  0x0000000000ddfb15 in row_update_for_mysql (mysql_rec=0x7f9eb581da88 "\361\001", prebuilt=0x7f9eb588c088) at /home/midenok/src/mariadb/midenok/src/storage/innobase/row/row0mysql.cc:2869
#7  0x0000000000c8579a in ha_innobase::delete_row (this=0x7f9eb58aa088, record=0x7f9eb581da88 "\361\001") at /home/midenok/src/mariadb/midenok/src/storage/innobase/handler/ha_innodb.cc:10066
#8  0x0000000000950945 in handler::ha_delete_row (this=0x7f9eb58aa088, buf=0x7f9eb581da88 "\361\001") at /home/midenok/src/mariadb/midenok/src/sql/handler.cc:5983
#9  0x0000000000adba14 in TABLE::delete_row (this=0x7f9eb58ca870) at /home/midenok/src/mariadb/midenok/src/sql/sql_delete.cc:220
#10 0x0000000000ad8f6d in mysql_delete (thd=0x7f9eb5816070, table_list=0x7f9eb5860180, conds=0x7f9eb5860930, order_list=0x7f9eb581a4c8, limit=0xffffffffffffffff, options=0x0, result=0x0) at /home/midenok/src/mariadb/midenok/src/sql/sql_delete.cc:608
#11 0x00000000006cd7d1 in mysql_execute_command (thd=0x7f9eb5816070) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:4518
#12 0x00000000006d851f in mysql_parse (thd=0x7f9eb5816070, rawbuf=0x7f9eb5860088 "delete from parent where id = 100011", length=0x24, parser_state=0x7f9ef6b96f80, is_com_multi=0x0, is_next_command=0x0) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:7794
```

#### 2.

```
#0  btr_cur_del_mark_set_clust_rec (flags=0x0, block=0x7f9ec98ded88, rec=0x7f9eca33407e "", index=0x7f9ebac45108, offsets=0x7f9ef6b94780, thr=0x7f9eb588cf60, entry=0x7f9eb590f888, mtr=0x7f9ef6b94aa0) at /home/midenok/src/mariadb/midenok/src/storage/innobase/btr/btr0cur.cc:4931
#1  0x0000000000e42be7 in row_upd_del_mark_clust_rec (flags=0x0, node=0x7f9eb5902788, index=0x7f9ebac45108, offsets=0x7f9ef6b94780, thr=0x7f9eb588cf60, referenced=0x0, foreign=0x0, mtr=0x7f9ef6b94aa0) at /home/midenok/src/mariadb/midenok/src/storage/innobase/row/row0upd.cc:2992
#2  0x0000000000e43650 in row_upd_clust_step (node=0x7f9eb5902788, thr=0x7f9eb588cf60) at /home/midenok/src/mariadb/midenok/src/storage/innobase/row/row0upd.cc:3180
#3  0x0000000000e43bab in row_upd (node=0x7f9eb5902788, thr=0x7f9eb588cf60) at /home/midenok/src/mariadb/midenok/src/storage/innobase/row/row0upd.cc:3299
#4  0x0000000000e440bb in row_upd_step (thr=0x7f9eb588cf60) at /home/midenok/src/mariadb/midenok/src/storage/innobase/row/row0upd.cc:3445
#5  0x0000000000ddef6e in row_update_for_mysql_using_upd_graph (mysql_rec=0x7f9eb581da88 "\361\001", prebuilt=0x7f9eb588c088) at /home/midenok/src/mariadb/midenok/src/storage/innobase/row/row0mysql.cc:2653
#6  0x0000000000ddfb15 in row_update_for_mysql (mysql_rec=0x7f9eb581da88 "\361\001", prebuilt=0x7f9eb588c088) at /home/midenok/src/mariadb/midenok/src/storage/innobase/row/row0mysql.cc:2869
#7  0x0000000000c8579a in ha_innobase::delete_row (this=0x7f9eb58aa088, record=0x7f9eb581da88 "\361\001") at /home/midenok/src/mariadb/midenok/src/storage/innobase/handler/ha_innodb.cc:10066
#8  0x0000000000950945 in handler::ha_delete_row (this=0x7f9eb58aa088, buf=0x7f9eb581da88 "\361\001") at /home/midenok/src/mariadb/midenok/src/sql/handler.cc:5983
#9  0x0000000000adba14 in TABLE::delete_row (this=0x7f9eb58ca870) at /home/midenok/src/mariadb/midenok/src/sql/sql_delete.cc:220
#10 0x0000000000ad8f6d in mysql_delete (thd=0x7f9eb5816070, table_list=0x7f9eb5860180, conds=0x7f9eb5860930, order_list=0x7f9eb581a4c8, limit=0xffffffffffffffff, options=0x0, result=0x0) at /home/midenok/src/mariadb/midenok/src/sql/sql_delete.cc:608
#11 0x00000000006cd7d1 in mysql_execute_command (thd=0x7f9eb5816070) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:4518
#12 0x00000000006d851f in mysql_parse (thd=0x7f9eb5816070, rawbuf=0x7f9eb5860088 "delete from parent where id = 100011", length=0x24, parser_state=0x7f9ef6b96f80, is_com_multi=0x0, is_next_command=0x0) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:7794
```

Repeat point: `row_update_for_mysql_using_upd_graph`

**Comment by midenok** [comment]
### Cascade operation

``` c++
2731            if (!cascade_upd_nodes->empty()) {
2732                    DEBUG_SYNC_C("foreign_constraint_update_cascade");
2733                    node = cascade_upd_nodes->front();
2734                    node->cascade_upd_nodes = cascade_upd_nodes;
2735                    cascade_upd_nodes->pop_front();
2736                    thr->fk_cascade_depth++;
2737                    prebuilt->m_mysql_table = NULL;
2738
2739                    goto run_again;
2740            }
```

**Comment by kevgs** [comment]
``` sql
create or replace table parent(
  id int unique key
) engine innodb with system versioning;

create or replace table child(
  parent_id int,
  foreign key(parent_id) references parent(id)
) engine innodb;

insert into parent values(1); insert into child values(1); delete from parent;
```

Test doesn't pass because parent table actually allows deletion when it souldn't.

**Comment by midenok** [comment]
```
#0  row_upd_check_references_constraints (node=0x7f3d27869c10, pcur=0x7f3d684034e0, table=0x7f3d2787e688, index=0x7f3d2787f808, offsets=0x7f3d2781ef18, thr=0x7f3d27869f78, mtr=0x7f3d68403a60) at /home/midenok/src/mariadb/midenok/src/storage/innobase/row/row0upd.cc:230
#1  0x0000000000e412b6 in row_upd_sec_index_entry (node=0x7f3d27869c10, thr=0x7f3d27869f78) at /home/midenok/src/mariadb/midenok/src/storage/innobase/row/row0upd.cc:2484
#2  0x0000000000e4156f in row_upd_sec_step (node=0x7f3d27869c10, thr=0x7f3d27869f78) at /home/midenok/src/mariadb/midenok/src/storage/innobase/row/row0upd.cc:2533
#3  0x0000000000e43d92 in row_upd (node=0x7f3d27869c10, thr=0x7f3d27869f78) at /home/midenok/src/mariadb/midenok/src/storage/innobase/row/row0upd.cc:3328
#4  0x0000000000e4411b in row_upd_step (thr=0x7f3d27869f78) at /home/midenok/src/mariadb/midenok/src/storage/innobase/row/row0upd.cc:3445
#5  0x0000000000ddefce in row_update_for_mysql_using_upd_graph (mysql_rec=0x7f3d2781d088 "\375\001", prebuilt=0x7f3d27869088) at /home/midenok/src/mariadb/midenok/src/storage/innobase/row/row0mysql.cc:2659
#6  0x0000000000ddfb75 in row_update_for_mysql (mysql_rec=0x7f3d2781d088 "\375\001", prebuilt=0x7f3d27869088) at /home/midenok/src/mariadb/midenok/src/storage/innobase/row/row0mysql.cc:2875
#7  0x0000000000c8579a in ha_innobase::delete_row (this=0x7f3d278ab888, record=0x7f3d2781d088 "\375\001") at /home/midenok/src/mariadb/midenok/src/storage/innobase/handler/ha_innodb.cc:10066
#8  0x0000000000950945 in handler::ha_delete_row (this=0x7f3d278ab888, buf=0x7f3d2781d088 "\375\001") at /home/midenok/src/mariadb/midenok/src/sql/handler.cc:5983
#9  0x0000000000adba14 in TABLE::delete_row (this=0x7f3d278ca870) at /home/midenok/src/mariadb/midenok/src/sql/sql_delete.cc:220
#10 0x0000000000ad8f6d in mysql_delete (thd=0x7f3d27816070, table_list=0x7f3d27860160, conds=0x0, order_list=0x7f3d2781a4c8, limit=0xffffffffffffffff, options=0x0, result=0x0) at /home/midenok/src/mariadb/midenok/src/sql/sql_delete.cc:608
#11 0x00000000006cd7d1 in mysql_execute_command (thd=0x7f3d27816070) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:4518
#12 0x00000000006d851f in mysql_parse (thd=0x7f3d27816070, rawbuf=0x7f3d27860088 "delete from parent", length=0x12, parser_state=0x7f3d68405f80, is_com_multi=0x0, is_next_command=0x0) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:7794
```
