### ISSUE TITLE
MDEV-19304 SIGSEGV / ASAN unknown-crash in row_sel_field_store_in_mysql_format_func or create_tmp_table or my_timestamp_from_binary or Field::cmp_binary or calc_row_difference upon action on system-versioned table with SIMULTANEOUS_ASSIGNMENT

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#591]
### Reproduce
```sql
create or replace table t1 (a int, s timestamp(6) as row start, e timestamp(6) as row end, period for system_time(s,e)) engine=myisam with system versioning;
insert into t1 values (null, null, null);
insert into t1 values (null, null, null);
set sql_mode= 'simultaneous_assignment';
update t1 set e= 1;
alter table t1 force;
```
### Result
```c++
#0  0x0000000000787634 in __asan::ReportGenericError(unsigned long, unsigned long, unsigned long, unsigned long, bool, unsigned long, unsigned int, bool) ()
#1  0x0000000000788188 in __asan_report_load1 ()
#2  0x00000000014db215 in my_timestamp_from_binary (tm=0x7fffd05f52a0, ptr=0x6190000a78b4 "\217\217\217\217\377", dec=6) at /home/midenok/src/mariadb/trunk/src/sql/compat56.cc:407
#3  0x000000000151c7ea in Field_timestampf::get_timestamp (this=0x6190000a7fd0, pos=0x6190000a78b4 "\217\217\217\217\377", sec_part=0x7fffd05f5410) at /home/midenok/src/mariadb/trunk/src/sql/field.cc:5565
#4  0x0000000001569da9 in Field_timestamp::get_timestamp (this=0x6190000a7fd0, sec_part=0x7fffd05f5410) at /home/midenok/src/mariadb/trunk/src/sql/field.h:2838
#5  0x0000000001516114 in Field_timestamp::get_date (this=0x6190000a7fd0, ltime=0x7fffd05f5560, fuzzydate=...) at /home/midenok/src/mariadb/trunk/src/sql/field.cc:5301
#6  0x00000000015148c3 in Field_timestamp::val_str (this=0x6190000a7fd0, val_buffer=0x7fffd05f5aa0, val_ptr=0x7fffd05f5aa0) at /home/midenok/src/mariadb/trunk/src/sql/field.cc:5226
#7  0x000000000082447d in Field::val_str (this=0x6190000a7fd0, str=0x7fffd05f5aa0) at /home/midenok/src/mariadb/trunk/src/sql/field.h:837
#8  0x000000000156fa58 in Field::val_str (this=0x6190000a7fd0, str=0x7fffd05f5aa0, new_ptr=0x6190000a78b4 "\217\217\217\217\377") at /home/midenok/src/mariadb/trunk/src/sql/field.h:1339
#9  0x000000000156470f in Column_definition::Column_definition (this=0x62b0000b6ed0, thd=0x62b0000af208, old_field=0x6190000a7fd0, orig_field=0x6190000a7fd0) at /home/midenok/src/mariadb/trunk/src/sql/field.cc:10806
#10 0x0000000000b06ec5 in Create_field::Create_field (this=0x62b0000b6ed0, thd=0x62b0000af208, old_field=0x6190000a7fd0, orig_field=0x6190000a7fd0) at /home/midenok/src/mariadb/trunk/src/sql/field.h:4989
#11 0x0000000000ed3ac2 in mysql_prepare_alter_table (thd=0x62b0000af208, table=0x620000036088, create_info=0x7fffd05fd400, alter_info=0x7fffd05fd630, alter_ctx=0x7fffd05f8af0) at /home/midenok/src/mariadb/trunk/src/sql/sql_table.cc:8134
#12 0x0000000000ee3d1c in mysql_alter_table (thd=0x62b0000af208, new_db=0x62b0000b39a0, new_name=0x62b0000b3da8, create_info=0x7fffd05fd400, table_list=0x62b0000b62f8, alter_info=0x7fffd05fd630, order_num=0, order=0x0, ignore=false) at /home/midenok/src/mariadb/trunk/src/sql/sql_table.cc:9674
#13 0x00000000011088a3 in Sql_cmd_alter_table::execute (this=0x62b0000b69a8, thd=0x62b0000af208) at /home/midenok/src/mariadb/trunk/src/sql/sql_alter.cc:490
#14 0x0000000000bcf6a7 in mysql_execute_command (thd=0x62b0000af208) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:6344
#15 0x0000000000ba8715 in mysql_parse (thd=0x62b0000af208, rawbuf=0x62b0000b6220 "alter table t1 force", length=20, parser_state=0x7fffd0603f80, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:8154
```

**Comment by midenok** [comment]
### Warning printed on update
```c++
#0  push_warning_printf (thd=0x620000036088, level=24896, code=4172, format=0x7fffd060b960 "\320?\v") at /home/midenok/src/mariadb/trunk/src/sql/sql_error.cc:737
#1  0x00000000009dd8c7 in fill_record (thd=0x62b0000af208, table_arg=0x620000036088, fields=..., values=..., ignore_errors=false, update=true) at /home/midenok/src/mariadb/trunk/src/sql/sql_base.cc:8418
#2  0x00000000009df0f1 in fill_record_n_invoke_before_triggers (thd=0x62b0000af208, table=0x620000036088, fields=..., values=..., ignore_errors=false, event=TRG_EVENT_UPDATE) at /home/midenok/src/mariadb/trunk/src/sql/sql_base.cc:8601
#3  0x0000000000f65c45 in mysql_update (thd=0x62b0000af208, table_list=0x62b0000b62f8, select_lex=0x62b0000b3900, values=..., limit=18446744073709551615, ignore=false, found_return=0x7fffd060ebd0, updated_return=0x7fffd060ebf0) at /home/midenok/src/mariadb/trunk/src/sql/sql_update.cc:959
#4  0x0000000000bc0abb in mysql_execute_command (thd=0x62b0000af208) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:4641
#5  0x0000000000ba8715 in mysql_parse (thd=0x62b0000af208, rawbuf=0x62b0000b6220 "update t1 set e= 1", length=18, parser_state=0x7fffd0613f80, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:8154
```
```c++
8413        if ((rfield->vcol_info || vers_sys_field) &&
8414            type != Item::DEFAULT_VALUE_ITEM &&
8415            type != Item::NULL_ITEM &&
8416            table->s->table_category != TABLE_CATEGORY_TEMPORARY)
8417        {
8418          push_warning_printf(thd, Sql_condition::WARN_LEVEL_WARN,
8419                              ER_WARNING_NON_DEFAULT_VALUE_FOR_GENERATED_COLUMN,
8420                              ER_THD(thd, ER_WARNING_NON_DEFAULT_VALUE_FOR_GENERATED_COLUMN),
8421                              rfield->field_name.str, table->s->table_name.str);
8422          if (vers_sys_field)
8423            continue;
8424        }
```
```
+---------+------+-----------------------------------------------------------------------------+
| Level   | Code | Message                                                                     |
+---------+------+-----------------------------------------------------------------------------+
| Warning | 1906 | The value specified for generated column 'e' in table 't1' has been ignored |
+---------+------+-----------------------------------------------------------------------------+
```
