### ISSUE TITLE
SHOW CREATE TABLE: `DEFAULT NULL` instead of `NOT NULL` for NOW() funcs

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#63]
``` diff
--- /home/midenok/src/mariadb/10.2/src4/mysql-test/r/ctype_binary.result        2016-10-27 10:23:10.867101438 +0000
+++ /home/midenok/src/mariadb/10.2/src4/mysql-test/r/ctype_binary.reject        2016-10-27 10:29:43.989820783 +0000
@@ -1606,21 +1606,21 @@
 show create table t1;
 Table  Create Table
 t1     CREATE TABLE `t1` (
-  `c1` varbinary(19) NOT NULL
+  `c1` varbinary(19) DEFAULT NULL
 ) ENGINE=MyISAM DEFAULT CHARSET=latin1
 drop table t1;
 create table t1 as select concat(utc_timestamp()) as c1;
 show create table t1;
 Table  Create Table
 t1     CREATE TABLE `t1` (
-  `c1` varbinary(19) NOT NULL
+  `c1` varbinary(19) DEFAULT NULL
 ) ENGINE=MyISAM DEFAULT CHARSET=latin1
 drop table t1;
 create table t1 as select concat(sysdate()) as c1;
 show create table t1;
 Table  Create Table
 t1     CREATE TABLE `t1` (
-  `c1` varbinary(19) NOT NULL
+  `c1` varbinary(19) DEFAULT NULL
 ) ENGINE=MyISAM DEFAULT CHARSET=latin1
 drop table t1;
 select hex(concat(addtime('00:00:00','11:22:33')));
```

**Comment by midenok** [comment]
### Correct:

``` sql
MariaDB [test]> create or replace table t1 as select concat('abcdef') as c1; show create table t1;
Query OK, 1 row affected (0.07 sec)
Records: 1  Duplicates: 0  Warnings: 0

+-------+----------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                             |
+-------+----------------------------------------------------------------------------------------------------------+
| t1    | CREATE TABLE `t1` (
  `c1` varchar(6) CHARACTER SET utf8 NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 |
+-------+----------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### Incorrect:

``` sql
MariaDB [test]> create or replace table t1 as select concat(now()) as c1; show create table t1;
Query OK, 1 row affected (0.07 sec)
Records: 1  Duplicates: 0  Warnings: 0

+-------+---------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                  |
+-------+---------------------------------------------------------------------------------------------------------------+
| t1    | CREATE TABLE `t1` (
  `c1` varchar(19) CHARACTER SET utf8 DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 |
+-------+---------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

Temporary func items are initialized with `DEFAULT NULL` instead of `NOT NULL`.

**Comment by midenok** [comment]
### 1. `maybe_null` set to `false`:

```
#0  0x000000000095779d in Item::Item (this=0x7ff961860140, thd=0x7ff961816070) at /home/midenok/src/mariadb/10.2/src/sql/item.cc:478
#1  0x0000000000605bef in Item_result_field::Item_result_field (this=0x7ff961860140, thd=0x7ff961816070) at /home/midenok/src/mariadb/10.2/src/sql/item.h:2317
#2  0x0000000000605f55 in Item_func_or_sum::Item_func_or_sum (this=0x7ff961860140, thd=0x7ff961816070, a=0x7ff961860238) at /home/midenok/src/mariadb/10.2/src/sql/item.h:3926
#3  0x0000000000606121 in Item_func::Item_func (this=0x7ff961860140, thd=0x7ff961816070, a=0x7ff961860238) at /home/midenok/src/mariadb/10.2/src/sql/item_func.h:78
#4  0x00000000008f79dd in Item_temporal_func::Item_temporal_func (this=0x7ff961860140, thd=0x7ff961816070, a=0x7ff961860238) at /home/midenok/src/mariadb/10.2/src/sql/item_timefunc.h:535
#5  0x00000000009abb3d in Item_datetimefunc::Item_datetimefunc (this=0x7ff961860140, thd=0x7ff961816070, a=0x7ff961860238) at /home/midenok/src/mariadb/10.2/src/sql/item_timefunc.h:628
#6  0x0000000000a2b13f in Item_func_now::Item_func_now (this=0x7ff961860140, thd=0x7ff961816070, dec=0x0) at /home/midenok/src/mariadb/10.2/src/sql/item_timefunc.cc:1697
#7  0x00000000008f7ea1 in Item_func_now_local::Item_func_now_local (this=0x7ff961860140, thd=0x7ff961816070, dec=0x0) at /home/midenok/src/mariadb/10.2/src/sql/item_timefunc.h:746
#8  0x00000000008d9588 in MYSQLparse (thd=0x7ff961816070) at /home/midenok/src/mariadb/10.2/src/sql/sql_yacc.yy:9837
#9  0x00000000006dd1fd in parse_sql (thd=0x7ff961816070, parser_state=0x7ff9a37f9f80, creation_ctx=0x0, do_pfs_digest=0x1) at /home/midenok/src/mariadb/10.2/src/sql/sql_parse.cc:9813
#10 0x00000000006d8392 in mysql_parse (thd=0x7ff961816070, rawbuf=0x7ff961860088 "select concat(now()) as c1", length=0x1a, parser_state=0x7ff9a37f9f80, is_com_multi=0x0, is_next_command=0x0) at /home/midenok/src/mariadb/10.2/src/sql/sql_parse.cc:7747
```

### 2. `maybe_null` set to `true`:

```
#0  Item_temporal_func::fix_length_and_dec (this=0x7ff961860140) at /home/midenok/src/mariadb/10.2/src/sql/item_timefunc.cc:1467
#1  0x00000000009b510a in Item_func::fix_fields (this=0x7ff961860140, thd=0x7ff961816070, ref=0x7ff9618603c8) at /home/midenok/src/mariadb/10.2/src/sql/item_func.cc:236
#2  0x0000000000a2b219 in Item_func_now::fix_fields (this=0x7ff961860140, thd=0x7ff961816070, items=0x7ff9618603c8) at /home/midenok/src/mariadb/10.2/src/sql/item_timefunc.cc:1711
#3  0x00000000009b4ebc in Item_func::fix_fields (this=0x7ff961860338, thd=0x7ff961816070, ref=0x7ff961860428) at /home/midenok/src/mariadb/10.2/src/sql/item_func.cc:209
#4  0x00000000009e62b9 in Item_str_func::fix_fields (this=0x7ff961860338, thd=0x7ff961816070, ref=0x7ff961860428) at /home/midenok/src/mariadb/10.2/src/sql/item_strfunc.cc:105
#5  0x0000000000663529 in setup_fields (thd=0x7ff961816070, ref_pointer_array=..., fields=..., mark_used_columns=MARK_COLUMNS_READ, sum_func_list=0x7ff9618607f8, allow_sum_func=0x1) at /home/midenok/src/mariadb/10.2/src/sql/sql_base.cc:6964
#6  0x000000000070afb1 in JOIN::prepare (this=0x7ff9618604e8, tables_init=0x0, wild_num=0x0, conds_init=0x0, og_num=0x0, order_init=0x0, skip_order_by=0x0, group_init=0x0, having_init=0x0, proc_param_init=0x0, select_lex_arg=0x7ff96181a278, unit_arg=0x7ff961819b38) at /home/midenok/src/mariadb/10.2/src/sql/sql_select.cc:981
#7  0x0000000000714efb in mysql_select (thd=0x7ff961816070, tables=0x0, wild_num=0x0, fields=..., conds=0x0, og_num=0x0, order=0x0, group=0x0, having=0x0, proc_param=0x0, select_options=0x80040b00, result=0x7ff9618604c8, unit=0x7ff961819b38, select_lex=0x7ff96181a278) at /home/midenok/src/mariadb/10.2/src/sql/sql_select.cc:3727
#8  0x0000000000708c67 in handle_select (thd=0x7ff961816070, lex=0x7ff961819a70, result=0x7ff9618604c8, setup_tables_done_option=0x0) at /home/midenok/src/mariadb/10.2/src/sql/sql_select.cc:374
#9  0x00000000006d4a17 in execute_sqlcom_select (thd=0x7ff961816070, all_tables=0x0) at /home/midenok/src/mariadb/10.2/src/sql/sql_parse.cc:6351
#10 0x00000000006ca1cc in mysql_execute_command (thd=0x7ff961816070) at /home/midenok/src/mariadb/10.2/src/sql/sql_parse.cc:3376
#11 0x00000000006d8525 in mysql_parse (thd=0x7ff961816070, rawbuf=0x7ff961860088 "select concat(now()) as c1", length=0x1a, parser_state=0x7ff9a37f9f80, is_com_multi=0x0, is_next_command=0x0) at /home/midenok/src/mariadb/10.2/src/sql/sql_parse.cc:7794
```

``` c++
1459    void Item_temporal_func::fix_length_and_dec()
1460    {
1461      uint char_length= mysql_temporal_int_part_length(field_type());
1462      /*
1463        We set maybe_null to 1 as default as any bad argument with date or
1464        time can get us to return NULL.
1465      */
1466      maybe_null= (arg_count > 0);
1467      if (decimals)
1468      {
1469        if (decimals == NOT_FIXED_DEC)
1470          char_length+= TIME_SECOND_PART_DIGITS + 1;
1471        else
1472        {
1473          set_if_smaller(decimals, TIME_SECOND_PART_DIGITS);
1474          char_length+= decimals + 1;
1475        }
1476      }
```

``` c++
51dcf4dc (Alexander Barkov   2013-09-13 12:06:17 +0400 1462)   /*
51dcf4dc (Alexander Barkov   2013-09-13 12:06:17 +0400 1463)     We set maybe_null to 1 as default as any bad argument with date or
51dcf4dc (Alexander Barkov   2013-09-13 12:06:17 +0400 1464)     time can get us to return NULL.
51dcf4dc (Alexander Barkov   2013-09-13 12:06:17 +0400 1465)   */
db7edfed (Michael Widenius   2016-06-29 09:14:22 +0200 1466)   maybe_null= (arg_count > 0);
76f0b94b (Sergei Golubchik   2011-10-19 21:45:18 +0200 1467)   if (decimals)
76f0b94b (Sergei Golubchik   2011-10-19 21:45:18 +0200 1468)   {
76f0b94b (Sergei Golubchik   2011-10-19 21:45:18 +0200 1469)     if (decimals == NOT_FIXED_DEC)
9adb6e99 (Alexander Barkov   2013-08-22 13:59:30 +0400 1470)       char_length+= TIME_SECOND_PART_DIGITS + 1;
76f0b94b (Sergei Golubchik   2011-10-19 21:45:18 +0200 1471)     else
76f0b94b (Sergei Golubchik   2011-10-19 21:45:18 +0200 1472)     {
76f0b94b (Sergei Golubchik   2011-10-19 21:45:18 +0200 1473)       set_if_smaller(decimals, TIME_SECOND_PART_DIGITS);
9adb6e99 (Alexander Barkov   2013-08-22 13:59:30 +0400 1474)       char_length+= decimals + 1;
76f0b94b (Sergei Golubchik   2011-10-19 21:45:18 +0200 1475)     }
76f0b94b (Sergei Golubchik   2011-10-19 21:45:18 +0200 1476)   }
```

``` diff
commit db7edfed17efe6bc3684b0fbacc0b0249e4f0fa2
Author: Michael Widenius <monty@mariadb.org>
Date:   Wed Jun 29 09:14:22 2016 +0200

    MDEV-7563 Support CHECK constraint as in (or close to) SQL Standard
    MDEV-10134 Add full support for DEFAULT

...
    - Add a lookahead for NOT NULL, to be able to handle DEFAULT 1+1 NOT NULL
...

diff --git a/sql/item_timefunc.cc b/sql/item_timefunc.cc
index 16edb35..69eb3d6 100644
--- a/sql/item_timefunc.cc
+++ b/sql/item_timefunc.cc
@@ -1465,7 +1465,7 @@ void Item_temporal_func::fix_length_and_dec()
     We set maybe_null to 1 as default as any bad argument with date or
     time can get us to return NULL.
   */
-  maybe_null= 1;
+  maybe_null= (arg_count > 0);
   if (decimals)
   {
     if (decimals == NOT_FIXED_DEC)
```

**Comment by midenok** [comment]
Related to #4.

**Comment by midenok** [comment]
Not fixing since the behaviour is expected (db7edfed17efe6bc3684b0fbacc0b0249e4f0fa2).
