### ISSUE TITLE
0.4: COMMIT_ID-based ordering of transactions

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#71]
Algorithm description is [here](https://github.com/natsys/mariadb_10.2/wiki/Ordering-of-transactions).

- [x] Remove `CONCURR_TRX`;
- [x]  Add `COMMIT_ID`, `ISO_LEVEL` to VTQ;
- [x]  Add `VTQ_COMMIT_ID`, `VTQ_ISO_LEVEL` functions;
- [x] Add `VTQ_TRX_ID` function (get TRX_ID by COMMIT_TS);
- [x]  Add `TRX_SEES` function;
- [x] Modify `setup_for_system_time()`, `TRX_SEES_EQ()`;
- [x]  Tests.

Tests:
- [x] check VTQ_ISO_LEVEL() for different isolation levels;
- [x] check VTQ_TRX_ID() is jumping to proper TRX_ID by COMMIT_TS;
- [x] test VTQ_TRX_SEES(), VTQ_TRX_SEES_EQ().

**Comment by midenok** [comment]
``` c++
static inline
ulint
innobase_map_isolation_level(
/*=========================*/
    enum_tx_isolation   iso)    /*!< in: MySQL isolation level code */
{
    switch (iso) {
    case ISO_REPEATABLE_READ:   return(TRX_ISO_REPEATABLE_READ);
    case ISO_READ_COMMITTED:    return(TRX_ISO_READ_COMMITTED);
    case ISO_SERIALIZABLE:      return(TRX_ISO_SERIALIZABLE);
    case ISO_READ_UNCOMMITTED:  return(TRX_ISO_READ_UNCOMMITTED);
    }

    ut_error;

    return(0);
}
```

``` c++
    /* Assign a read view if the transaction does not have it yet.
    Do this only if transaction is using REPEATABLE READ isolation
    level. */
    trx->isolation_level = innobase_map_isolation_level(
        thd_get_trx_isolation(thd));
```

**Comment by midenok** [comment]
### Set `trx->isolation_level` on INSERT

```
#0  innobase_map_isolation_level (iso=ISO_REPEATABLE_READ) at /home/midenok/src/mariadb/midenok/src/storage/innobase/handler/ha_innodb.cc:18086
#1  0x0000000000c96890 in ha_innobase::store_lock (this=0x7fffaf8af088, thd=0x7fffaf816070, to=0x7fffaf8609e0, lock_type=TL_WRITE_CONCURRENT_INSERT) at /home/midenok/src/mariadb/midenok/src/storage/innobase/handler/ha_innodb.cc:19037
#2  0x0000000000a57cd1 in get_lock_data (thd=0x7fffaf816070, table_ptr=0x7fffaf8609c0, count=0x1, flags=0x3) at /home/midenok/src/mariadb/midenok/src/sql/lock.cc:798
#3  0x0000000000a566ba in mysql_lock_tables (thd=0x7fffaf816070, tables=0x7fffaf8609c0, count=0x1, flags=0x0) at /home/midenok/src/mariadb/midenok/src/sql/lock.cc:306
#4  0x000000000065df9c in lock_tables (thd=0x7fffaf816070, tables=0x7fffaf860168, count=0x1, flags=0x0) at /home/midenok/src/mariadb/midenok/src/sql/sql_base.cc:4809
#5  0x000000000065d6df in open_and_lock_tables (thd=0x7fffaf816070, options=..., tables=0x7fffaf860168, derived=0x1, flags=0x0, prelocking_strategy=0x7ffff7f4ac20) at /home/midenok/src/mariadb/midenok/src/sql/sql_base.cc:4599
#6  0x000000000065236b in open_and_lock_tables (thd=0x7fffaf816070, tables=0x7fffaf860168, derived=0x1, flags=0x0) at /home/midenok/src/mariadb/midenok/src/sql/sql_base.h:497
#7  0x00000000006a3da3 in mysql_insert (thd=0x7fffaf816070, table_list=0x7fffaf860168, fields=..., values_list=..., update_fields=..., update_values=..., duplic=DUP_ERROR, ignore=0x0) at /home/midenok/src/mariadb/midenok/src/sql/sql_insert.cc:719
#8  0x00000000006ccc5c in mysql_execute_command (thd=0x7fffaf816070) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:4322
#9  0x00000000006d8539 in mysql_parse (thd=0x7fffaf816070, rawbuf=0x7fffaf860088 "insert into t1 values (1)", length=0x19, parser_state=0x7ffff7f4bf30, is_com_multi=0x0, is_next_command=0x0) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:7794
```

### Set `trx->isolation_level` on SELECT

```
#0  innobase_map_isolation_level (iso=ISO_REPEATABLE_READ) at /home/midenok/src/mariadb/midenok/src/storage/innobase/handler/ha_innodb.cc:18086
#1  0x0000000000c96890 in ha_innobase::store_lock (this=0x7fffaf8b6088, thd=0x7fffaf816070, to=0x7fffaf860938, lock_type=TL_READ) at /home/midenok/src/mariadb/midenok/src/storage/innobase/handler/ha_innodb.cc:19037
#2  0x0000000000a57cd1 in get_lock_data (thd=0x7fffaf816070, table_ptr=0x7fffaf860918, count=0x1, flags=0x3) at /home/midenok/src/mariadb/midenok/src/sql/lock.cc:798
#3  0x0000000000a566ba in mysql_lock_tables (thd=0x7fffaf816070, tables=0x7fffaf860918, count=0x1, flags=0x0) at /home/midenok/src/mariadb/midenok/src/sql/lock.cc:306
#4  0x000000000065df9c in lock_tables (thd=0x7fffaf816070, tables=0x7fffaf860260, count=0x1, flags=0x0) at /home/midenok/src/mariadb/midenok/src/sql/sql_base.cc:4809
#5  0x000000000065d6df in open_and_lock_tables (thd=0x7fffaf816070, options=..., tables=0x7fffaf860260, derived=0x1, flags=0x0, prelocking_strategy=0x7ffff7f4aa10) at /home/midenok/src/mariadb/midenok/src/sql/sql_base.cc:4599
#6  0x000000000065236b in open_and_lock_tables (thd=0x7fffaf816070, tables=0x7fffaf860260, derived=0x1, flags=0x0) at /home/midenok/src/mariadb/midenok/src/sql/sql_base.h:497
#7  0x00000000006d4585 in execute_sqlcom_select (thd=0x7fffaf816070, all_tables=0x7fffaf860260) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:6272
#8  0x00000000006ca1e0 in mysql_execute_command (thd=0x7fffaf816070) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:3376
#9  0x00000000006d8539 in mysql_parse (thd=0x7fffaf816070, rawbuf=0x7fffaf860088 "select * from t1", length=0x10, parser_state=0x7ffff7f4bf30, is_com_multi=0x0, is_next_command=0x0) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:7794
```

**Comment by midenok** [comment]
```
#0  Item_func_vtq_id::fix_fields (this=0x7fffafc61490, thd=0x7fffafc16070, ref=0x7fffafc61858) at /home/midenok/src/mariadb/midenok/src/sql/item_timefunc.h:1348
#1  0x00000000009be1d4 in Item_func::fix_fields (this=0x7fffafc617b0, thd=0x7fffafc16070, ref=0x7fffafc619b8) at /home/midenok/src/mariadb/midenok/src/sql/item_func.cc:209
#2  0x0000000000992c87 in Item_cond::fix_fields (this=0x7fffafc61890, thd=0x7fffafc16070, ref=0x7fffafc610e8) at /home/midenok/src/mariadb/midenok/src/sql/item_cmpfunc.cc:4525
#3  0x00000000006681b4 in setup_conds (thd=0x7fffafc16070, tables=0x7fffafc60460, leaves=..., conds=0x7fffafc610e8) at /home/midenok/src/mariadb/midenok/src/sql/sql_base.cc:7714
#4  0x000000000070c5bb in setup_without_group (thd=0x7fffafc16070, ref_pointer_array=..., tables=0x7fffafc60460, leaves=..., fields=..., all_fields=..., conds=0x7fffafc610e8, order=0x0, group=0x0, win_specs=..., win_funcs=..., hidden_group_fields=0x7fffafc60fc7, reserved=0x7fffafc1a52c) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:638
#5  0x000000000070e4c8 in JOIN::prepare (this=0x7fffafc60cf0, tables_init=0x7fffafc60460, wild_num=0x0, conds_init=0x0, og_num=0x0, order_init=0x0, skip_order_by=0x0, group_init=0x0, having_init=0x0, proc_param_init=0x0, select_lex_arg=0x7fffafc1a278, unit_arg=0x7fffafc19b38) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:1047
#6  0x00000000007182fb in mysql_select (thd=0x7fffafc16070, tables=0x7fffafc60460, wild_num=0x0, fields=..., conds=0x0, og_num=0x0, order=0x0, group=0x0, having=0x0, proc_param=0x0, select_options=0x80040b00, result=0x7fffafc60cd0, unit=0x7fffafc19b38, select_lex=0x7fffafc1a278) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:3788
#7  0x000000000070bb5f in handle_select (thd=0x7fffafc16070, lex=0x7fffafc19a70, result=0x7fffafc60cd0, setup_tables_done_option=0x0) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:374
#8  0x00000000006d7790 in execute_sqlcom_select (thd=0x7fffafc16070, all_tables=0x7fffafc60460) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:6351
#9  0x00000000006ccf3f in mysql_execute_command (thd=0x7fffafc16070) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:3376
#10 0x00000000006db29d in mysql_parse (thd=0x7fffafc16070, rawbuf=0x7fffafc60088 "select x as FROMTO_x, y from t1 for system_time from timestamp '0-0-0 0:0:0' to timestamp '2018-1-1'", length=0x64, parser_state=0x7ffff7f4bf30, is_com_multi=0x0, is_next_command=0x0) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:7794
```

**Comment by midenok** [comment]
#### Item cached:

```
#0  Item_cache::get_cache (thd=0x7fffb0016070, item=0x7fffb0061490, type=INT_RESULT) at /home/midenok/src/mariadb/midenok/src/sql/item.cc:9079
#1  0x0000000000976886 in Item_cache::get_cache (thd=0x7fffb0016070, item=0x7fffb0061490) at /home/midenok/src/mariadb/midenok/src/sql/item.cc:9060
#2  0x000000000096f34d in Item::cache_const_expr_transformer (this=0x7fffb0061490, thd=0x7fffb0016070, arg=0x7ffff7f4a6a7 "") at /home/midenok/src/mariadb/midenok/src/sql/item.cc:6730
#3  0x00000000009bebb0 in Item_func::compile (this=0x7fffb0061490, thd=0x7fffb0016070, analyzer=(bool (Item::*)(Item * const, uchar **)) 0x96f1a6 <Item::cache_const_expr_analyzer(unsigned char**)>, arg_p=0x7ffff7f4a588, transformer=(Item *(Item::*)(Item * const, THD *, uchar *)) 0x96f314 <Item::cache_const_expr_transformer(THD*, unsigned char*)>, arg_t=0x7ffff7f4a6a7 "") at /home/midenok/src/mariadb/midenok/src/sql/item_func.cc:417
#4  0x00000000009beb2c in Item_func::compile (this=0x7fffb00617b0, thd=0x7fffb0016070, analyzer=(bool (Item::*)(Item * const, uchar **)) 0x96f1a6 <Item::cache_const_expr_analyzer(unsigned char**)>, arg_p=0x7ffff7f4a608, transformer=(Item *(Item::*)(Item * const, THD *, uchar *)) 0x96f314 <Item::cache_const_expr_transformer(THD*, unsigned char*)>, arg_t=0x7ffff7f4a6a7 "") at /home/midenok/src/mariadb/midenok/src/sql/item_func.cc:412
#5  0x0000000000993626 in Item_cond::compile (this=0x7fffb0061890, thd=0x7fffb0016070, analyzer=(bool (Item::*)(Item * const, uchar **)) 0x96f1a6 <Item::cache_const_expr_analyzer(unsigned char**)>, arg_p=0x7ffff7f4a6a8, transformer=(Item *(Item::*)(Item * const, THD *, uchar *)) 0x96f314 <Item::cache_const_expr_transformer(THD*, unsigned char*)>, arg_t=0x7ffff7f4a6a7 "") at /home/midenok/src/mariadb/midenok/src/sql/item_cmpfunc.cc:4735
#6  0x0000000000751c20 in JOIN::cache_const_exprs (this=0x7fffb0060cf0) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:25744
#7  0x000000000071190b in JOIN::optimize_inner (this=0x7fffb0060cf0) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:1889
#8  0x000000000070f718 in JOIN::optimize (this=0x7fffb0060cf0) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:1317
#9  0x000000000071831d in mysql_select (thd=0x7fffb0016070, tables=0x7fffb0060460, wild_num=0x0, fields=..., conds=0x0, og_num=0x0, order=0x0, group=0x0, having=0x0, proc_param=0x0, select_options=0x80040b00, result=0x7fffb0060cd0, unit=0x7fffb0019b38, select_lex=0x7fffb001a278) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:3796
```

#### Const check:

```
#0  Item_func_vtq_id::const_item (this=0x7fffb0061490) at /home/midenok/src/mariadb/midenok/src/sql/item_timefunc.h:1356
#1  0x0000000000608536 in Used_tables_and_const_cache::used_tables_and_const_cache_join (this=0x7fffb0061868, item=0x7fffb0061490) at /home/midenok/src/mariadb/midenok/src/sql/item.h:3776
#2  0x00000000009be41f in Item_func::fix_fields (this=0x7fffb00617b0, thd=0x7fffb0016070, ref=0x7fffb00619b8) at /home/midenok/src/mariadb/midenok/src/sql/item_func.cc:232
#3  0x0000000000992cc7 in Item_cond::fix_fields (this=0x7fffb0061890, thd=0x7fffb0016070, ref=0x7fffb00610e8) at /home/midenok/src/mariadb/midenok/src/sql/item_cmpfunc.cc:4525
#4  0x00000000006681f4 in setup_conds (thd=0x7fffb0016070, tables=0x7fffb0060460, leaves=..., conds=0x7fffb00610e8) at /home/midenok/src/mariadb/midenok/src/sql/sql_base.cc:7714
#5  0x000000000070c5fb in setup_without_group (thd=0x7fffb0016070, ref_pointer_array=..., tables=0x7fffb0060460, leaves=..., fields=..., all_fields=..., conds=0x7fffb00610e8, order=0x0, group=0x0, win_specs=..., win_funcs=..., hidden_group_fields=0x7fffb0060fc7, reserved=0x7fffb001a52c) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:638
#6  0x000000000070e508 in JOIN::prepare (this=0x7fffb0060cf0, tables_init=0x7fffb0060460, wild_num=0x0, conds_init=0x0, og_num=0x0, order_init=0x0, skip_order_by=0x0, group_init=0x0, having_init=0x0, proc_param_init=0x0, select_lex_arg=0x7fffb001a278, unit_arg=0x7fffb0019b38) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:1047
#7  0x000000000071833b in mysql_select (thd=0x7fffb0016070, tables=0x7fffb0060460, wild_num=0x0, fields=..., conds=0x0, og_num=0x0, order=0x0, group=0x0, having=0x0, proc_param=0x0, select_options=0x80040b00, result=0x7fffb0060cd0, unit=0x7fffb0019b38, select_lex=0x7fffb001a278) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:3788
#8  0x000000000070bb9f in handle_select (thd=0x7fffb0016070, lex=0x7fffb0019a70, result=0x7fffb0060cd0, setup_tables_done_option=0x0) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:374
#9  0x00000000006d77d0 in execute_sqlcom_select (thd=0x7fffb0016070, all_tables=0x7fffb0060460) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:6351
#10 0x00000000006ccf7f in mysql_execute_command (thd=0x7fffb0016070) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:3376
#11 0x00000000006db2dd in mysql_parse (thd=0x7fffb0016070, rawbuf=0x7fffb0060088 "select x as FROMTO_x, y from t1 for system_time from timestamp '0-0-0 0:0:0' to timestamp '2018-1-1'", length=0x64, parser_state=0x7ffff7f4bf30, is_com_multi=0x0, is_next_command=0x0) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:7794
```

```
#0  Item_func_vtq_id::const_item (this=0x7fffb0061490) at /home/midenok/src/mariadb/midenok/src/sql/item_timefunc.h:1356
#1  0x0000000000608536 in Used_tables_and_const_cache::used_tables_and_const_cache_join (this=0x7fffb0061868, item=0x7fffb0061490) at /home/midenok/src/mariadb/midenok/src/sql/item.h:3776
#2  0x0000000000608594 in Used_tables_and_const_cache::used_tables_and_const_cache_update_and_join (this=0x7fffb0061868, item=0x7fffb0061490) at /home/midenok/src/mariadb/midenok/src/sql/item.h:3781
#3  0x00000000006085de in Used_tables_and_const_cache::used_tables_and_const_cache_update_and_join (this=0x7fffb0061868, argc=0x2, argv=0x7fffb0061850) at /home/midenok/src/mariadb/midenok/src/sql/item.h:3792
#4  0x00000000006088e0 in Item_func::update_used_tables (this=0x7fffb00617b0) at /home/midenok/src/mariadb/midenok/src/sql/item_func.h:135
#5  0x0000000000608581 in Used_tables_and_const_cache::used_tables_and_const_cache_update_and_join (this=0x7fffb0061948, item=0x7fffb00617b0) at /home/midenok/src/mariadb/midenok/src/sql/item.h:3780
#6  0x0000000000999ee0 in Used_tables_and_const_cache::used_tables_and_const_cache_update_and_join (this=0x7fffb0061948, list=...) at /home/midenok/src/mariadb/midenok/src/sql/item.h:3805
#7  0x000000000099d390 in Item_cond::update_used_tables (this=0x7fffb0061890) at /home/midenok/src/mariadb/midenok/src/sql/item_cmpfunc.h:2149
#8  0x00000000006be35a in st_select_lex::update_used_tables (this=0x7fffb001a278) at /home/midenok/src/mariadb/midenok/src/sql/sql_lex.cc:4206
#9  0x000000000070fade in JOIN::optimize_inner (this=0x7fffb0060cf0) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:1390
#10 0x000000000070f758 in JOIN::optimize (this=0x7fffb0060cf0) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:1317
#11 0x000000000071835d in mysql_select (thd=0x7fffb0016070, tables=0x7fffb0060460, wild_num=0x0, fields=..., conds=0x0, og_num=0x0, order=0x0, group=0x0, having=0x0, proc_param=0x0, select_options=0x80040b00, result=0x7fffb0060cd0, unit=0x7fffb0019b38, select_lex=0x7fffb001a278) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:3796
#12 0x000000000070bb9f in handle_select (thd=0x7fffb0016070, lex=0x7fffb0019a70, result=0x7fffb0060cd0, setup_tables_done_option=0x0) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:374
#13 0x00000000006d77d0 in execute_sqlcom_select (thd=0x7fffb0016070, all_tables=0x7fffb0060460) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:6351
#14 0x00000000006ccf7f in mysql_execute_command (thd=0x7fffb0016070) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:3376
#15 0x00000000006db2dd in mysql_parse (thd=0x7fffb0016070, rawbuf=0x7fffb0060088 "select x as FROMTO_x, y from t1 for system_time from timestamp '0-0-0 0:0:0' to timestamp '2018-1-1'", length=0x64, parser_state=0x7ffff7f4bf30, is_com_multi=0x0, is_next_command=0x0) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:7794
```
